// Catalogue batch 3 — the DistroSource Originals that are not web templates
// (the ten web templates live in scripts/catalog/originals as DS-ORG-051…060).
// Personal prices were drawn at random between $10 and $200; commercial and
// agency follow the store's 39 / 79 / 149 ratio. Every file these products
// ship is generated by the builders in this folder — no third-party assets.

export const tiers = (p) => [p, p * 2 + 1, Math.round((p * 3.8) / 10) * 10 - 1]

const FONT_LICENCES = [
  ["personal", "Install on your own computers for personal, non-commercial work."],
  ["commercial", "Desktop use plus web and print use for one commercial project or one client, including logos."],
  ["agency", "Desktop, web and app embedding for multiple client projects, up to the limits stated on this page."],
]
const AUDIO_LICENCES = [
  ["personal", "Use in your own non-commercial videos, games, streams and music."],
  ["commercial", "Use in one commercial production or one client project, including monetised video and released music."],
  ["agency", "Use across multiple client productions, games and broadcast projects."],
]

const FONT_COMMON = {
  howTo: ["Unzip the download", "Install the OTF files on macOS (double-click → Install) or Windows (right-click → Install)", "For websites, self-host the WOFF2 files with @font-face — see the included specimen.html", "Pick the weight in your app's font menu"],
  requirements: ["Any app that supports OpenType fonts", "A web server or CDN for WOFF2 files on websites"],
  compat: ["macOS and Windows", "Adobe apps, Figma (local fonts), Affinity, Office, Canva uploads", "All modern browsers via WOFF2"],
}

const AUDIO_COMMON = {
  howTo: ["Unzip the download", "Browse the folders — files are named by category and number", "Drag WAV files into your DAW, video editor or game engine", "Loops carry their tempo and key in the file name, so set your project to match"],
  requirements: ["Any DAW, video editor or game engine that reads WAV", "About 70 MB of free space for the larger packs"],
  compat: ["Ableton Live, FL Studio, Logic Pro, Reaper, GarageBand", "Premiere Pro, DaVinci Resolve, Final Cut Pro", "Unity, Unreal Engine, Godot"],
}

export const PRODUCTS = [
  /* ---------------------------------------------------------------- */
  /* Fonts & Typography                                                 */
  /* ---------------------------------------------------------------- */
  {
    sku: "DS-ORG-061", kind: "font", slug: "meridian-sans-geometric-typeface-family", name: "Meridian Sans — Geometric Typeface Family",
    category: "fonts-typefaces", subcategory: "Geometric Sans", prices: tiers(200), licences: FONT_LICENCES,
    font: { family: "Meridian Sans", files: "MeridianSans", styles: ["Light", "Regular", "Medium", "Bold"], theme: "paper" },
    tagline: "A four-weight geometric sans built from circles and straight lines, for brands, headlines and interfaces.",
    overview: ["Meridian Sans is a geometric sans-serif family drawn from pure shapes: near-circular bowls, straight stems and flat-cut diagonals. It sets headlines with the calm confidence of classic geometric type and stays open and legible at interface sizes.", "Four weights — Light, Regular, Medium and Bold — share the same skeleton, so a brand can move from a thin display line to a heavy call to action without changing voice. Kerning for common pairs such as AV, To and Ya is built in."],
    bestFor: ["Brand identities and logotypes", "Headlines, posters and packaging", "App and website interfaces", "Presentation decks and reports"],
    features: ["Four weights: Light, Regular, Medium and Bold", "Geometric construction with circular bowls and single-storey a and g", "Built-in kerning for common capital and lowercase pairs", "Basic Latin: A–Z, a–z, 0–9, punctuation and symbols, plus curly quotes and dashes", "OTF for desktop and WOFF2 for the web", "Consistent metrics across weights for clean weight changes"],
    get: ["4 OpenType (OTF) font files", "4 WOFF2 web font files", "specimen.html with ready-made @font-face rules", "README and licence"],
    note: "Accented and non-Latin characters are not included.",
    tags: ["geometric sans", "sans serif", "font family", "branding", "headline font"],
  },
  {
    sku: "DS-ORG-062", kind: "font", slug: "rivet-mono-coding-typeface", name: "Rivet Mono — Monospaced Coding Typeface",
    category: "fonts-typefaces", subcategory: "Monospace", prices: tiers(169), licences: FONT_LICENCES,
    font: { family: "Rivet Mono", files: "RivetMono", styles: ["Regular", "Bold"], theme: "code" },
    tagline: "A monospaced typeface with slab details and a slashed zero, made for code, terminals and technical design.",
    overview: ["Rivet Mono is a monospaced typeface for people who read code all day. Every character sits in the same 600-unit cell, the i, l and 1 carry slab details so they never blur together, and the zero is slashed so it cannot be mistaken for a capital O.", "Its geometric bowls and flat terminals give it a crisp, engineered feel that also works in technical branding, dashboards and data-heavy layouts. Regular and Bold cover the full printable ASCII set."],
    bestFor: ["Code editors and terminals", "Developer documentation and product sites", "Dashboards, tables and data layouts", "Technical and industrial branding"],
    features: ["True monospace: every glyph on a 600-unit advance", "Slashed zero and slab-serif i, j, l, r, t, 1 for disambiguation", "Regular and Bold weights", "Full printable ASCII (95 characters) plus curly quotes and dashes", "OTF for desktop and WOFF2 for the web", "Wide bowls for comfortable reading at small sizes"],
    get: ["2 OpenType (OTF) font files", "2 WOFF2 web font files", "specimen.html with ready-made @font-face rules", "README and licence"],
    note: "Accented and non-Latin characters and programming ligatures are not included.",
    tags: ["monospace", "coding font", "terminal", "developer", "slab"],
  },
  {
    sku: "DS-ORG-063", kind: "font", slug: "blockhaus-pixel-display-font", name: "Blockhaus Pixel — Pixel Display Font",
    category: "fonts-typefaces", subcategory: "Pixel & Display", prices: tiers(54), licences: FONT_LICENCES,
    font: { family: "Blockhaus Pixel", files: "BlockhausPixel", styles: ["Regular"], theme: "pixel" },
    tagline: "A crisp 5 × 7 pixel font for game interfaces, retro branding and low-resolution displays.",
    overview: ["Blockhaus Pixel is a bitmap-style display font drawn on a strict 5 × 7 grid and exported as clean vector outlines, so it stays razor sharp at any size — perfect at exact multiples of 7 pixels for true pixel-art rendering.", "It covers the full printable ASCII set with descenders for g, j, p, q and y, which makes it practical for game HUDs, scoreboards, retro posters and device-style readouts rather than just a novelty headline face."],
    bestFor: ["Game HUDs, menus and scoreboards", "Retro and arcade branding", "Stream overlays and alerts", "LED and device-style readouts"],
    features: ["5 × 7 pixel grid with true descenders", "Full printable ASCII (95 characters)", "Monospaced 6-pixel cells for aligned scores and timers", "Vector outlines that stay crisp at any size", "OTF for desktop and WOFF2 for the web", "Pixel-perfect at multiples of 7 px"],
    get: ["1 OpenType (OTF) font file", "1 WOFF2 web font file", "specimen.html with ready-made @font-face rules", "README and licence"],
    note: "Accented and non-Latin characters are not included.",
    tags: ["pixel font", "bitmap", "retro", "game font", "8-bit"],
  },

  /* ---------------------------------------------------------------- */
  /* Media — Audio                                                      */
  /* ---------------------------------------------------------------- */
  {
    sku: "DS-ORG-064", kind: "audio", slug: "monolith-cinematic-toolkit", name: "Monolith — Cinematic Sound Design Toolkit",
    category: "audio", subcategory: "Cinematic SFX", prices: tiers(197), licences: AUDIO_LICENCES, theme: ["#0b0d12", "#e8a33d"],
    groups: [["Riser", "Risers"], ["Impact", "Impacts"], ["Whoosh", "Whooshes"], ["Braam", "Braams"], ["SubDrop", "Sub drops"], ["ReverseHit", "Reverse hits"], ["TensionDrone", "Tension drones"]],
    tagline: "Forty synthesised risers, impacts, whooshes, braams and drones for trailers, edits and game cinematics.",
    overview: ["Monolith is a trailer-style sound design toolkit: tension that builds, hits that land and transitions that move the picture. Risers come in 4, 6 and 8 second lengths so they line up with edits, impacts layer a sub drop, a noise burst and a metallic ring, and braams are built from detuned low chords pushed through saturation.", "Every sound was synthesised by DistroSource from oscillators, noise and filters, then mastered to a consistent peak level, so they sit together in a mix without per-file gain riding."],
    bestFor: ["Trailers, teasers and promos", "YouTube edits and short films", "Game cinematics and menus", "Podcast and stream stingers"],
    features: ["8 risers at 4, 6 and 8 seconds", "8 layered impacts with reverb tails", "8 stereo whooshes with movement", "6 braams, 4 sub drops, 3 reverse hits and 3 tension drones", "44.1 kHz / 16-bit stereo WAV", "Peak-normalised for consistent levels"],
    tags: ["cinematic", "trailer", "sound effects", "impacts", "risers"],
  },
  {
    sku: "DS-ORG-065", kind: "audio", slug: "late-night-lofi-loop-kit", name: "Late Night — Lo-Fi Loop Kit",
    category: "audio", subcategory: "Music Loops", prices: tiers(147), licences: AUDIO_LICENCES, theme: ["#1b1424", "#f4a261"],
    groups: [["LoFi_Chords", "Chord loops"], ["LoFi_Drums", "Drum loops"], ["LoFi_Bass", "Bass loops"], ["LoFi_Texture", "Textures"]],
    tagline: "Thirty-two tempo-labelled lo-fi loops — electric-piano chords, swung drums, bass and vinyl textures.",
    overview: ["Late Night is a lo-fi hip-hop construction kit at 82 and 90 BPM. Electric-piano chord loops are voiced as rich sevenths and ninths with gentle tape wobble, drum loops are swung and softened with vinyl crackle, and bass loops follow the same progressions so kits fit together immediately.", "Every loop is exactly four bars and labelled with its key and tempo, so it drops onto your DAW grid without stretching. Textures — vinyl, tape hiss, rain on glass and room tone — are seamless loops for glueing a mix together."],
    bestFor: ["Lo-fi and chill-hop producers", "Study and stream background music", "Content creators needing quick beds", "Game menus and cosy game soundtracks"],
    features: ["12 electric-piano chord loops in six keys", "10 swung drum loops at 82 and 90 BPM", "6 bass loops matching the chord keys", "4 seamless textures: vinyl, tape hiss, rain, room tone", "Key and tempo in every file name", "44.1 kHz / 16-bit stereo WAV, four-bar loops"],
    tags: ["lo-fi", "loops", "chill hop", "hip hop", "sample pack"],
  },
  {
    sku: "DS-ORG-066", kind: "audio", slug: "driftfield-ambient-textures", name: "Driftfield — Ambient Texture Loops",
    category: "audio", subcategory: "Ambient & Drones", prices: tiers(103), licences: AUDIO_LICENCES, theme: ["#0c1a1d", "#7fd1c7"],
    groups: [["Ambient_Pad", "Pads"], ["Ambient_Drone", "Drones"], ["Ambient_Shimmer", "Shimmers"], ["Ambient_Wind", "Wind"], ["Ambient_Bells", "Bell clouds"]],
    tagline: "Twelve seamless 32-second ambient loops — pads, drones, shimmers, wind and bell clouds.",
    overview: ["Driftfield is a collection of slow-moving ambient beds for film, games, meditation apps and music. Each texture is exactly 32 seconds and loops seamlessly, so it can run under a scene for as long as you need without an audible seam.", "Pads use detuned voices through slowly sweeping filters, drones stack beating harmonics, shimmers layer octaves in a long reverb, and the bell clouds scatter tuned bells across the stereo field. Musical textures are labelled with their key."],
    bestFor: ["Film and documentary underscore", "Game exploration and menu beds", "Meditation, sleep and wellness apps", "Ambient and electronic music"],
    features: ["3 pads, 3 drones and 2 shimmers labelled by key", "2 wind textures and 2 bell clouds", "Every file a seamless 32-second loop", "Wide stereo image with long reverbs", "44.1 kHz / 16-bit stereo WAV", "Levels matched for layering"],
    tags: ["ambient", "drones", "pads", "atmosphere", "loops"],
  },
  {
    sku: "DS-ORG-067", kind: "audio", slug: "interface-ui-sound-pack", name: "Interface — UI Sound Effects Pack",
    category: "audio", subcategory: "UI & Interface SFX", prices: tiers(64), licences: AUDIO_LICENCES, theme: ["#0f1720", "#5aa9ff"],
    groups: [["UI_Click", "Clicks"], ["UI_Tap", "Taps"], ["UI_Toggle", "Toggles"], ["UI_Confirm", "Confirmations"], ["UI_Error", "Errors"], ["UI_Notification", "Notifications"], ["UI_Swipe", "Swipes"], ["UI_Keypress", "Keypresses"]],
    tagline: "Sixty short, clean interface sounds — clicks, taps, toggles, confirmations, errors and notifications.",
    overview: ["Interface is a set of short, tasteful sounds for apps, websites, games and kiosks. Clicks and taps are tight enough to repeat without fatigue, toggles come in matched on/off pairs, confirmations are bright little chords and errors say no without sounding alarming.", "Everything is trimmed to the first sample and peak-normalised, so the sounds play instantly and sit at the same level — no editing before you drop them into your product."],
    bestFor: ["Mobile and web apps", "Game menus and HUDs", "Kiosks, dashboards and smart devices", "Video UI animations and explainers"],
    features: ["10 clicks and 8 taps", "4 matched toggle on/off pairs", "8 confirmation chords and 6 error sounds", "10 notification tones", "6 swipes and 4 keypresses", "Trimmed, peak-normalised 44.1 kHz / 16-bit stereo WAV"],
    tags: ["ui sounds", "interface", "app sounds", "notifications", "clicks"],
  },
  {
    sku: "DS-ORG-068", kind: "audio", slug: "arcade-game-sfx-pack", name: "Arcade — Retro Game SFX Pack",
    category: "audio", subcategory: "Game SFX", prices: tiers(63), licences: AUDIO_LICENCES, theme: ["#140a24", "#ff4fd8"],
    groups: [["Game_Coin", "Coins"], ["Game_Jump", "Jumps"], ["Game_PowerUp", "Power-ups"], ["Game_Laser", "Lasers"], ["Game_Explosion", "Explosions"], ["Game_Hit", "Hits"], ["Game_Pickup", "Pickups"], ["Game_MenuBlip", "Menu blips"], ["Game_Jingle", "Jingles"], ["Game_", "Extras"]],
    tagline: "Sixty chiptune-style game sounds — coins, jumps, power-ups, lasers, explosions and jingles.",
    overview: ["Arcade is a retro game sound effects pack built from square, triangle and noise channels in the spirit of classic consoles, with enough variation per category that repeated actions never sound copy-pasted.", "It covers the moments every platformer, shooter and puzzle game needs — collecting, jumping, powering up, firing, taking hits and winning or losing — plus six short jingles for level ends and game overs."],
    bestFor: ["Platformers and arcade games", "Game jams and prototypes", "Retro-styled apps and websites", "Stream alerts and overlays"],
    features: ["6 variations each of coins, jumps, power-ups, lasers, explosions, hits, pickups and menu blips", "6 jingles: win, level up, lose, game over, checkpoint and secret", "6 extras: teleport, shield, dash, heal, door and step", "Chiptune-style square, triangle and noise voices", "44.1 kHz / 16-bit stereo WAV", "Trimmed and peak-normalised"],
    tags: ["game sfx", "chiptune", "8-bit", "retro", "sound effects"],
  },
  {
    sku: "DS-ORG-069", kind: "audio", slug: "neon-drive-drum-kit", name: "Neon Drive — Synthwave Drum Kit",
    category: "audio", subcategory: "Drum Kits", prices: tiers(31), licences: AUDIO_LICENCES, theme: ["#12051f", "#ff5ea8"],
    groups: [["Kick", "Kicks"], ["Snare", "Snares"], ["Clap", "Claps"], ["HiHat_Closed", "Closed hats"], ["HiHat_Open", "Open hats"], ["Tom", "Toms"], ["Cymbal", "Cymbals"], ["Perc", "Percussion"]],
    tagline: "Eighty synthwave drum one-shots — punchy kicks, gated snares, claps, hats, toms and cymbals.",
    overview: ["Neon Drive is an eighties-inspired drum kit for synthwave, retrowave and electro. Kicks range from tight and clicky to long and boomy, half of the snares carry that big gated-reverb tail, and the toms roll across the stereo field the way a studio kit should.", "Every one-shot is synthesised, trimmed and peak-normalised, so you can load the whole folder into a sampler or drum rack and start programming straight away."],
    bestFor: ["Synthwave, retrowave and electro producers", "Beat makers building drum racks", "Game and film scores with an 80s feel", "Content creators needing quick drums"],
    features: ["14 kicks and 14 snares, 7 with gated reverb", "8 claps, 10 closed hats and 8 open hats", "12 toms across high, mid and low", "6 cymbals and 8 percussion one-shots", "44.1 kHz / 16-bit stereo WAV", "Trimmed and peak-normalised"],
    tags: ["drum kit", "synthwave", "one shots", "80s drums", "retrowave"],
  },
]

/* ------------------------------------------------------------------ */
/* 3D & Print                                                           */
/* ------------------------------------------------------------------ */

const MODEL_LICENCES = [
  ["personal", "Use in your own non-commercial games, renders and animations."],
  ["commercial", "Use in one commercial game, film, visualisation or client project."],
  ["agency", "Use across multiple client projects and commercial releases."],
]
const PRINT_LICENCES = [
  ["personal", "Print for yourself, your home and gifts. Not for sale."],
  ["commercial", "Sell physical prints you make yourself, up to 250 copies of each part."],
  ["agency", "Sell unlimited physical prints you make, and print for clients."],
]
const KIT_COMMON = {
  compat: ["Blender 3.6+ (File → Import → glTF 2.0 or OBJ)", "Unity 2021+ (glTFast or OBJ import)", "Unreal Engine 5 (glTF import)", "Godot 4 (native glTF)"],
  requirements: ["Any 3D app or engine that imports glTF 2.0 (GLB) or OBJ"],
  howTo: ["Unzip the download", "Import the GLB files — materials and hierarchy come with them", "Use OBJ if your tool prefers it; OBJ files carry geometry and material names", "Pieces share a common scale and pivot at the base, so they snap together"],
}
const PRINT_COMMON = {
  compat: ["PrusaSlicer, Cura, Bambu Studio, OrcaSlicer", "Any FDM printer with a 200 × 200 mm bed or larger", "Resin printers for the smaller parts"],
  requirements: ["A slicer that opens STL files", "PLA or PETG filament"],
  howTo: ["Unzip the download and open an STL in your slicer", "Parts are exported on the bed at real size in millimetres", "Slice with the settings in the README (0.2 mm layers, 3 walls, 15% infill)", "Print, remove from the bed and use — no supports needed unless the README says so"],
}

PRODUCTS.push(
  {
    sku: "DS-ORG-070", kind: "model", model: "kit", view: "scifi", slug: "modular-sci-fi-corridor-kit-3d", name: "Modular Sci-Fi Corridor Kit — 3D Asset Pack",
    category: "3d-assets", subcategory: "Game Environments", prices: tiers(164), licences: MODEL_LICENCES, common: KIT_COMMON,
    tagline: "Eleven snap-together sci-fi corridor pieces on a 4-metre grid — floors, walls, doorways, lights and props — as GLB and OBJ.",
    overview: ["The Modular Sci-Fi Corridor Kit builds spaceship interiors, research stations and industrial bases from eleven pieces that share one 4-metre grid. Floors, walls, a window wall, a doorway and ceiling lights tile together without gaps, and crates, a console, pipes, a vent and a corner pillar dress the space.", "Every piece is modelled with bevelled panels, trims and emissive light strips, kept light enough for real-time use, and exported as glTF (GLB) with named materials — panel, frame, trim, hazard, light strip and screen — so re-skinning the whole kit is a few material edits."],
    bestFor: ["Indie games and game jams", "Level blockouts that need to look finished", "Film and animation previs", "VR and real-time visualisation"],
    features: ["11 modular pieces on a 4 m grid", "Emissive light strips, screens and warning lights", "Named, shared materials for quick re-skinning", "Pivots at the base of each piece for grid snapping", "GLB per piece plus one combined GLB", "OBJ per piece for tools without glTF"],
    get: ["11 GLB files and 1 combined GLB", "11 OBJ files", "README with piece list, sizes and triangle counts", "Licence"],
    note: "Materials are flat PBR colours rather than texture maps, which keeps the kit light and easy to restyle.",
    tags: ["sci-fi", "modular", "3d models", "game assets", "corridor"],
  },
  {
    sku: "DS-ORG-071", kind: "model", model: "kit", view: "nature", slug: "low-poly-nature-kit-3d", name: "Low-Poly Nature Kit — 3D Asset Pack",
    category: "3d-assets", subcategory: "Nature & Props", prices: tiers(115), licences: MODEL_LICENCES, common: KIT_COMMON,
    tagline: "Sixteen faceted low-poly trees, rocks, bushes and props for stylised games and illustrations, as GLB and OBJ.",
    overview: ["The Low-Poly Nature Kit is a set of sixteen hand-shaped stylised pieces — three pines, two leafy trees in summer and autumn colours, bushes, four rocks, a stump, a log, grass tufts, mushrooms and flowers — built with crisp faceted shading that reads clearly from a top-down or third-person camera.", "Every piece is extremely light, so you can scatter hundreds across a level. Pivots sit at ground level and colours use a small named palette, making it easy to shift the whole kit to a new season or art style."],
    bestFor: ["Stylised and mobile games", "Isometric and top-down levels", "Illustrations and motion graphics", "Prototypes that need to look good"],
    features: ["16 pieces: pines, leafy trees, bushes, rocks and props", "Faceted low-poly shading", "Summer and autumn foliage colours", "Ground-level pivots for easy scattering", "Tiny triangle counts for large scenes", "GLB and OBJ for every piece"],
    get: ["16 GLB files and 1 combined GLB", "16 OBJ files", "README with piece list, sizes and triangle counts", "Licence"],
    note: "Colours are flat PBR materials; no texture maps are needed or included.",
    tags: ["low poly", "nature", "trees", "3d models", "stylised"],
  },
  {
    sku: "DS-ORG-072", kind: "model", model: "kit", view: "furniture", slug: "stylised-furniture-set-3d", name: "Stylised Furniture Set — 3D Asset Pack",
    category: "3d-assets", subcategory: "Furniture & Interiors", prices: tiers(73), licences: MODEL_LICENCES, common: KIT_COMMON,
    tagline: "Twelve soft, stylised living-room pieces — sofa, chairs, tables, lamp, bookshelf and plants — as GLB and OBJ.",
    overview: ["The Stylised Furniture Set furnishes a warm, modern room in one import: a three-seat sofa and matching armchair, dining and coffee tables, a chair and a stool, a floor lamp, a filled bookshelf, a side table, a potted plant, a vase and a rug.", "Pieces are modelled at real-world scale with rounded edges and simple oak, walnut, fabric and brass materials, so they drop into architectural visualisation, cosy games and product scenes without looking out of place."],
    bestFor: ["Cosy and simulation games", "Interior and architectural visualisation", "Product shots and 3D illustrations", "VR rooms and virtual sets"],
    features: ["12 pieces at real-world scale", "Rounded, soft stylised forms", "Oak, walnut, fabric, brass and ceramic materials", "Bookshelf filled with individual books", "Glowing bulb in the floor lamp for rendering", "GLB and OBJ for every piece"],
    get: ["12 GLB files and 1 combined GLB", "12 OBJ files", "README with piece list, sizes and triangle counts", "Licence"],
    note: "Materials are flat PBR colours rather than texture maps.",
    tags: ["furniture", "interior", "3d models", "stylised", "living room"],
  },
  {
    sku: "DS-ORG-073", kind: "model", model: "print", slug: "modular-desk-organiser-3d-print-system", name: "Modular Desk Organiser — 3D Print System",
    category: "3d-print", subcategory: "Home & Desk", prices: tiers(174), licences: PRINT_LICENCES, common: PRINT_COMMON,
    tagline: "Ten printable bins, trays, a pen cup and locating frames on a 40 mm grid, ready to slice as STL.",
    overview: ["The Modular Desk Organiser is a printable system for drawers and desktops. Bins and trays come in sizes that fit a 40 mm grid, so any combination tiles neatly, and two locating frames hold them in place so nothing slides around when a drawer opens.", "Every part is a clean, watertight solid with 1.6 mm walls, a 1.2 mm floor and rounded corners, designed to print without supports in PLA or PETG."],
    bestFor: ["Desk drawers and workbenches", "Stationery, craft and electronics parts", "Makers selling organisers", "Anyone with a 3D printer and a messy drawer"],
    features: ["Bins in 1×1, 1×2 and 2×2 at 40 mm and 70 mm tall", "Low trays in 1×3 and 2×3", "70 mm pen cup", "3×3 and 2×4 locating frames", "Watertight solids that slice without repair", "Prints without supports"],
    get: ["10 STL files at real size (mm)", "README with sizes and recommended print settings", "Licence"],
    tags: ["3d printing", "stl", "desk organiser", "storage", "modular"],
  },
  {
    sku: "DS-ORG-074", kind: "model", model: "print", slug: "dungeon-terrain-tiles-3d-print-set", name: "Dungeon Terrain Tiles — 3D Print Set",
    category: "3d-print", subcategory: "Tabletop Gaming", prices: tiers(155), licences: PRINT_LICENCES, common: PRINT_COMMON,
    tagline: "Eleven printable 2-inch terrain tiles, wall panels and pillars for tabletop RPG maps, with a 1-inch grid built in.",
    overview: ["Dungeon Terrain Tiles give tabletop games a physical map that looks the part. Six floor tiles — two flagstone patterns, cobble, planks, an iron grate and rubble — each carry a subtle 1-inch grid so movement stays easy to count.", "Brick and stone wall panels print flat for crisp detail and stand up behind any tile, and two pillars add height to rooms and corridors. Surfaces are sculpted as real relief, not flat decals, so they take a dry-brush beautifully."],
    bestFor: ["Tabletop RPG and skirmish games", "Dungeon crawls and one-shots", "Terrain painters and hobbyists", "Game stores selling printed terrain"],
    features: ["6 floor tiles at 2 × 2 inches with a 1-inch grid", "Brick, half-height brick and stone wall panels", "Round and square pillars", "Sculpted relief made for dry-brushing", "Watertight solids at real size", "Walls print flat, no supports"],
    get: ["11 STL files at real size (mm)", "README with sizes and recommended print settings", "Licence"],
    tags: ["tabletop terrain", "dungeon tiles", "stl", "rpg", "3d printing"],
  },
  {
    sku: "DS-ORG-075", kind: "model", model: "print", slug: "geometric-planter-collection-3d-print", name: "Geometric Planter Collection — 3D Print Set",
    category: "3d-print", subcategory: "Home & Garden", prices: tiers(133), licences: PRINT_LICENCES, common: PRINT_COMMON,
    tagline: "Twelve faceted planters and saucers in hexagonal, octagonal and twelve-sided forms, each with a drainage hole.",
    overview: ["The Geometric Planter Collection is a family of faceted pots in three forms — six, eight and twelve sides — and three sizes, plus matching saucers. The flat facets catch light the way ceramic does and print beautifully in matte or silk filament.", "Every planter has a drainage hole and a 2.4 mm wall, and tapers outward so it prints cleanly without supports. The small size suits succulents, the large one a proper houseplant."],
    bestFor: ["Succulents, herbs and houseplants", "Gifts and home décor", "Makers selling planters", "Desk and shelf styling"],
    features: ["Hexagonal, octagonal and dodecagonal forms", "Small, medium and large sizes up to 152 mm across", "Three matching saucers", "Drainage hole in every planter", "Outward taper that prints without supports", "Watertight solids at real size"],
    get: ["12 STL files at real size (mm)", "README with sizes and recommended print settings", "Licence"],
    tags: ["planter", "stl", "geometric", "home decor", "3d printing"],
  },
  {
    sku: "DS-ORG-076", kind: "model", model: "print", slug: "cable-management-hook-set-3d-print", name: "Cable & Hook Set — 3D Print Set",
    category: "3d-print", subcategory: "Home & Desk", prices: tiers(131), licences: PRINT_LICENCES, common: PRINT_COMMON,
    tagline: "Ten printable wall hooks, cable clips, a cable comb, a cord wrap and a key rail for tidy desks and hallways.",
    overview: ["The Cable & Hook Set tidies the things that tangle. Wall hooks come in three sizes plus a wide headphone hook, each with two screw holes; adhesive cable clips hold 5 to 16 mm cables; a six-slot comb keeps desk cables in order; and a cord wrap and four-hook key rail finish the set.", "Parts are designed for PLA or PETG with screw holes sized for 4 mm screws. Hooks print on their side for the strongest layer direction."],
    bestFor: ["Desk setups and home offices", "Hallways and entryways", "Workshops and studios", "Makers selling practical prints"],
    features: ["Small, medium and large wall hooks plus a headphone hook", "Cable clips for 5–16 mm cables", "Six-slot cable comb and cord wrap", "Four-hook key rail with screw holes", "Holes sized for 4 mm screws", "Print orientation noted for each part"],
    get: ["10 STL files at real size (mm)", "README with sizes, print orientation and settings", "Licence"],
    note: "Wall hooks and the key rail are two bodies — a screw plate and the hook arm — in one file; slicers merge them automatically.",
    tags: ["cable management", "wall hook", "stl", "desk setup", "3d printing"],
  },
  {
    sku: "DS-ORG-077", kind: "model", model: "print", slug: "phone-and-tablet-stand-pack-3d-print", name: "Phone & Tablet Stand Pack — 3D Print Set",
    category: "3d-print", subcategory: "Home & Desk", prices: tiers(36), licences: PRINT_LICENCES, common: PRINT_COMMON,
    tagline: "Four printable stands — upright and low phone stands, a tablet stand and a mini stand — with a front lip and cut-out frame.",
    overview: ["The Phone & Tablet Stand Pack gives every device on your desk a place to lean. The upright phone stand suits video calls, the low stand suits reading and notifications, the tablet stand holds a device up to 12.9 inches, and the mini stand fits small phones and e-readers.", "Each stand is a single solid profile with a front lip, a groove that clears most cases and a triangular cut-out that saves filament. They print quickly, upright and without supports."],
    bestFor: ["Desks, kitchens and bedside tables", "Video calls and recipes", "Gifts and quick prints", "Makers selling desk accessories"],
    features: ["Upright and low phone stands", "Tablet stand for devices up to 12.9 inches", "Mini stand for small phones and e-readers", "Front lip with case-clearing groove", "Filament-saving cut-out", "Prints upright without supports"],
    get: ["4 STL files at real size (mm)", "README with sizes and recommended print settings", "Licence"],
    tags: ["phone stand", "tablet stand", "stl", "desk", "3d printing"],
  },
)

/* ------------------------------------------------------------------ */
/* Business & Office                                                    */
/* ------------------------------------------------------------------ */

const BUSINESS_LICENCES = [
  ["personal", "For your own business, job search or personal planning."],
  ["commercial", "For one company or one client, including customising the files for them."],
  ["agency", "For multiple clients and client work, up to the limits stated on this page."],
]
const OFFICE_COMMON = {
  compat: ["Microsoft Word, Excel and PowerPoint 2016 or later, and Microsoft 365", "Google Docs, Sheets and Slides (upload and open)", "Apple Pages, Numbers and Keynote (open the Office files)", "LibreOffice"],
  requirements: ["An app that opens DOCX, XLSX or PPTX files, or a PDF reader for the PDF versions"],
  howTo: ["Unzip the download", "Open the file you need — DOCX, XLSX or PPTX, with a PDF copy alongside", "Replace the fictional sample content with your own", "Save a copy under your own name before sharing"],
}
const NOTION_COMMON = {
  compat: ["Notion on any plan (Free, Plus, Business)", "Notion web, desktop and mobile apps"],
  requirements: ["A Notion account", "About ten minutes for import and setup"],
  howTo: ["Unzip the download", "In Notion open Settings → Import and import the Markdown pages, then each CSV as a database", "Follow Setup_Guide.pdf to link the databases and add the recommended views", "Delete the fictional sample rows and add your own"],
}

PRODUCTS.push(
  {
    sku: "DS-ORG-078", kind: "doc", slug: "startup-operations-kit-business-templates", name: "Startup Operations Kit — Business Plan, Financial Model & Cap Table",
    category: "business-templates", subcategory: "Startup & Finance", prices: tiers(163), licences: BUSINESS_LICENCES, common: OFFICE_COMMON,
    tagline: "A business plan, a working 12-month financial model, a cap table with round modelling, an OKR tracker and board templates.",
    overview: ["The Startup Operations Kit covers the documents a young company is asked for again and again. The business plan walks through twelve sections with guidance lines and a complete worked example. The financial model is a real Excel model: change the price, growth, churn, team and costs on the Assumptions sheet and the 12-month forecast, cash position and summary recalculate.", "The cap table models the next round — pre-money, investment, price per share and dilution — and the OKR tracker calculates progress and status from start, target and current values. An investor update and a board meeting agenda complete the set, every file supplied as an editable Office document with a PDF copy."],
    bestFor: ["Founders preparing to raise", "Accelerator and incubator cohorts", "Small businesses writing a plan for a bank or grant", "Operators running monthly investor updates and board meetings"],
    features: ["12-section business plan with guidance and a worked example", "12-month financial model driven by one Assumptions sheet", "Cash runway, first profitable month and burn calculated automatically", "Cap table with next-round dilution modelling", "OKR tracker with automatic progress and status", "Investor update and board agenda templates"],
    get: ["Business_Plan.docx, Investor_Update.docx and Board_Meeting_Agenda.docx", "Financial_Model.xlsx, Cap_Table.xlsx and OKR_Tracker.xlsx", "PDF copies of every file", "README and licence"],
    note: "All company names, people and figures in the samples are fictional.",
    media: [{ type: "fan", images: ["Business_Plan.png", "Financial_Model-Forecast.png", "Cap_Table-CapTable.png"] }, { type: "frame", image: "Financial_Model-Forecast.png", caption: "Financial_Model.xlsx · 12-month forecast calculated in Excel" }, { type: "grid", images: ["Cap_Table-CapTable.png", "OKR_Tracker-OKRs.png", "Financial_Model-Assumptions.png"], caption: "Cap table, OKR tracker and model assumptions" }],
    tags: ["business plan", "financial model", "cap table", "startup", "excel template"],
  },
  {
    sku: "DS-ORG-079", kind: "doc", slug: "invoice-and-quote-pack-business-templates", name: "Invoice & Quote Pack — Excel and Word Templates",
    category: "business-templates", subcategory: "Invoicing", prices: tiers(17), licences: BUSINESS_LICENCES, common: OFFICE_COMMON,
    tagline: "Invoice, quote, receipt and credit note templates that total themselves in Excel, plus a Word invoice.",
    overview: ["The Invoice & Quote Pack gives a freelancer or small business four matching documents: an invoice, a quote, a receipt and a credit note. In the Excel versions you type descriptions, quantities and prices, and the line amounts, subtotal, tax and total calculate — change the tax rate once and everything updates.", "Due dates and quote expiry dates follow the issue date automatically. A Word invoice is included for people who prefer to type everything, and every template has a PDF copy so you can see the layout before you start."],
    bestFor: ["Freelancers and consultants", "Small agencies and studios", "Tradespeople and service businesses", "Anyone replacing invoices typed from scratch"],
    features: ["Invoice, quote, receipt and credit note in Excel", "Automatic line amounts, subtotal, tax and total", "Due and expiry dates calculated from the issue date", "Ten line items per document", "Word invoice for manual editing", "Blue input cells so you know exactly what to change"],
    get: ["Invoice.xlsx, Quote.xlsx, Receipt.xlsx and Credit_Note.xlsx", "Invoice_Word.docx", "PDF copies of every file", "README and licence"],
    note: "Sample company and client details are placeholders.",
    media: [{ type: "fan", images: ["Invoice-Invoice.png", "Quote-Quote.png", "Receipt-Receipt.png"] }, { type: "frame", image: "Invoice-Invoice.png", caption: "Invoice.xlsx · totals and tax calculated by Excel", portrait: true }, { type: "grid", images: ["Quote-Quote.png", "Credit_Note-CreditNote.png", "Invoice_Word.png"], caption: "Quote, credit note and Word invoice" }],
    tags: ["invoice template", "quote", "receipt", "excel", "small business"],
  },
  {
    sku: "DS-ORG-080", kind: "notion", slug: "agency-operating-system-notion-template", name: "Agency OS — Notion Workspace Template",
    category: "notion-workspace-templates", subcategory: "Agency & Operations", prices: tiers(195), licences: BUSINESS_LICENCES, common: NOTION_COMMON,
    pack: "Agency OS", db2: "Projects", page: "Client onboarding",
    tagline: "A Notion workspace for running a small agency — clients, projects, tasks, invoices, meetings, team, leads and playbooks.",
    overview: ["Agency OS is a Notion workspace for small creative and digital agencies. Seven databases cover the whole client lifecycle — leads, clients, projects, tasks, meetings, invoices and team capacity — and six playbook pages turn the processes most agencies keep in their heads into checklists anyone can follow.", "It ships as a Notion import package of Markdown pages and CSV databases with sample rows, plus a setup guide that shows how to link the databases and add the recommended board, calendar and filtered views."],
    bestFor: ["Studios and agencies of 2–20 people", "Freelancers growing into a team", "Account managers juggling several clients", "Agencies moving off spreadsheets"],
    features: ["7 databases: Clients, Projects, Tasks, Invoices, Meetings, Team and Leads", "6 playbooks: onboarding, kickoff, weekly status, retrospective, rate card, invoicing SOP", "Sample rows that show how each database is meant to be used", "Setup guide with relation links and recommended views", "Works on Notion's free plan", "Plain Markdown and CSV, so the content is portable"],
    get: ["Notion import package (Markdown pages and CSV databases)", "Setup_Guide.docx and Setup_Guide.pdf", "README and licence"],
    note: "CSV import creates text columns where databases link to each other; the setup guide shows how to turn them into relations in a few minutes.",
    tags: ["notion template", "agency", "project management", "crm", "workspace"],
  },
  {
    sku: "DS-ORG-081", kind: "notion", slug: "creator-content-planner-notion-template", name: "Creator Content Planner — Notion Template",
    category: "notion-workspace-templates", subcategory: "Content & Creators", prices: tiers(48), licences: BUSINESS_LICENCES, common: NOTION_COMMON,
    pack: "Creator Content Planner", db2: "Sponsors", page: "Video script template",
    tagline: "A Notion planner for creators — content calendar, ideas, sponsors, channel stats and series, with script and posting templates.",
    overview: ["The Creator Content Planner keeps a channel's pipeline in one place: ideas scored by effort and potential, a content calendar across platforms, sponsor deals with deliverables and due dates, monthly channel stats, and the series that give a channel its rhythm.", "Four templates — a video script, a sponsor brief, a posting checklist and a thumbnail checklist — cover the steps that are easy to skip on a busy week. It imports into Notion as Markdown and CSV with a short setup guide."],
    bestFor: ["YouTubers, streamers and podcasters", "Small creator teams and editors", "Creators managing sponsorships", "Newsletter writers planning a content calendar"],
    features: ["5 databases: Content Calendar, Ideas, Sponsors, Channel Stats and Series", "Video script, sponsor brief, posting and thumbnail templates", "Calendar and board views described in the setup guide", "Sample rows for every database", "Works on Notion's free plan", "Plain Markdown and CSV"],
    get: ["Notion import package (Markdown pages and CSV databases)", "Setup_Guide.docx and Setup_Guide.pdf", "README and licence"],
    note: "Sample channels, brands and figures are fictional.",
    tags: ["notion template", "content calendar", "youtube", "creator", "planner"],
  },
  {
    sku: "DS-ORG-082", kind: "doc", slug: "pitch-deck-template-presentation", name: "Pitch Deck Template — 14 Slides for PowerPoint",
    category: "presentation-templates", subcategory: "Pitch Decks", prices: tiers(35), licences: BUSINESS_LICENCES, common: OFFICE_COMMON,
    tagline: "A clean 14-slide investor pitch deck in PowerPoint — problem to ask — with charts built from editable shapes.",
    overview: ["The Pitch Deck Template follows the order investors expect: problem, solution, product, market, business model, traction, competition, go-to-market, team, financials, roadmap and the ask. Each slide is filled with a worked example so you can see how much to say — and how little.", "Everything is built from native PowerPoint shapes and text, including the traction chart, market circles, competition matrix and use-of-funds bars, so colours, numbers and labels are edited in place without a chart plug-in. It opens in Keynote and Google Slides too."],
    bestFor: ["Founders raising a pre-seed or seed round", "Accelerator demo days", "Sales and partnership decks", "Students and pitch competitions"],
    features: ["14 slides from title to thank-you", "Traction chart, market sizing, competition matrix and roadmap from native shapes", "Navy, paper and orange palette you can re-theme in minutes", "16:9 widescreen", "Worked example content on every slide", "PDF copy for sharing"],
    get: ["Pitch_Deck.pptx", "Pitch_Deck.pdf", "README and licence"],
    note: "The example company, people and figures are fictional.",
    media: [{ type: "fan", images: ["slides/slide-01.png", "slides/slide-05.png", "slides/slide-07.png"], wide: true }, { type: "grid", images: ["slides/slide-02.png", "slides/slide-03.png", "slides/slide-04.png", "slides/slide-06.png", "slides/slide-08.png", "slides/slide-10.png"], caption: "Problem, solution, product, business model, competition and team", wide: true }, { type: "grid", images: ["slides/slide-11.png", "slides/slide-12.png", "slides/slide-13.png", "slides/slide-14.png"], caption: "Financials, roadmap, the ask and close", wide: true }],
    tags: ["pitch deck", "powerpoint", "startup", "presentation", "investor"],
  },
  {
    sku: "DS-ORG-083", kind: "doc", slug: "undated-daily-weekly-planner-printable", name: "Undated Planner — Printable Daily, Weekly & Monthly Pages",
    category: "productivity", subcategory: "Printable Planners", prices: tiers(33), licences: BUSINESS_LICENCES,
    common: { compat: ["Print at home on A4 or US Letter", "GoodNotes, Notability and other PDF note apps", "Any PDF reader"], requirements: ["A printer or a tablet PDF app"], howTo: ["Unzip the download", "Print the full planner, or single pages as often as you need", "On a tablet, import the PDF into your note-taking app", "Write in the dates — nothing is pre-dated"] },
    tagline: "An 84-page undated planner in A4 and US Letter — monthly, weekly, habit and goal pages — plus six single-page templates.",
    overview: ["The Undated Planner starts whenever you do. The full planner runs for twelve months with a monthly calendar, a habit tracker and four or five weekly spreads for each month, bracketed by yearly goals and notes pages. Nothing carries a date, so a missed week never wastes a page.", "Single-page templates — daily, weekly, monthly, habit tracker, yearly goals and notes — are included as separate PDFs so you can print exactly what you need. Every page comes in both A4 and US Letter and works in tablet note apps."],
    bestFor: ["People who plan on paper", "Tablet note-takers using GoodNotes or Notability", "Students and freelancers", "Anyone who abandons dated planners in March"],
    features: ["84-page full planner in A4 and US Letter", "12 undated monthly calendars with focus notes", "Weekly spreads with a top-three priorities box", "Monthly habit trackers for twelve habits", "Six single-page templates to print on demand", "Calm, printer-friendly design"],
    get: ["Full_Planner_A4.pdf and Full_Planner_Letter.pdf", "12 single-page PDFs (six templates in two sizes)", "README and licence"],
    media: [{ type: "fan", images: ["cover.png", "week.png", "day.png"] }, { type: "grid", images: ["month.png", "week.png", "day.png", "habits.png"], caption: "Monthly, weekly, daily and habit tracker pages", portrait: true }, { type: "frame", image: "week.png", caption: "Weekly spread · A4 and US Letter", portrait: true }],
    tags: ["planner", "printable", "undated", "weekly planner", "pdf"],
  },
  {
    sku: "DS-ORG-084", kind: "doc", slug: "resume-and-cover-letter-set", name: "Resume & Cover Letter Set — Three Word Designs",
    category: "resume-cv-templates", subcategory: "Resumes", prices: tiers(23), licences: BUSINESS_LICENCES, common: OFFICE_COMMON,
    tagline: "Three resume designs — Classic, Modern and Minimal — each with a matching cover letter, in Word and PDF.",
    overview: ["The Resume & Cover Letter Set gives you three designs for three kinds of employer: Classic for traditional firms, Modern with a coloured sidebar for design-led companies, and Minimal for when the content should do all the work. Each comes with a cover letter that matches it.", "All six are plain Word documents built with styles and tables rather than text boxes, so they stay tidy when you edit them and read cleanly in applicant-tracking systems. The sample resume and letter show the level of detail that gets interviews."],
    bestFor: ["Job seekers updating an old CV", "Graduates writing a first resume", "Career changers", "Recruiters and career coaches"],
    features: ["Classic, Modern and Minimal designs", "Matching cover letter for each design", "Built with Word styles and tables — no floating text boxes", "Readable by applicant-tracking systems", "Worked example content to follow", "PDF copies for quick previews"],
    get: ["3 resume DOCX files and 3 cover letter DOCX files", "PDF copies of all six", "README and licence"],
    note: "The sample person and employers are fictional.",
    media: [{ type: "fan", images: ["Resume_Classic.png", "Resume_Modern.png", "Resume_Minimal.png"] }, { type: "frame", image: "Resume_Modern.png", caption: "Modern resume · sidebar design", portrait: true }, { type: "frame", image: "Resume_Classic.png", caption: "Classic resume · serif design", portrait: true }],
    tags: ["resume template", "cv", "cover letter", "word", "job search"],
  },
)

/* ------------------------------------------------------------------ */
/* Design Resources                                                     */
/* ------------------------------------------------------------------ */

const DESIGN_LICENCES = [
  ["personal", "Use in your own non-commercial projects."],
  ["commercial", "Use in one commercial project or for one client, including products you sell where the asset is not the main thing being sold."],
  ["agency", "Use across multiple client projects and commercial work, up to the limits stated on this page."],
]
const SOCIAL_DIR = "../files/Social Media Template Pack/PNG"
const BG_DIR = "../files/Abstract Backgrounds Pack/JPG_4K"

PRODUCTS.push(
  {
    sku: "DS-ORG-085", kind: "design", slug: "colour-palette-collection-design", name: "Palette Library — 60 Colour Palettes for Designers",
    category: "design-branding", subcategory: "Colour Palettes", prices: tiers(11), licences: DESIGN_LICENCES,
    common: {
      compat: ["Adobe Photoshop, Illustrator and InDesign (ASE swatches)", "Procreate on iPad (.swatches)", "Figma, Sketch, Canva and Affinity (HEX codes from the cards or JSON)", "Websites and design-token pipelines (CSS variables and JSON)"],
      requirements: ["Nothing beyond the app you design in"],
      howTo: ["Unzip the download", "Adobe apps: open the Swatches panel → Import Swatches, and choose All_Palettes.ase or a single palette's ASE file", "Procreate: AirDrop or open a .swatches file on your iPad and it is added to your palettes", "Web: copy a block from All_Palettes.css, or read All_Palettes.json in your build"],
    },
    tagline: "Sixty five-colour palettes — each with deep, primary, accent, soft and light roles — as ASE, Procreate, CSS, JSON and swatch cards.",
    overview: ["Palette Library is a collection of sixty ready-to-use colour palettes built in the OKLCH colour space, so the five colours in each palette step evenly from a deep shade to a near-white light. Every palette assigns the same five roles — Deep, Primary, Accent, Soft and Light — which makes it easy to swap one palette for another in a layout without re-deciding which colour goes where.", "The palettes cover six colour schemes, ten of each: analogous, complementary, triadic, split-complementary, monochrome and earth tones. Each one comes in every format a designer is likely to need, from Adobe swatch files to CSS custom properties."],
    bestFor: ["Brand and identity exploration", "UI themes and design systems", "Illustration and Procreate artwork", "Presentations, social posts and marketing"],
    features: ["60 palettes of five colours each", "Consistent Deep, Primary, Accent, Soft and Light roles", "Ten palettes in each of six schemes", "Built in OKLCH for even lightness steps", "ASE, Procreate .swatches, CSS and JSON", "A swatch card PNG with HEX and RGB for every palette"],
    get: ["All_Palettes.ase plus 60 single-palette ASE files", "60 Procreate .swatches files", "All_Palettes.css and All_Palettes.json", "60 swatch card PNGs (1200 × 750)", "README and licence"],
    note: "Colours are specified in sRGB. Check contrast for text against your own accessibility requirements.",
    media: [{ type: "fan", images: ["wall.png", "detail.png", "card.png"], wide: true }, { type: "full", image: "wall.png", caption: "24 of the 60 palettes", bg: "#f1ede6", fit: "contain" }, { type: "full", image: "card.png", caption: "Swatch card · HEX, RGB and role for each colour", fit: "contain", bg: "#fff" }],
    tags: ["colour palettes", "swatches", "procreate", "ase", "design"],
  },
  {
    sku: "DS-ORG-086", kind: "design", slug: "brand-identity-system-guidelines-template", name: "Brand Identity System — Brand Guidelines Template with Example Brand",
    category: "design-branding", subcategory: "Brand Guidelines", prices: tiers(170), licences: DESIGN_LICENCES,
    common: {
      compat: ["Any PDF reader for the guidelines and stationery", "Illustrator, Figma, Affinity Designer and Inkscape (SVG logos)", "Photoshop, Illustrator and InDesign (ASE colours)", "Chrome or Edge to print the editable guidelines to PDF", "Gmail, Outlook and Apple Mail (email signature)"],
      requirements: ["A code or text editor to edit the guidelines source", "Chrome or Edge to export the PDF"],
      howTo: ["Unzip the download and read Tidewell_Brand_Guidelines.pdf to see the finished system", "Open Editable_Source/Tidewell_Brand_Guidelines.html in a code editor", "Find and replace the brand name and the five colour codes listed at the top of the file, then edit the page text", "Open the file in Chrome or Edge → Print → Save as PDF with background graphics on", "Swap the logo SVGs, tokens and ASE file for your own using the same file names"],
    },
    tagline: "A 14-page brand guidelines system shown through a complete example brand — logos, colour, type, social, stationery and an editable source.",
    overview: ["The Brand Identity System shows what a finished, usable brand guide looks like and gives you the parts to make your own. It is demonstrated through Tidewell, a fictional wellness brand, across fourteen landscape pages: story, logo, clear space and minimum size, misuse, colour, typography, graphic elements, photography direction, layout grid, social media, stationery and email signature.", "Behind the PDF are the working files: logo lockups and marks in SVG and transparent PNG, colour tokens as CSS, JSON and ASE, a print-ready business card with bleed, an A4 letterhead and an HTML email signature. The guidelines themselves ship as an editable HTML source that rebrands with a find-and-replace and prints straight to PDF."],
    bestFor: ["Studios delivering brand guidelines to clients", "Founders documenting a new brand", "Designers who need a guideline structure to follow", "Marketing teams keeping a brand consistent"],
    features: ["14-page landscape brand guidelines PDF", "Editable HTML source that rebrands with find-and-replace", "7 logo files in SVG and transparent PNG: primary, reversed, mono black and white, marks and favicon", "Colour tokens as CSS variables, JSON and an ASE swatch file", "Print-ready 85 × 55 mm business card with 3 mm bleed and an A4 letterhead", "HTML email signature"],
    get: ["Tidewell_Brand_Guidelines.pdf (14 pages)", "Editable_Source/Tidewell_Brand_Guidelines.html", "Logos in SVG and PNG (7 each)", "Colour tokens: tokens.css, tokens.json and Tidewell.ase", "Business card and letterhead PDFs", "Email_Signature.html, README and licence"],
    note: "Tidewell is a fictional example brand. There is no InDesign or Figma file: the guidelines are edited as HTML and exported to PDF from a browser.",
    media: [{ type: "fan", images: ["cover.png", "logo.png", "colour.png"], wide: true }, { type: "grid", images: ["logo.png", "colour.png", "type.png", "social.png"], caption: "Four of the fourteen guideline pages", wide: true }, { type: "full", image: "stationery.png", caption: "Stationery page · print-ready card and letterhead PDFs included", fit: "contain", bg: "#f6f4ef" }],
    tags: ["brand guidelines", "brand identity", "style guide", "logo", "template"],
  },
  {
    sku: "DS-ORG-087", kind: "design", slug: "abstract-backgrounds-pack-graphics", name: "Abstract Backgrounds — 80 4K Backgrounds in SVG and JPG",
    category: "graphics", subcategory: "Backgrounds", prices: tiers(122), licences: DESIGN_LICENCES,
    common: {
      compat: ["Any image editor, slide app or video editor (JPG)", "Illustrator, Affinity Designer, Figma and Inkscape (SVG)", "Websites and apps (SVG or JPG)", "Desktop and phone wallpapers"],
      requirements: ["Any app that opens JPG or SVG files"],
      howTo: ["Unzip the download", "Use the JPG_4K files directly in slides, videos, websites and wallpapers", "Open an SVG in a vector editor to change colours or crop to a new size without losing quality", "Export at any resolution from the SVG if you need larger than 4K"],
    },
    tagline: "Eighty abstract backgrounds in five styles — gradient mesh, topographic, geometric tiles, waves and dot fields — at 3840 × 2160.",
    overview: ["Abstract Backgrounds is a set of eighty generative backgrounds for slides, websites, video, social posts and wallpapers. Five styles cover most needs: soft gradient meshes, topographic contour lines, Bauhaus-style geometric tiles, layered waves and halftone-like dot fields, sixteen of each.", "Every background comes twice: as a high-quality 3840 × 2160 JPG ready to drop in, and as an SVG you can recolour, crop or scale to any size. Colours are drawn from coordinated palettes, so backgrounds in the same style sit well together in a deck or a campaign."],
    bestFor: ["Presentation and keynote backgrounds", "Website heroes and section backgrounds", "YouTube, stream and video backdrops", "Social posts, wallpapers and print"],
    features: ["80 backgrounds, 16 in each of five styles", "3840 × 2160 (4K UHD) JPG at quality 88", "Editable SVG for every background", "Coordinated colours from designed palettes", "Subtle film grain on gradient and wave styles", "Named by style and number for quick browsing"],
    get: ["80 JPG files at 3840 × 2160", "80 SVG files", "README and licence"],
    note: "Gradient mesh and grain effects are SVG filters. If a vector app renders them differently, use the JPG version.",
    media: [{ type: "fan", images: [`${BG_DIR}/Topographic/Topographic_03.jpg`, `${BG_DIR}/Geometric_Tiles/Geometric_Tiles_02.jpg`, `${BG_DIR}/Gradient_Mesh/Gradient_Mesh_05.jpg`], wide: true }, { type: "full", image: "overview.png", caption: "Four from each of the five styles", fit: "contain", bg: "#1a1b1f" }, { type: "full", image: "hero.png", caption: "Topographic 05 · 3840 × 2160 JPG and SVG" }],
    tags: ["backgrounds", "abstract", "4k", "wallpaper", "gradient"],
  },
  {
    sku: "DS-ORG-088", kind: "design", slug: "device-mockup-kit-design", name: "Device Mockup Kit — Browser, Laptop, Phone & Tablet Mockups",
    category: "mockups", subcategory: "Device Mockups", prices: tiers(129), licences: DESIGN_LICENCES,
    common: {
      compat: ["Any modern browser for Mockup Studio (works offline)", "Figma, Illustrator, Affinity Designer and Inkscape (SVG)", "Photoshop, Affinity Photo, GIMP, Keynote and Canva (transparent PNG frames)"],
      requirements: ["Screenshots of your website or app", "A browser, or any editor that supports layers"],
      howTo: ["Unzip the download and open Mockup_Studio.html in your browser", "Pick a mockup, add a screenshot for each screen and download a PNG at up to 3200 × 2000", "Or place a transparent PNG frame over your screenshot in any editor, using Screen_Areas.json for the screen position", "Or open an SVG and replace the linked your-screen image"],
    },
    tagline: "Twelve clean vector device mockups — browser, laptop, monitor, tablet, phone and multi-device scenes — with an offline Mockup Studio.",
    overview: ["The Device Mockup Kit presents websites and apps on flat, modern devices without a Photoshop dependency. Twelve mockups cover light and dark browser windows, a laptop in graphite and silver, a monitor, landscape and portrait tablets, two phones and three scenes, including a laptop with a phone and a trio of phones.", "Mockup Studio is a single HTML file that runs offline in any browser: choose a mockup, drop in your screenshots and download a high-resolution PNG. Every mockup is also supplied as an editable SVG and as a transparent PNG frame with its screen coordinates, so it works in whatever tool you already use."],
    bestFor: ["Portfolio and case-study images", "Product launch and landing page visuals", "App store and social media promotion", "Client presentations and pitch decks"],
    features: ["12 mockups: browser, laptop, monitor, tablet, phone and scenes", "Mockup Studio: offline, no upload, PNG export up to 3200 × 2000", "Editable SVG for every mockup", "Transparent PNG frames at 3200 × 2000", "Screen_Areas.json with exact screen positions", "Graphite and silver device finishes"],
    get: ["Mockup_Studio.html", "12 SVG mockups", "12 transparent PNG frames (3200 × 2000)", "Screen_Areas.json", "README and licence"],
    note: "Devices are flat vector illustrations, not photographs, and are not modelled on any specific brand's hardware. Screens in the previews show DistroSource Originals templates.",
    media: [{ type: "fan", images: ["Laptop_Graphite.png", "Scene_Laptop_And_Phone.png", "Phone_Graphite.png"], wide: true }, { type: "full", image: "Scene_Three_Phones.png", caption: "Three-phone scene · screens show DistroSource Originals templates", fit: "contain", bg: "#dfe8f5" }, { type: "grid", images: ["Browser_Light.png", "Monitor_Graphite.png", "Tablet_Landscape_Graphite.png", "Laptop_Silver.png", "Phone_Silver.png", "Scene_Browser_On_Gradient.png"], caption: "Browser, monitor, tablet, laptop, phone and scene mockups", wide: true }],
    tags: ["mockups", "device mockup", "laptop mockup", "phone mockup", "presentation"],
  },
  {
    sku: "DS-ORG-089", kind: "design", slug: "social-media-template-pack-design", name: "Social Media Template Pack — 60 Editable Post, Story & Thumbnail Templates",
    category: "social-media-templates", subcategory: "Posts & Stories", prices: tiers(76), licences: DESIGN_LICENCES,
    common: {
      compat: ["Figma, Illustrator, Affinity Designer and Inkscape (editable SVG)", "Photoshop and Affinity Photo (PNG, or place the SVG)", "Canva (upload the SVG or PNG as a graphic)"],
      requirements: ["The free Google Fonts listed in Fonts_to_install.txt"],
      howTo: ["Unzip the download and install the fonts listed in Fonts_to_install.txt", "Open an SVG in Figma, Illustrator, Affinity or Inkscape", "Edit the text, swap the accent colour and add your logo", "Export at the size shown in the file name folder and post"],
    },
    tagline: "Twelve social templates in five visual styles — posts, carousels, stories, a LinkedIn post and a YouTube thumbnail — as editable SVG and PNG.",
    overview: ["The Social Media Template Pack gives a small brand a month of consistent posts without starting from a blank canvas. Twelve layouts cover the jobs social media actually does — quotes, announcements, product posts, statistics, a three-slide carousel, event and promo stories, a poll story, a LinkedIn post and a YouTube thumbnail.", "Each layout comes in five styles — Bold Minimal, Editorial, Gradient Pop, Earthy and Dark Tech — so you can pick the one that fits your brand or mix them for different series. Every template is an SVG with live text plus a ready-made PNG."],
    bestFor: ["Small businesses and creators posting weekly", "Social media managers handling several brands", "Launches, events and promotions", "Coaches, consultants and LinkedIn creators"],
    features: ["12 layouts in 5 styles: 60 templates", "Square posts (1080 × 1080), carousels (1080 × 1350) and stories (1080 × 1920)", "LinkedIn post (1200 × 627) and YouTube thumbnail (1280 × 720)", "Editable SVG with live text", "PNG export of every template", "Free Google Fonts only"],
    get: ["60 SVG templates", "60 PNG templates", "Fonts_to_install.txt", "README and licence"],
    note: "Canva imports SVG files as graphics, so their text is not editable there; edit the text in Figma, Illustrator, Affinity or Inkscape.",
    media: [{ type: "fan", images: [`${SOCIAL_DIR}/Bold_Minimal/Carousel_1_Cover.png`, `${SOCIAL_DIR}/Gradient_Pop/Carousel_1_Cover.png`, `${SOCIAL_DIR}/Dark_Tech/Carousel_1_Cover.png`] }, { type: "grid", images: ["Bold_Minimal", "Editorial", "Gradient_Pop", "Earthy", "Dark_Tech"].map((s) => `${SOCIAL_DIR}/${s}/Story_Event.png`), caption: "Event story in all five styles", portrait: true, aspect: "9 / 16" }, { type: "grid", images: [["Editorial", "Post_Quote"], ["Bold_Minimal", "Post_Product"], ["Earthy", "Post_Stat"], ["Gradient_Pop", "Post_Announcement"], ["Dark_Tech", "Post_Quote"], ["Earthy", "Post_Product"]].map(([s, n]) => `${SOCIAL_DIR}/${s}/${n}.png`), caption: "Square posts · 1080 × 1080" }],
    tags: ["social media templates", "instagram", "stories", "carousel", "youtube thumbnail"],
  },
)

/* ------------------------------------------------------------------ */
/* Media — Photography presets                                          */
/* ------------------------------------------------------------------ */

const PRESET_LICENCES = [
  ["personal", "Edit your own photos and videos for non-commercial use."],
  ["commercial", "Edit photos and video for one business, including paid client work."],
  ["agency", "Use across a studio or agency's client work, for any number of clients."],
]
const PRESET_COMMON = {
  compat: ["Lightroom Classic 7.3 or later, and Lightroom desktop (presets sync to Lightroom mobile)", "Adobe Camera Raw 10.3 or later in Photoshop", "LUTs: DaVinci Resolve, Premiere Pro (Lumetri), Final Cut Pro, Photoshop (Color Lookup), Affinity Photo"],
  requirements: ["Lightroom or Camera Raw for the XMP presets", "Any editor that loads 33-point .cube LUTs"],
  howTo: ["Unzip the download", "Lightroom Classic: Develop → Presets panel → + → Import Presets, then choose the XMP files", "Photoshop: open an image in Camera Raw → Presets → Import Profiles & Presets", "Video: load a .cube file as a LUT (Resolve LUT folder, Premiere Lumetri → Creative → Look, Final Cut Custom LUT)", "Adjust exposure and white balance for each photo after applying a look"],
}
const presetNote = "The XMP presets and the LUTs are built from the same look settings but applied by different engines, so results are close rather than identical. White balance shifts in the presets apply to JPEG, HEIC and TIFF files; set white balance by eye on raw files. Previews show the LUTs applied to DistroSource 3D renders, not photographs."
const presetMedia = (look, count) => [
  { type: "fan", images: ["before-after.png", "grid-a.png", "grid-b.png"], wide: true },
  { type: "full", image: "before-after.png", caption: `${look} · LUT shown on a DistroSource 3D render`, fit: "contain" },
  { type: "full", image: "grid-b.png", caption: `All ${count} looks · shown on a DistroSource 3D render`, fit: "contain", bg: "#141518" },
]

PRODUCTS.push(
  {
    sku: "DS-ORG-090", kind: "preset", slug: "film-stock-lightroom-presets", name: "Film Stock — 12 Lightroom Presets & LUTs",
    category: "photography", subcategory: "Lightroom Presets", prices: tiers(99), licences: PRESET_LICENCES, common: PRESET_COMMON,
    tagline: "Twelve film-inspired looks — warm and cool stocks, faded, expired, slide, cross-processed and mono — as Lightroom presets and matching LUTs.",
    overview: ["Film Stock brings the colour of analogue photography to digital files: lifted blacks, gentle highlight roll-off, split-toned shadows and grain. Warm and cool everyday stocks sit alongside character looks — faded, expired, chrome slide, cross-processed — and a grainy mono stock.", "Each look ships twice: as an XMP preset for Lightroom and Camera Raw, and as a 33-point .cube LUT for video editors and Photoshop, so stills and video from the same shoot can share one look."],
    bestFor: ["Lifestyle, travel and street photographers", "Wedding and portrait edits with a film feel", "Content creators matching photos and video", "Anyone who wants analogue colour without film costs"],
    features: ["12 looks: Warm Film 100 and 400, Cool Film 200, Faded, Expired, Chrome Slide, Soft Portrait, Cinema Teal, Golden Hour, Overcast, Cross Process and Mono Film 400", "XMP presets for Lightroom and Camera Raw", "Matching 33-point .cube LUTs", "Grain and split toning built into each look", "Grouped as DistroSource Film Stock in Lightroom", "Numbered in a logical order from subtle to strong"],
    get: ["12 XMP presets", "12 .cube LUTs (33-point)", "README with install steps", "Licence"],
    note: presetNote, media: presetMedia("Warm Film 400", 12),
    tags: ["lightroom presets", "film look", "luts", "photo editing", "analogue"],
  },
  {
    sku: "DS-ORG-091", kind: "preset", slug: "moody-cinematic-lightroom-presets", name: "Moody Cinematic — 10 Lightroom Presets & LUTs",
    category: "photography", subcategory: "Lightroom Presets", prices: tiers(71), licences: PRESET_LICENCES, common: PRESET_COMMON,
    tagline: "Ten dark, cinematic grades — night city, teal and orange, deep shadows, neon dusk and colour noir — as Lightroom presets and LUTs.",
    overview: ["Moody Cinematic is a set of dramatic grades for night scenes, city streets, interiors and portraits with atmosphere. Looks deepen shadows, cool or warm the midtones and pull saturation where it distracts, borrowing the colour choices of modern film and television.", "The pack spans cool night blues, the classic teal and orange split, desaturated drama, neon magenta dusk and a warm ember grade, each as an XMP preset and a matching LUT for video."],
    bestFor: ["Night, street and urban photography", "Music, fashion and editorial shoots", "Short films, reels and music videos", "Moody interiors and portraits"],
    features: ["10 looks: Night City, Teal and Orange, Deep Shadows, Rain Street, Neon Dusk, Muted Forest, Colour Noir, Desaturated Drama, Blue Hour and Ember", "XMP presets for Lightroom and Camera Raw", "Matching 33-point .cube LUTs", "Vignettes tuned per look", "Grouped as DistroSource Moody Cinematic in Lightroom", "Works on raw and JPEG files"],
    get: ["10 XMP presets", "10 .cube LUTs (33-point)", "README with install steps", "Licence"],
    note: presetNote, media: presetMedia("Night City", 10),
    tags: ["cinematic presets", "moody", "luts", "teal and orange", "lightroom"],
  },
  {
    sku: "DS-ORG-092", kind: "preset", slug: "bright-and-airy-lightroom-presets", name: "Bright & Airy — 10 Lightroom Presets & LUTs",
    category: "photography", subcategory: "Lightroom Presets", prices: tiers(68), licences: PRESET_LICENCES, common: PRESET_COMMON,
    tagline: "Ten light, clean looks — clean white, soft pastel, morning light, creamy and cloud — as Lightroom presets and LUTs.",
    overview: ["Bright & Airy lifts exposure and shadows, softens contrast and cleans up colour casts for the light, open look used in home, food, wedding and lifestyle photography. Whites stay white rather than turning grey, and skin tones stay natural.", "Looks range from a crisp clean white to warm creamy and linen tones, pastel and blush tints and a fresh green for plants and gardens. Each comes as an XMP preset and a matching LUT."],
    bestFor: ["Interior, home and real-estate photos", "Food, product and flat-lay photography", "Weddings, newborn and family sessions", "Lifestyle bloggers and small shops"],
    features: ["10 looks: Clean White, Soft Pastel, Morning Light, Beach Day, Blush, Minimal Home, Fresh Green, Creamy, Linen and Cloud", "XMP presets for Lightroom and Camera Raw", "Matching 33-point .cube LUTs", "Highlight recovery to keep bright areas detailed", "Grouped as DistroSource Bright & Airy in Lightroom", "Works on raw and JPEG files"],
    get: ["10 XMP presets", "10 .cube LUTs (33-point)", "README with install steps", "Licence"],
    note: presetNote, media: presetMedia("Clean White", 10),
    tags: ["bright presets", "airy", "light and airy", "luts", "lightroom"],
  },
  {
    sku: "DS-ORG-093", kind: "preset", slug: "black-and-white-lightroom-presets", name: "Black & White — 8 Lightroom Presets & LUTs",
    category: "photography", subcategory: "Lightroom Presets", prices: tiers(47), licences: PRESET_LICENCES, common: PRESET_COMMON,
    tagline: "Eight monochrome looks — classic, high contrast, soft matte, silver, grain, low key, high key and selenium — as presets and LUTs.",
    overview: ["Black & White is a compact set of monochrome conversions with a clear purpose for each: a balanced classic mono, a punchy high-contrast look, a soft matte fade, a cool silver tone, a gritty grain look, dramatic low key, bright high key and a subtle selenium tone.", "Each look uses its own channel mix, so skies, skin and foliage separate into different greys, and each ships as an XMP preset for Lightroom and Camera Raw and a matching LUT for video."],
    bestFor: ["Street and documentary photography", "Portraits and headshots", "Architecture and landscape", "Black-and-white video and music videos"],
    features: ["8 looks: Classic Mono, High Contrast, Soft Matte, Silver, Punchy Grain, Low Key, High Key and Selenium Tone", "Per-look channel mix in the XMP presets", "Matching 33-point .cube LUTs", "Toned options: silver and selenium", "Grouped as DistroSource Black & White in Lightroom", "Works on raw and JPEG files"],
    get: ["8 XMP presets", "8 .cube LUTs (33-point)", "README with install steps", "Licence"],
    note: presetNote, media: presetMedia("High Contrast", 8),
    tags: ["black and white", "monochrome", "lightroom presets", "luts", "photography"],
  },
)

export { AUDIO_COMMON, FONT_COMMON }
