import type { GamingProduct } from "@/lib/gaming/catalog/types"
import { LAUNCH_DATE, LICENSE_CREATOR, card, image } from "@/lib/gaming/catalog/media"

/** Server & Community and Creator & Branding subscriptions. */

export const COMMUNITY_CREATOR_PRODUCTS: GamingProduct[] = [
  /* ------------------------------------------------------------------ */
  {
    id: "gs-community-discord-server-toolkit",
    slug: "community-discord-server-toolkit",
    title: "Discord Server Toolkit",
    platform: "community",
    category: "discord-resources",
    tags: ["Discord", "Bots", "Tickets"],
    frameworks: [],
    summary: "Self-hosted Discord bots for tickets, verification, applications and logs, configured from a web dashboard.",
    description: [
      "Discord Server Toolkit is a subscription to DistroSource's self-hosted Discord bots for game communities. It covers the jobs every server's Discord needs: support tickets with transcripts, member verification, staff applications, role menus, welcome messages and audit logs.",
      "It is for community teams who want their Discord to run smoothly without stitching together public bots with different permissions and uptime. Everything runs from one bot you host, configured through a web dashboard, with optional links to FiveM and Minecraft servers for whitelist and account checks.",
      "While subscribed you receive new modules, fixes and updates when Discord's API changes. If you cancel, updates stop and the licence to run the toolkit ends with the period you have paid for. Ticket transcripts and logs stay on your own host.",
    ],
    whatYouGet: [
      "Ticket system with categories, claiming and transcripts",
      "Member verification and role menus",
      "Staff application forms with a review workflow",
      "Welcome, leave and announcement messages",
      "Audit logs for messages, roles and moderation",
      "Web dashboard for configuration",
      "Optional FiveM and Minecraft whitelist links",
    ],
    features: [
      { title: "One bot, one dashboard", body: "Tickets, verification, applications and logs share one configuration." },
      { title: "Your host, your data", body: "Transcripts and logs never leave the server you run the bot on." },
      { title: "Linked to your game", body: "Optional whitelist and account checks for FiveM and Minecraft." },
    ],
    compatibility: ["Node.js 20 or newer", "Any VPS or container host", "SQLite or PostgreSQL storage"],
    requirements: ["A Discord server where you can add bots", "A host to run the bot"],
    license: [
      "Licensed for the communities you own or operate.",
      "You may configure and restyle the bot for those communities.",
      "Reselling, sharing or re-uploading the files is not permitted.",
      "The toolkit is licensed while your subscription is active.",
    ],
    installation: [
      "Download the toolkit from your Gaming Library.",
      "Create a bot application in the Discord developer portal and copy its token into the config.",
      "Start the bot with Docker or Node.js on your host.",
      "Open the web dashboard to choose modules, channels and roles.",
    ],
    pricing: { kind: "subscription", monthly: 58, annual: 555 },
    models: ["vault", "update-plan"],
    cadence: ["Every module from your first day", "New modules as they release", "Updates when Discord's API changes"],
    afterCancel: [
      "Access and updates continue until the end of the period you paid for.",
      "The licence to run the toolkit ends with the subscription.",
      "Transcripts and logs stay on your own host.",
    ],
    eligibleResourceTypes: ["Ticket and support bots", "Verification and roles", "Applications", "Logging and audit"],
    media: [
      image("community-discord-server-toolkit", "cover", "Community chat app with a support ticket panel and verification message from the bot", "Built interface — ticket panel"),
      image("community-discord-server-toolkit", "gallery-2", "Ticket thread with staff claim, conversation and transcript controls", "Built interface — ticket thread"),
      image("community-discord-server-toolkit", "gallery-3", "Bot web dashboard with modules, channels and role settings", "Built interface — bot dashboard"),
    ],
    cardImage: card("community-discord-server-toolkit", "Discord Server Toolkit — ticket panel preview"),
    availability: "on-sale",
    curation: 12,
    releasedAt: LAUNCH_DATE,
    updatedAt: LAUNCH_DATE,
    searchTerms: ["discord bot", "tickets", "verification", "whitelist", "applications", "logs", "roles"],
  },

  /* ------------------------------------------------------------------ */
  {
    id: "gs-community-staff-moderation-ops",
    slug: "community-staff-moderation-ops",
    title: "Staff & Moderation Ops",
    platform: "community",
    category: "moderation",
    tags: ["Moderation", "Staff", "Membership"],
    frameworks: [],
    summary: "Staff dashboard, report and appeal workflows, handbook templates and training for moderation teams.",
    description: [
      "Staff & Moderation Ops is a membership for the teams who keep game communities fair. It combines tools and process: a staff dashboard for reports and player history, warning and ban-appeal workflows, and a moderation handbook with rule templates, escalation paths and training scenarios.",
      "It is for communities where moderation has grown past a single admin and a spreadsheet. The dashboard connects to FiveM, Minecraft and Discord through documented adapters, so one record follows a player across your platforms, and every action is logged with the staff member and the reason.",
      "Members receive monthly additions — new training scenarios, template updates and dashboard features — while subscribed. If you cancel, the tools stop updating and their licence ends with the period you have paid for, while handbook documents you have adapted remain yours to use.",
    ],
    whatYouGet: [
      "Staff dashboard for reports, notes and player history",
      "Warning, kick, ban and appeal workflows with an audit trail",
      "Adapters for FiveM, Minecraft and Discord",
      "Moderation handbook with editable rule templates",
      "Escalation paths and staff role definitions",
      "Monthly training scenarios for new moderators",
    ],
    features: [
      { title: "One record per player", body: "Reports, notes and actions follow a player across your platforms." },
      { title: "Every action explained", body: "Each warning or ban records who acted and why." },
      { title: "Process, not just tools", body: "Handbook templates and training make decisions consistent." },
    ],
    compatibility: ["FiveM adapter for ESX, QBCore and Qbox", "Minecraft adapter for Paper servers", "Discord bot adapter", "Self-hosted with Docker"],
    requirements: ["A host for the staff dashboard", "Admin access to the servers you connect"],
    license: [
      "Licensed for the communities you own or operate.",
      "You may adapt the handbook and templates for those communities.",
      "Reselling, sharing or re-uploading the files is not permitted.",
    ],
    installation: [
      "Download the dashboard and handbook from your Gaming Library.",
      "Deploy the dashboard with Docker on your host.",
      "Install the adapters for your FiveM, Minecraft and Discord servers.",
      "Adapt the handbook and invite your staff.",
    ],
    pricing: { kind: "subscription", monthly: 79, annual: 755 },
    models: ["membership", "monthly-drop"],
    cadence: ["The dashboard and handbook from your first day", "Training scenarios and template updates every month", "New dashboard features as they release"],
    afterCancel: [
      "Tools remain available until the end of the period you paid for.",
      "The dashboard and adapters stop updating, and their licence ends with the subscription.",
      "Handbook documents you have adapted remain yours to use.",
    ],
    eligibleResourceTypes: ["Moderation tools", "Appeal workflows", "Rules and handbooks", "Staff training"],
    media: [
      image("community-staff-moderation-ops", "cover", "Staff dashboard with a report queue, player history and recent actions", "Built interface — staff dashboard"),
      image("community-staff-moderation-ops", "gallery-2", "Ban appeal review with the original evidence, the appeal and a decision", "Built interface — appeal review"),
      image("community-staff-moderation-ops", "gallery-3", "Moderation handbook page with an escalation path and rule template", "Design mockup — moderation handbook"),
    ],
    cardImage: card("community-staff-moderation-ops", "Staff & Moderation Ops — staff dashboard preview"),
    availability: "on-sale",
    curation: 20,
    releasedAt: LAUNCH_DATE,
    updatedAt: LAUNCH_DATE,
    searchTerms: ["moderation", "staff", "admin", "reports", "bans", "appeals", "handbook", "rules"],
  },

  /* ------------------------------------------------------------------ */
  {
    id: "gs-creator-esports-team-kit",
    slug: "creator-esports-team-kit",
    title: "Esports Team Kit",
    platform: "creator",
    category: "esports-graphics",
    tags: ["Esports", "Match graphics", "Team"],
    frameworks: [],
    summary: "Match-day posters, roster cards, scoreboards and stream graphics for esports teams, with new sets every month.",
    description: [
      "Esports Team Kit is a creator plan for competitive teams and tournament organisers. It provides the graphics a season needs: match-day and result posters, roster and player cards, scoreboards and lower thirds for streams, and social templates for signings and schedules.",
      "It is for teams that post every match and want each one to look like the same organisation. Everything is built around your logo, colours and player photos through named layers and styles, and match details — opponent, time, score — are text fields, so a post takes minutes rather than an evening.",
      "Two new template sets arrive every month, and every set released while you are subscribed is yours to keep. The plan is licensed for one team or organisation, including its roster and staff.",
    ],
    whatYouGet: [
      "Match-day, result and schedule posters",
      "Roster and player cards",
      "Stream scoreboards, lower thirds and caster frames",
      "Social templates for signings and announcements",
      "Two new template sets every month",
      "Layered PSD and Figma files with editable text fields",
      "Sets released while subscribed, kept permanently",
    ],
    features: [
      { title: "One organisation, every post", body: "Posters, cards and stream graphics share one visual system." },
      { title: "Minutes per match", body: "Opponent, time and score are text fields, not redesigns." },
      { title: "Keep every set", body: "Sets released while you are subscribed stay yours." },
    ],
    compatibility: ["Adobe Photoshop (PSD)", "Figma", "OBS Studio and Streamlabs for stream graphics"],
    requirements: ["An editor for PSD or Figma files"],
    license: [...LICENSE_CREATOR, "Licensed for one team or organisation, including its roster and staff.", "Sets released during your paid months stay licensed to you after you cancel."],
    installation: [
      "Download the month's sets from your Gaming Library.",
      "Open the files in Photoshop or Figma and apply your logo and colours.",
      "Fill in the match details and player photos.",
      "Export for social posts or add the stream graphics to your scenes.",
    ],
    pricing: { kind: "subscription", monthly: 91, annual: 870 },
    models: ["creator", "monthly-drop"],
    cadence: ["Two new template sets every month", "Back catalogue available while subscribed"],
    afterCancel: [
      "Sets released during your paid months stay yours permanently.",
      "Back-catalogue access ends with the subscription.",
      "No new sets after the paid period ends.",
    ],
    eligibleResourceTypes: ["Match graphics", "Roster cards", "Stream graphics", "Social templates"],
    media: [
      image("creator-esports-team-kit", "cover", "Match-day poster for a fictional team with logo, opponent and start time", "Design mockup — match-day poster"),
      image("creator-esports-team-kit", "gallery-2", "Roster cards for five players with roles and numbers", "Design mockup — roster cards"),
      image("creator-esports-team-kit", "gallery-3", "Stream scoreboard and lower third over gameplay", "Design mockup — stream scoreboard"),
    ],
    cardImage: card("creator-esports-team-kit", "Esports Team Kit — match-day poster preview"),
    availability: "on-sale",
    curation: 16,
    releasedAt: LAUNCH_DATE,
    updatedAt: LAUNCH_DATE,
    searchTerms: ["esports", "team", "roster", "match", "tournament", "scoreboard", "poster", "graphics"],
  },

  /* ------------------------------------------------------------------ */
  {
    id: "gs-creator-thumbnail-studio",
    slug: "creator-thumbnail-studio",
    title: "Thumbnail Studio",
    platform: "creator",
    category: "thumbnails",
    tags: ["Thumbnails", "Templates", "Creator"],
    frameworks: [],
    summary: "Editable video thumbnail templates for gaming creators, with a new pack every month.",
    description: [
      "Thumbnail Studio is a creator plan for people who publish gaming videos. Each month it delivers a pack of editable thumbnail templates built for roleplay, survival, building and competitive content, with bold title treatments, cut-out frames for gameplay and face shots, and consistent series styling.",
      "It is for creators who want thumbnails that read at small sizes and stay recognisable across a series. Templates are designed at 1280×720 and checked at feed size, with contrast-tested text styles and named layers for your capture, title and episode number. Packs include a series system — matching episode, short and live-stream variants — so a whole playlist looks planned.",
      "Every pack released while you are subscribed is yours to keep and use on your channels after you cancel. Back-catalogue packs are available while your subscription is active.",
    ],
    whatYouGet: [
      "A new thumbnail template pack every month",
      "Templates for roleplay, survival, building and competitive videos",
      "Series variants for episodes, shorts and live streams",
      "Contrast-tested title styles readable at feed size",
      "Layered PSD and Figma files with named layers",
      "Packs released while subscribed, kept permanently",
    ],
    features: [
      { title: "Readable when small", body: "Every template is checked at feed size, not only full size." },
      { title: "A series look", body: "Episode, short and live variants keep a playlist consistent." },
      { title: "Keep every pack", body: "Packs released while you are subscribed stay yours." },
    ],
    compatibility: ["Adobe Photoshop (PSD)", "Figma", "Photopea"],
    requirements: ["An editor for PSD or Figma files"],
    license: [...LICENSE_CREATOR, "Packs released during your paid months stay licensed to you after you cancel."],
    installation: [
      "Download the month's pack from your Gaming Library.",
      "Open a template and drop your capture into the named frame.",
      "Edit the title and episode layers.",
      "Export at 1280×720 and upload with your video.",
    ],
    pricing: { kind: "subscription", monthly: 21, annual: 200 },
    models: ["creator", "monthly-drop"],
    cadence: ["One template pack every month", "Back catalogue available while subscribed"],
    afterCancel: [
      "Packs released during your paid months stay yours permanently.",
      "Back-catalogue access ends with the subscription.",
      "No new packs after the paid period ends.",
    ],
    eligibleResourceTypes: ["Video thumbnails", "Series templates", "Title treatments"],
    media: [
      image("creator-thumbnail-studio", "cover", "Grid of gaming video thumbnails from one monthly pack", "Design mockup — thumbnail pack"),
      image("creator-thumbnail-studio", "gallery-2", "Thumbnail template open in an editor with named layers", "Design mockup — thumbnail layers"),
      image("creator-thumbnail-studio", "gallery-3", "Episode, short and live-stream variants of one series", "Design mockup — series set"),
    ],
    cardImage: card("creator-thumbnail-studio", "Thumbnail Studio — thumbnail pack preview"),
    availability: "on-sale",
    curation: 23,
    releasedAt: LAUNCH_DATE,
    updatedAt: LAUNCH_DATE,
    searchTerms: ["thumbnail", "thumbnails", "youtube", "video", "templates", "creator"],
  },
]
