import type { GamingFramework, GamingProduct } from "@/lib/gaming/catalog/types"
import { AFTER_CANCEL_LICENSED, LAUNCH_DATE, LICENSE_CREATOR, LICENSE_SERVER, card, image } from "@/lib/gaming/catalog/media"

/** FiveM subscriptions, products 7–26 of the catalogue (with Minecraft, community and creator). */

const FRAMEWORKS: GamingFramework[] = ["esx", "qbcore", "qbox"]
const SCRIPT_COMPAT = ["ESX Legacy", "QBCore", "Qbox", "oxmysql"]
const SCRIPT_REQUIRES = ["A FiveM server running ESX, QBCore or Qbox", "oxmysql"]
const scriptInstall = (what: string) => [
  `Download ${what} from your Gaming Library.`,
  "Place the resources in your server's resources directory.",
  "Set your framework and options in the bundled config.",
  "Add the `ensure` lines to server.cfg after your framework and oxmysql, then restart.",
]

export const FIVEM_PRODUCTS: GamingProduct[] = [
  /* ------------------------------------------------------------------ */
  {
    id: "gs-fivem-city-starter-server",
    slug: "fivem-city-starter-server",
    title: "City Starter Server",
    platform: "fivem",
    category: "server-packages",
    tags: ["Server package", "Full city", "Monthly update"],
    frameworks: ["qbcore", "qbox"],
    summary: "A complete, configured FiveM roleplay city — core systems, jobs, interfaces, interiors and vehicles — updated every month.",
    description: [
      "City Starter Server is a complete FiveM roleplay server delivered as a subscription. Instead of assembling a city from dozens of resources and hoping they cooperate, you get one tested package: the framework setup, core systems, jobs, interfaces, interiors and vehicles, pre-configured to work together.",
      "It is for new communities that want to open in days rather than months, and for owners rebuilding an existing city on a clean foundation. The package ships as a deployable recipe with a database schema, a staging checklist and documented settings for the economy, jobs and permissions, so your team starts from a working city and customises from there. Resources from the MLO Vault, Interface Series, Fleet Garage and Server Owner Plan are set up inside it.",
      "Every month the package receives a tested update — new resources, framework upgrades and fixes — released with a changelog you apply on staging first. If you cancel, updates stop and the licence to run the package ends with the period you have paid for. Your database and player data remain yours.",
    ],
    whatYouGet: [
      "A deployable server recipe with core resources and database schema",
      "Pre-configured jobs, economy, housing and inventory systems",
      "MLO Vault, Interface Series and Fleet Garage resources placed in the city",
      "Server Owner Plan tools, presets and staff checklists",
      "A tested package update every month, with changelog and staging notes",
      "QBCore and Qbox editions",
      "Documented permissions, settings and customisation points",
    ],
    features: [
      { title: "Tested as one city", body: "Every resource in the package is configured and tested against the others before a release." },
      { title: "Staging first", body: "Each monthly update ships with a changelog and a checklist for your staging server." },
      { title: "Yours to shape", body: "Branding, economy and job settings are documented so the city becomes your own." },
    ],
    compatibility: ["QBCore or Qbox edition", "oxmysql with MariaDB 10.6+ or MySQL 8", "txAdmin recipe deployment", "Current recommended FiveM server artifacts"],
    requirements: ["A FiveM server licence key", "A MariaDB or MySQL database", "A host with at least 8 GB RAM for a populated city"],
    license: [...LICENSE_SERVER, "The package is licensed while your subscription is active."],
    installation: [
      "Download the package recipe for your edition from your Gaming Library.",
      "Create the database and import the bundled schema.",
      "Deploy the recipe with txAdmin on a staging server and follow the checklist.",
      "Apply your branding and economy settings, then promote to live.",
    ],
    pricing: { kind: "subscription", monthly: 149, annual: 1430 },
    models: ["server-owner", "update-plan", "vault"],
    cadence: ["The complete package from your first day", "One tested package update every month", "Framework upgrades validated before release"],
    afterCancel: [
      "Access and updates continue until the end of the period you paid for.",
      "The licence to run the package ends with the subscription.",
      "Your server's database and player data remain yours.",
    ],
    eligibleResourceTypes: ["Core systems", "Jobs and economy", "Interfaces and HUDs", "Interiors and maps", "Vehicles", "Server administration tools"],
    media: [
      image("fivem-city-starter-server", "cover", "Server package overview listing the included systems, jobs, interfaces and interiors", "Built interface — package overview"),
      image("fivem-city-starter-server", "gallery-2", "Setup wizard with database, framework and branding steps", "Built interface — setup wizard"),
      image("fivem-city-starter-server", "gallery-3", "Monthly update changelog with staging checklist", "Built interface — monthly update"),
    ],
    cardImage: card("fivem-city-starter-server", "City Starter Server — package overview preview"),
    availability: "launching",
    curation: 7,
    releasedAt: LAUNCH_DATE,
    updatedAt: LAUNCH_DATE,
    searchTerms: ["full server", "server pack", "starter", "qbcore server", "qbox server", "txadmin", "recipe", "city"],
  },

  /* ------------------------------------------------------------------ */
  {
    id: "gs-fivem-heist-series",
    slug: "fivem-heist-series",
    title: "Heist Series",
    platform: "fivem",
    category: "crime-heists",
    tags: ["Heists", "Interiors", "Minigames"],
    frameworks: FRAMEWORKS,
    summary: "Heist scripts, vault interiors and hacking minigames for FiveM, with a new heist released every month.",
    description: [
      "Heist Series is a subscription to DistroSource's crime content for FiveM: complete heists that combine a scripted robbery, a purpose-built interior and the minigames between them. Each heist is a set piece your criminals can plan around and your police can respond to.",
      "It is designed for roleplay servers that want organised crime to feel earned rather than farmed. Every heist has configurable police requirements, cooldowns, loot tables and item gates, so it slots into your economy instead of flooding it, and it raises alerts through common MDT and dispatch resources.",
      "A new heist is released every month and the full back catalogue stays available while you are subscribed, along with balance passes and framework updates. If you cancel, access ends with the period you have paid for, and series heists should be removed from your live server.",
    ],
    whatYouGet: [
      "Every released heist: scripted robbery, interior and minigames",
      "One new heist every month",
      "Vault, safe and security-room interiors",
      "Hacking, drilling and lockpick minigames with adjustable difficulty",
      "Police requirements, cooldowns and loot tables in one config",
      "Dispatch alerts for common MDT and dispatch resources",
      "Balance passes and framework updates while subscribed",
    ],
    features: [
      { title: "Earned, not farmed", body: "Police minimums, cooldowns and item gates keep heists rare and meaningful." },
      { title: "Built as set pieces", body: "Each interior is designed around its heist, not reused from a map pack." },
      { title: "Readable minigames", body: "Clear, skill-based minigames with difficulty you tune per heist." },
    ],
    compatibility: [...SCRIPT_COMPAT, "ox_inventory or your framework's inventory"],
    requirements: [...SCRIPT_REQUIRES, "An inventory resource for heist items"],
    license: [...LICENSE_SERVER, "Series heists are licensed while your subscription is active."],
    installation: scriptInstall("the heists you want"),
    pricing: { kind: "subscription", monthly: 137, annual: 1315 },
    models: ["vault", "monthly-drop"],
    cadence: ["One new heist released every month", "Balance passes on existing heists", "Framework compatibility updates"],
    afterCancel: AFTER_CANCEL_LICENSED("series heists"),
    eligibleResourceTypes: ["Bank and vault heists", "Store and jewellery robberies", "Security-room and hacking set pieces", "Heist interiors", "Crime minigames"],
    media: [
      image("fivem-heist-series", "cover", "Bank vault interior with a round vault door, deposit boxes and security lighting", "Rendered preview — vault interior"),
      image("fivem-heist-series", "gallery-2", "Heist planning board with crew roles, entry points and a timeline", "Built interface — planning board"),
      image("fivem-heist-series", "gallery-3", "Hacking minigame with a node grid and countdown", "Built interface — hacking minigame"),
    ],
    cardImage: card("fivem-heist-series", "Heist Series — vault interior preview"),
    availability: "launching",
    curation: 8,
    releasedAt: LAUNCH_DATE,
    updatedAt: LAUNCH_DATE,
    searchTerms: ["robbery", "bank", "vault", "hack", "hacking", "drill", "crime", "jewellery", "fleeca"],
  },

  /* ------------------------------------------------------------------ */
  {
    id: "gs-fivem-phone-os",
    slug: "fivem-phone-os",
    title: "Phone OS",
    platform: "fivem",
    category: "phone",
    tags: ["Phone", "Apps", "Update plan"],
    frameworks: FRAMEWORKS,
    summary: "A complete in-game smartphone with messages, calls, banking, garage and social apps, maintained monthly.",
    description: [
      "Phone OS is DistroSource's in-game smartphone for FiveM, delivered as a maintained subscription. It gives players one device for messages, calls, contacts, photos, banking, their garage and a city social feed, with a home screen, lock screen and notifications that behave like a real phone.",
      "It is for servers whose roleplay runs through players' pockets. Apps talk to your framework's money, vehicles and jobs through bridges for ESX, QBCore and Qbox, and a documented app API lets your developers add their own apps with the same look and behaviour.",
      "While subscribed you receive new apps as they release, monthly fixes and compatibility updates when frameworks or FiveM change. If you cancel, updates stop and the licence to run Phone OS ends with the period you have paid for.",
    ],
    whatYouGet: [
      "Home screen, lock screen, notifications and settings",
      "Messages, calls, contacts and group chats",
      "Banking, garage and job apps wired to your framework",
      "Camera, gallery and a city social feed",
      "Developer API for your own apps",
      "Light and dark themes with your server's wallpaper and colours",
      "New apps and compatibility updates while subscribed",
    ],
    features: [
      { title: "Feels like a phone", body: "Gestures, notifications and app switching behave the way players expect." },
      { title: "Your apps, same look", body: "The app API gives custom apps the system's layout, type and motion." },
      { title: "Wired to your city", body: "Banking, garage and job apps read your framework's real data." },
    ],
    compatibility: [...SCRIPT_COMPAT, "pma-voice for voice calls"],
    requirements: [...SCRIPT_REQUIRES, "pma-voice for voice calls"],
    license: [...LICENSE_SERVER, "Phone OS is licensed while your subscription is active."],
    installation: scriptInstall("Phone OS"),
    pricing: { kind: "subscription", monthly: 59, annual: 565 },
    models: ["update-plan", "vault"],
    cadence: ["The full phone and every released app from day one", "New apps as they release", "Monthly fixes and framework updates"],
    afterCancel: AFTER_CANCEL_LICENSED("Phone OS"),
    eligibleResourceTypes: ["Communication apps", "Banking and finance apps", "Vehicle and garage apps", "Social and media apps", "Job and business apps"],
    media: [
      image("fivem-phone-os", "cover", "In-game smartphone home screen with app icons and notifications over a city street", "Built interface — home screen"),
      image("fivem-phone-os", "gallery-2", "Messages conversation and banking app side by side", "Built interface — messages and banking"),
      image("fivem-phone-os", "gallery-3", "Garage app and city social feed side by side", "Built interface — garage and social"),
    ],
    cardImage: card("fivem-phone-os", "Phone OS — home screen preview"),
    availability: "launching",
    curation: 9,
    releasedAt: LAUNCH_DATE,
    updatedAt: LAUNCH_DATE,
    searchTerms: ["phone", "smartphone", "messages", "twitter", "social", "gallery", "calls", "npwd"],
  },

  /* ------------------------------------------------------------------ */
  {
    id: "gs-fivem-housing-collection",
    slug: "fivem-housing-collection",
    title: "Housing Collection",
    platform: "fivem",
    category: "housing",
    tags: ["Housing", "Interiors", "Pick & keep"],
    frameworks: FRAMEWORKS,
    summary: "A property system plus apartments and houses to furnish. Claim two new residences a month and keep them.",
    description: [
      "Housing Collection is a residential subscription for FiveM: a property system for buying, renting and furnishing homes, together with a growing collection of apartment and house interiors built for it. Players browse listings, receive keys and decorate with a placement tool that respects walls and floors.",
      "It suits servers where owning a place is part of a character's story. The property system handles ownership, rent, shared keys, storage and wardrobes across ESX, QBCore and Qbox, and every residence ships with entry points, storage spots and furniture limits already configured.",
      "Each month two new residences are released for you to claim and keep permanently, alongside a furniture drop for the placement catalogue. The property system and its updates are included while you are subscribed. Claimed residences stay licensed to you after you cancel; the property system's licence ends with the paid period.",
    ],
    whatYouGet: [
      "Property system: buying, renting, shared keys, storage and wardrobes",
      "Furniture placement tool with a searchable catalogue",
      "Two residence claims each month, kept permanently",
      "Apartment, house and penthouse interiors with entry points configured",
      "A furniture drop for the catalogue every month",
      "Property listings app for players and estate agents",
      "ESX, QBCore and Qbox bridges",
    ],
    features: [
      { title: "Homes worth decorating", body: "Placement snaps to floors and walls and respects per-property furniture limits." },
      { title: "Ready to move in", body: "Entry, storage and wardrobe points are configured in every residence." },
      { title: "Residences you keep", body: "Claimed interiors stay licensed to you after you cancel." },
    ],
    compatibility: [...SCRIPT_COMPAT, "Standalone interiors with no framework dependency"],
    requirements: [...SCRIPT_REQUIRES, "Space in your resources folder for streamed interiors"],
    license: [...LICENSE_SERVER, "Claimed residences stay licensed to you after you cancel."],
    installation: [
      "Claim your residences for the month in your Gaming Library.",
      "Download the property system and the interiors you claimed.",
      "Set your framework, rent and furniture limits in the config.",
      "Add the `ensure` lines to server.cfg and restart.",
    ],
    pricing: { kind: "subscription", monthly: 128, annual: 1225 },
    models: ["pick-and-keep", "monthly-drop", "update-plan"],
    cadence: ["Two residence claims per billing month", "A furniture drop every month", "Unused claims do not roll over"],
    afterCancel: [
      "Residences you claimed stay licensed to you permanently.",
      "The property system and furniture catalogue stop updating, and their licence ends with the paid period.",
      "No new claims after the paid period ends.",
    ],
    eligibleResourceTypes: ["Apartments and flats", "Houses and penthouses", "Furniture and decor props", "Property and estate systems"],
    media: [
      image("fivem-housing-collection", "cover", "Furnished apartment living room with a sofa, rug, kitchen island and city view", "Rendered preview — apartment interior"),
      image("fivem-housing-collection", "gallery-2", "Furniture placement tool with a catalogue panel over the apartment", "Built interface — furniture placement"),
      image("fivem-housing-collection", "gallery-3", "Property listings app with apartments, prices and key holders", "Built interface — property listings"),
    ],
    cardImage: card("fivem-housing-collection", "Housing Collection — apartment preview"),
    availability: "launching",
    curation: 11,
    releasedAt: LAUNCH_DATE,
    updatedAt: LAUNCH_DATE,
    searchTerms: ["house", "houses", "apartment", "property", "real estate", "furniture", "decorate", "motel"],
  },

  /* ------------------------------------------------------------------ */
  {
    id: "gs-fivem-emergency-services-suite",
    slug: "fivem-emergency-services-suite",
    title: "Emergency Services Suite",
    platform: "fivem",
    category: "police-emergency",
    tags: ["Police", "EMS", "Fire"],
    frameworks: FRAMEWORKS,
    summary: "Police, EMS and fire job systems — treatment, evidence, booking and duty rosters — maintained and extended monthly.",
    description: [
      "Emergency Services Suite is a subscription to DistroSource's job systems for the people who keep a roleplay city safe: police, EMS and fire. It covers the work between the calls — treating injuries, logging evidence, booking and jailing suspects, impounding vehicles and running duty rosters.",
      "It is built for servers with active emergency departments that have outgrown basic job scripts. Each system uses shared ranks, grades and duty status across ESX, QBCore and Qbox, and pairs with the Interface Series MDT and dispatch without requiring them.",
      "While subscribed you get every system in the suite, new modules as they release, and updates when frameworks change. Department configs for ranks, pay and equipment are included. If you cancel, updates stop and the licence to run suite systems ends with the period you have paid for.",
    ],
    whatYouGet: [
      "EMS treatment with injury states, triage and hospital beds",
      "Police booking, jail, evidence lockers and impound",
      "Fire and rescue job with call-outs and equipment",
      "Duty rosters, ranks and grade-based permissions",
      "Department configs for pay, equipment and vehicles",
      "Optional hooks for the Interface Series MDT and dispatch",
      "New modules and framework updates while subscribed",
    ],
    features: [
      { title: "The work between calls", body: "Treatment, evidence and booking give responders something to do after they arrive." },
      { title: "One department model", body: "Ranks, grades and duty status are shared by police, EMS and fire." },
      { title: "Plays well with MDTs", body: "Hooks for the Interface Series, documented exports for anything else." },
    ],
    compatibility: SCRIPT_COMPAT,
    requirements: SCRIPT_REQUIRES,
    license: [...LICENSE_SERVER, "Suite systems are licensed while your subscription is active."],
    installation: scriptInstall("the suite"),
    pricing: { kind: "subscription", monthly: 142, annual: 1360 },
    models: ["vault", "update-plan"],
    cadence: ["Every system in the suite from your first day", "New modules as they release", "Updates when ESX, QBCore, Qbox or FiveM change"],
    afterCancel: AFTER_CANCEL_LICENSED("suite systems"),
    eligibleResourceTypes: ["Police job systems", "EMS and medical systems", "Fire and rescue systems", "Justice, jail and impound", "Department management"],
    media: [
      image("fivem-emergency-services-suite", "cover", "EMS treatment interface with a body chart, injuries and treatment steps", "Built interface — EMS treatment"),
      image("fivem-emergency-services-suite", "gallery-2", "Police evidence locker with logged items, chain of custody and case links", "Built interface — evidence locker"),
      image("fivem-emergency-services-suite", "gallery-3", "Department duty roster with ranks, units and on-duty status", "Built interface — duty roster"),
    ],
    cardImage: card("fivem-emergency-services-suite", "Emergency Services Suite — EMS treatment preview"),
    availability: "launching",
    curation: 13,
    releasedAt: LAUNCH_DATE,
    updatedAt: LAUNCH_DATE,
    searchTerms: ["police job", "ems job", "ambulance", "medic", "fire", "jail", "evidence", "impound", "lspd", "sheriff"],
  },

  /* ------------------------------------------------------------------ */
  {
    id: "gs-fivem-business-systems",
    slug: "fivem-business-systems",
    title: "Business Systems",
    platform: "fivem",
    category: "businesses",
    tags: ["Businesses", "Staff", "Monthly drop"],
    frameworks: FRAMEWORKS,
    summary: "Player-run businesses with stock, staff, tills and supplier deliveries, plus a new business type every month.",
    description: [
      "Business Systems is a subscription that turns storefronts into businesses players actually run. Owners hire staff, set wages, order stock from suppliers, price their menu and take payments at the till, while employees clock in, prepare orders and hand them over.",
      "It is for servers that want a civilian economy with more depth than grinding jobs. Every business type shares one management system across ESX, QBCore and Qbox, so a diner, a mechanic and a nightclub all report sales, stock and payroll in the same dashboard.",
      "A new business type is added each month — with its recipes, props and till layout — and every released type stays available while you are subscribed. If you cancel, updates stop and the licence to run business systems ends with the period you have paid for.",
    ],
    whatYouGet: [
      "Business dashboard for sales, stock, staff and payroll",
      "Till and point-of-sale interface with receipts",
      "Supplier orders and delivery runs for stock",
      "Staff hiring, grades, wages and clock-in",
      "Every released business type with recipes and props",
      "A new business type every month",
      "ESX, QBCore and Qbox bridges",
    ],
    features: [
      { title: "Owners make decisions", body: "Prices, wages and stock levels are set by players, not a config file." },
      { title: "Staff have a job", body: "Clock in, prepare orders and serve customers through one consistent flow." },
      { title: "One dashboard", body: "Every business type reports into the same management view." },
    ],
    compatibility: SCRIPT_COMPAT,
    requirements: SCRIPT_REQUIRES,
    license: [...LICENSE_SERVER, "Business systems are licensed while your subscription is active."],
    installation: scriptInstall("the business systems"),
    pricing: { kind: "subscription", monthly: 118, annual: 1130 },
    models: ["vault", "monthly-drop"],
    cadence: ["Every released business type from your first day", "One new business type every month", "Updates when frameworks change"],
    afterCancel: AFTER_CANCEL_LICENSED("business systems"),
    eligibleResourceTypes: ["Restaurants and cafés", "Bars and nightclubs", "Mechanic and tuning shops", "Retail stores", "Supply and delivery businesses"],
    media: [
      image("fivem-business-systems", "cover", "Business management dashboard with sales, stock levels and staff on shift", "Built interface — business dashboard"),
      image("fivem-business-systems", "gallery-2", "Till interface with a menu grid, current order and payment", "Built interface — till"),
      image("fivem-business-systems", "gallery-3", "Supplier order screen with stock levels and a delivery run", "Built interface — supplier orders"),
    ],
    cardImage: card("fivem-business-systems", "Business Systems — dashboard preview"),
    availability: "launching",
    curation: 15,
    releasedAt: LAUNCH_DATE,
    updatedAt: LAUNCH_DATE,
    searchTerms: ["business", "restaurant", "burger", "cafe", "nightclub", "shop", "cash register", "pos", "stock"],
  },

  /* ------------------------------------------------------------------ */
  {
    id: "gs-fivem-job-center",
    slug: "fivem-job-center",
    title: "Job Center",
    platform: "fivem",
    category: "jobs",
    tags: ["Jobs", "Routes", "Monthly drop"],
    frameworks: FRAMEWORKS,
    summary: "Civilian jobs with routes, vehicles and payouts — trucking, delivery, sanitation and more — with new jobs every month.",
    description: [
      "Job Center is a subscription to DistroSource's civilian jobs for FiveM. Players sign on at a job centre, choose a role and work routes with the right vehicle, equipment and pay — hauling freight, delivering parcels, collecting refuse, driving buses or clearing tow calls.",
      "It is meant for servers that want legal work to be worth doing and pleasant to repeat. Every job shares one job-centre interface, route editor and payout config across ESX, QBCore and Qbox, with progression that unlocks better routes and vehicles as players level up.",
      "New jobs are published every month and every released job stays available while you are subscribed, along with route packs and balance updates. If you cancel, updates stop and the licence to run the jobs ends with the period you have paid for.",
    ],
    whatYouGet: [
      "Job-centre interface for signing on and choosing work",
      "Trucking, delivery, sanitation, bus and tow jobs",
      "Route editor for placing stops and depots",
      "Progression that unlocks routes, vehicles and pay",
      "One payout config shared by every job",
      "New jobs and route packs every month",
      "ESX, QBCore and Qbox bridges",
    ],
    features: [
      { title: "Work worth doing", body: "Progression and fair pay make legal jobs a real choice." },
      { title: "Your city's routes", body: "Place stops and depots in-game with the route editor." },
      { title: "One economy lever", body: "Every job's pay lives in one config, so balancing is quick." },
    ],
    compatibility: SCRIPT_COMPAT,
    requirements: SCRIPT_REQUIRES,
    license: [...LICENSE_SERVER, "Jobs are licensed while your subscription is active."],
    installation: scriptInstall("the jobs you want"),
    pricing: { kind: "subscription", monthly: 65, annual: 620 },
    models: ["monthly-drop", "vault"],
    cadence: ["New jobs published every month", "Route packs for existing jobs", "Balance and framework updates"],
    afterCancel: AFTER_CANCEL_LICENSED("the jobs"),
    eligibleResourceTypes: ["Logistics and delivery jobs", "Public-service jobs", "Transport jobs", "Recovery and towing jobs", "Route packs"],
    media: [
      image("fivem-job-center", "cover", "Job centre tablet listing civilian jobs with pay, level and vehicles", "Built interface — job centre"),
      image("fivem-job-center", "gallery-2", "Delivery route HUD with the next stop, cargo and route map", "Built interface — route HUD"),
      image("fivem-job-center", "gallery-3", "Shift summary with deliveries, earnings and progression", "Built interface — shift summary"),
    ],
    cardImage: card("fivem-job-center", "Job Center — job centre preview"),
    availability: "launching",
    curation: 17,
    releasedAt: LAUNCH_DATE,
    updatedAt: LAUNCH_DATE,
    searchTerms: ["jobs", "trucker", "trucking", "delivery", "garbage", "bus", "tow", "work", "legal job"],
  },

  /* ------------------------------------------------------------------ */
  {
    id: "gs-fivem-economy-banking-suite",
    slug: "fivem-economy-banking-suite",
    title: "Economy & Banking Suite",
    platform: "fivem",
    category: "economy",
    tags: ["Banking", "Economy", "Invoices"],
    frameworks: FRAMEWORKS,
    summary: "Banking, ATMs, loans, invoices and business accounts, with an economy dashboard for tuning — maintained monthly.",
    description: [
      "Economy & Banking Suite gives a FiveM city a financial system that holds together. Players manage personal and shared accounts, use ATMs, take loans with repayment schedules and pay invoices, while businesses and departments run accounts with permissions and statements.",
      "It is for owners who want money to mean something and staff who need to see where it goes. An economy dashboard shows money supply, sources and sinks over time, so you can tune wages, prices and taxes on evidence rather than complaints. Bridges cover ESX, QBCore and Qbox accounts.",
      "While subscribed you receive every module, fixes and new modules as they release, plus compatibility updates when frameworks change. If you cancel, updates stop and the licence to run the suite ends with the period you have paid for. Your players' balances stay in your database.",
    ],
    whatYouGet: [
      "Bank interface with personal, shared and business accounts",
      "ATM interface for withdrawals, deposits and transfers",
      "Loans with credit checks and repayment schedules",
      "Invoices and fines for businesses and departments",
      "Economy dashboard: money supply, sources and sinks over time",
      "Tax and fee configuration",
      "ESX, QBCore and Qbox account bridges",
    ],
    features: [
      { title: "Money with meaning", body: "Loans, invoices and taxes give spending and saving consequences." },
      { title: "Tune on evidence", body: "The economy dashboard shows exactly where money enters and leaves." },
      { title: "Accounts for everyone", body: "Shared, business and department accounts with permissions and statements." },
    ],
    compatibility: SCRIPT_COMPAT,
    requirements: SCRIPT_REQUIRES,
    license: [...LICENSE_SERVER, "The suite is licensed while your subscription is active."],
    installation: scriptInstall("the suite"),
    pricing: { kind: "subscription", monthly: 88, annual: 840 },
    models: ["update-plan", "vault"],
    cadence: ["Every module from your first day", "New modules as they release", "Updates when frameworks change"],
    afterCancel: [
      "Access and updates continue until the end of the period you paid for.",
      "The licence to run the suite ends with the subscription.",
      "Player balances and transaction history stay in your database.",
    ],
    eligibleResourceTypes: ["Banking and ATM systems", "Loans and credit", "Invoicing and billing", "Economy monitoring and tuning"],
    media: [
      image("fivem-economy-banking-suite", "cover", "Bank interface with account balances, recent transactions and a loan", "Built interface — bank"),
      image("fivem-economy-banking-suite", "gallery-2", "ATM screen with quick withdrawal amounts and a balance", "Built interface — ATM"),
      image("fivem-economy-banking-suite", "gallery-3", "Economy dashboard charting money supply, sources and sinks", "Built interface — economy dashboard"),
    ],
    cardImage: card("fivem-economy-banking-suite", "Economy & Banking Suite — bank preview"),
    availability: "launching",
    curation: 19,
    releasedAt: LAUNCH_DATE,
    updatedAt: LAUNCH_DATE,
    searchTerms: ["bank", "banking", "atm", "loan", "invoice", "billing", "money", "tax", "economy"],
  },

  /* ------------------------------------------------------------------ */
  {
    id: "gs-fivem-inventory-suite",
    slug: "fivem-inventory-suite",
    title: "Inventory Suite",
    platform: "fivem",
    category: "inventory",
    tags: ["Inventory", "Crafting", "Update plan"],
    frameworks: FRAMEWORKS,
    summary: "A grid inventory with crafting, shops, stashes and trading, kept current with every framework update.",
    description: [
      "Inventory Suite is DistroSource's inventory for FiveM: a weight-and-slot grid with a hotbar, containers and drops, together with crafting benches, shops, stashes and player trading built on the same item system. Items carry metadata for durability, serial numbers and quality.",
      "It is for servers replacing an inventory that fights their other resources. The suite exposes a documented item API and ships bridges for ESX, QBCore and Qbox, plus a set of item images for common roleplay items, so a new item can be added with one config entry.",
      "While subscribed you get monthly fixes, new container and crafting features, and updates when frameworks or FiveM change. If you cancel, updates stop and the licence to run Inventory Suite ends with the period you have paid for.",
    ],
    whatYouGet: [
      "Weight-and-slot grid inventory with hotbar",
      "Crafting benches with recipes, skill levels and timers",
      "Shops, stashes, trunks and gloveboxes",
      "Player-to-player trading with confirmation",
      "Item metadata for durability, serials and quality",
      "Documented item API and common item images",
      "Updates for ESX, QBCore, Qbox and FiveM changes",
    ],
    features: [
      { title: "One item system", body: "Inventory, crafting, shops and trading all use the same items and metadata." },
      { title: "Clear at a glance", body: "Weight, durability and stack counts are readable without hovering." },
      { title: "Built for developers", body: "A documented API for adding items, containers and hooks." },
    ],
    compatibility: SCRIPT_COMPAT,
    requirements: SCRIPT_REQUIRES,
    license: [...LICENSE_SERVER, "Inventory Suite is licensed while your subscription is active."],
    installation: scriptInstall("Inventory Suite"),
    pricing: { kind: "subscription", monthly: 32, annual: 305 },
    models: ["update-plan"],
    cadence: ["The full suite from your first day", "Monthly fixes and features", "Updates when frameworks or FiveM change"],
    afterCancel: AFTER_CANCEL_LICENSED("Inventory Suite"),
    eligibleResourceTypes: ["Inventory and containers", "Crafting systems", "Shops and trading", "Item images"],
    media: [
      image("fivem-inventory-suite", "cover", "Grid inventory with hotbar, item weights and a vehicle trunk container", "Built interface — inventory"),
      image("fivem-inventory-suite", "gallery-2", "Crafting bench with recipes, required materials and a progress timer", "Built interface — crafting bench"),
      image("fivem-inventory-suite", "gallery-3", "Player trade window with offered items and confirmation", "Built interface — trading"),
    ],
    cardImage: card("fivem-inventory-suite", "Inventory Suite — inventory preview"),
    availability: "launching",
    curation: 21,
    releasedAt: LAUNCH_DATE,
    updatedAt: LAUNCH_DATE,
    searchTerms: ["inventory", "items", "crafting", "stash", "trunk", "shop", "trade", "hotbar", "weight"],
  },

  /* ------------------------------------------------------------------ */
  {
    id: "gs-fivem-sound-library",
    slug: "fivem-sound-library",
    title: "Sound Library",
    platform: "fivem",
    category: "audio",
    tags: ["Audio", "Sirens", "Pick & keep"],
    frameworks: ["standalone"],
    summary: "Siren tones, engine sounds and ambience for FiveM. Pick five sounds a month and keep them.",
    description: [
      "Sound Library is an audio subscription for FiveM servers. DistroSource publishes a monthly drop of original sounds — emergency siren tones, engine and exhaust notes, horns, and ambient loops for interiors and streets — and you pick five to add to your server permanently.",
      "It is for servers that want their city to sound as considered as it looks. Sirens ship as audio banks with tone switching, engines as replacement audio for add-on vehicles, and ambience as loops ready for interior zones, each with instructions for streaming it correctly.",
      "Sounds you pick are yours to keep after you cancel, and unused picks do not roll over. While subscribed you can preview the whole library in your Gaming Library before you choose, so every pick is one you have heard.",
    ],
    whatYouGet: [
      "A monthly drop of original sounds",
      "Five sound picks per month, kept permanently",
      "Emergency siren tones with tone-switch banks",
      "Engine, exhaust and horn sounds for add-on vehicles",
      "Ambient loops for interiors and streets",
      "Streaming instructions for every sound",
    ],
    features: [
      { title: "Original recordings", body: "Every sound is made by DistroSource, not ripped from other games." },
      { title: "Hear before you pick", body: "Preview the full library in your Gaming Library." },
      { title: "Yours to keep", body: "Picked sounds stay licensed to you after you cancel." },
    ],
    compatibility: ["Standalone audio resources", "Works with common siren controllers and add-on vehicles"],
    requirements: ["A FiveM server you own or operate"],
    license: [...LICENSE_SERVER, "Sounds you pick stay licensed to you after you cancel."],
    installation: [
      "Pick your sounds for the month in your Gaming Library.",
      "Download each sound resource and place it in your resources directory.",
      "Follow the streaming notes to assign sirens, engines or ambient zones.",
      "Add `ensure <resource-name>` to server.cfg and restart.",
    ],
    pricing: { kind: "subscription", monthly: 15, annual: 140 },
    models: ["monthly-drop", "pick-and-keep"],
    cadence: ["One sound drop every month", "Five picks per billing month", "Unused picks do not roll over"],
    afterCancel: [
      "Sounds you picked stay licensed to you permanently.",
      "No new picks after the paid period ends.",
      "Library previews end with the subscription.",
    ],
    eligibleResourceTypes: ["Siren tones", "Engine and exhaust sounds", "Horns", "Ambient loops"],
    media: [
      image("fivem-sound-library", "cover", "Siren control panel with wail, yelp and phaser tones over a patrol car at night", "Built interface — siren tone bank"),
      image("fivem-sound-library", "gallery-2", "Sound browser with waveforms for siren, engine and ambience sounds", "Built interface — sound browser"),
      image("fivem-sound-library", "gallery-3", "Monthly sound drop with five picks selected", "Built interface — monthly picks"),
    ],
    cardImage: card("fivem-sound-library", "Sound Library — siren control preview"),
    availability: "launching",
    curation: 25,
    releasedAt: LAUNCH_DATE,
    updatedAt: LAUNCH_DATE,
    searchTerms: ["sound", "sounds", "siren", "sirens", "engine sound", "exhaust", "horn", "ambience", "audio"],
  },

  /* ------------------------------------------------------------------ */
  {
    id: "gs-fivem-loading-screen-club",
    slug: "fivem-loading-screen-club",
    title: "Loading Screen Club",
    platform: "fivem",
    category: "graphics-branding",
    tags: ["Loading screens", "Branding", "Monthly drop"],
    frameworks: ["standalone"],
    summary: "A new editable FiveM loading screen every month, with real load progress, tips and music built in.",
    description: [
      "Loading Screen Club delivers a new FiveM loading screen every month: a complete, editable design with your server name, logo, rotating tips, staff and rules panels, a music player and a real load-progress bar driven by FiveM's loading events.",
      "It is for servers that want the first thirty seconds of every session to look deliberate. Each screen is plain HTML, CSS and JavaScript with a single config file for text, colours, background images and music, so you can make it yours without touching the layout. Designs rotate through styles — cinematic, minimal and illustrated — so a server can refresh its look each season.",
      "Every screen released while you are subscribed is yours to keep and use after you cancel. Back-catalogue access lasts as long as your subscription does.",
    ],
    whatYouGet: [
      "A new loading screen design every month",
      "Real load-progress bar driven by FiveM loading events",
      "Rotating tips, rules and staff panels",
      "Built-in music player for your own tracks",
      "One config file for text, colours, images and music",
      "Every screen released while subscribed, kept permanently",
    ],
    features: [
      { title: "Real progress", body: "The bar follows FiveM's loading events instead of a fake timer." },
      { title: "Edit one file", body: "Text, colours, images and music live in a single config." },
      { title: "Keep every month", body: "Screens released while you are subscribed stay yours." },
    ],
    compatibility: ["FiveM loadscreen, including manual shutdown", "Any framework — no dependencies"],
    requirements: ["A FiveM server you own or operate"],
    license: [...LICENSE_CREATOR, "Screens released during your paid months stay licensed to you after you cancel."],
    installation: [
      "Download the month's screen from your Gaming Library.",
      "Place the resource in your resources directory.",
      "Edit config.js with your name, colours, images and music.",
      "Add `ensure <resource-name>` to server.cfg and restart.",
    ],
    pricing: { kind: "subscription", monthly: 10, annual: 95 },
    models: ["creator", "monthly-drop"],
    cadence: ["One new loading screen every month", "Back catalogue available while subscribed"],
    afterCancel: [
      "Screens released during your paid months stay yours permanently.",
      "Back-catalogue access ends with the subscription.",
      "No new screens after the paid period ends.",
    ],
    eligibleResourceTypes: ["Loading screens", "Server branding panels", "Music player layouts"],
    media: [
      image("fivem-loading-screen-club", "cover", "Cinematic loading screen with server name, load progress, tips and a music player", "Design mockup — loading screen"),
      image("fivem-loading-screen-club", "gallery-2", "Minimal loading screen with rules and staff panels", "Design mockup — minimal loading screen"),
      image("fivem-loading-screen-club", "gallery-3", "Four loading screen styles from the monthly set", "Design mockup — monthly set"),
    ],
    cardImage: card("fivem-loading-screen-club", "Loading Screen Club — loading screen preview"),
    availability: "launching",
    curation: 26,
    releasedAt: LAUNCH_DATE,
    updatedAt: LAUNCH_DATE,
    searchTerms: ["loading screen", "loadscreen", "loading", "intro", "music", "branding"],
  },
]
