import type { GamingFramework, GamingPricing, GamingProduct } from "@/lib/gaming/catalog/types"
import { AFTER_CANCEL_LICENSED, LAUNCH_DATE, LICENSE_SERVER, card, image } from "@/lib/gaming/catalog/media"

/** FiveM subscriptions added in the second catalogue batch (products 28–31). */

const FRAMEWORKS: GamingFramework[] = ["esx", "qbcore", "qbox"]
const SCRIPT_COMPAT = ["ESX Legacy", "QBCore", "Qbox", "oxmysql"]
const SCRIPT_REQUIRES = ["A FiveM server running ESX, QBCore or Qbox", "oxmysql"]
/** Monthly price with the catalogue's annual rule: about 9.6 months, rounded down to $5. */
const sub = (monthly: number): GamingPricing => ({ kind: "subscription", monthly, annual: Math.floor((monthly * 9.6) / 5) * 5 })

export const FIVEM_PRODUCTS_2: GamingProduct[] = [
  /* ------------------------------------------------------------------ */
  {
    id: "gs-fivem-emote-animation-library",
    slug: "fivem-emote-animation-library",
    title: "Emote & Animation Library",
    platform: "fivem",
    category: "animations",
    tags: ["Animations", "Emotes", "Monthly drop"],
    frameworks: ["standalone"],
    summary: "An emote menu with a growing library of original animations — gestures, poses, dances, props and synced emotes — with new clips every month.",
    description: [
      "Emote & Animation Library is a subscription to DistroSource's animation work for FiveM: a fast emote menu with a radial wheel, and a library of original animation clips made for roleplay — everyday gestures, sitting and leaning poses, job actions, prop animations, dances, and synced emotes for two players such as handshakes, hugs and carrying.",
      "It is for servers whose players fall back on the same handful of stock emotes. Every clip is keyframed for the game's ped skeleton, streamed as a standard animation dictionary and tagged by category, loop behaviour and props, so players find what they need from the wheel, the searchable menu or a chat command, and staff can switch off anything that does not fit the city.",
      "New clips are released every month and every released clip is available while you are subscribed. If you cancel, updates stop and the licence to run the library ends with the period you have paid for.",
    ],
    whatYouGet: [
      "Emote menu with a radial wheel, search and favourites",
      "Original animation clips streamed as animation dictionaries",
      "Gestures, poses, job actions, dances and prop animations",
      "Synced two-player emotes with request and accept",
      "Walk styles and moods saved per character",
      "Staff controls to disable, restrict or rename any clip",
      "New clips every month",
    ],
    features: [
      { title: "Made for roleplay", body: "Clips cover the small, everyday moments players act out most." },
      { title: "Find it fast", body: "A wheel for favourites, search for everything else and chat commands for regulars." },
      { title: "Two-player moments", body: "Synced emotes line both players up and wait for the other to accept." },
    ],
    compatibility: ["FiveM, current recommended server artifacts", "Standalone resource — no framework required", "Runs alongside ESX, QBCore and Qbox"],
    requirements: ["A FiveM server you own or operate", "OneSync enabled for synced emotes"],
    license: [...LICENSE_SERVER, "The library is licensed while your subscription is active."],
    installation: [
      "Download the menu and the animation packs from your Gaming Library.",
      "Place the resources in your server's resources directory.",
      "Choose keybinds, wheel slots and disabled clips in the config.",
      "Add the `ensure` lines to server.cfg and restart.",
    ],
    pricing: sub(187),
    models: ["vault", "monthly-drop"],
    cadence: ["New animation clips every month", "Every released clip while subscribed", "Menu updates and fixes as they release"],
    afterCancel: AFTER_CANCEL_LICENSED("the library"),
    eligibleResourceTypes: ["Emotes and gestures", "Poses and scenarios", "Prop animations", "Synced emotes", "Walk styles"],
    media: [
      image("fivem-emote-animation-library", "cover", "In-game emote wheel over a city street with categories, favourites and a selected emote", "Built interface — emote wheel"),
      image("fivem-emote-animation-library", "gallery-2", "Animation library browser with categories, clip details and a pose preview", "Built interface — animation library"),
      image("fivem-emote-animation-library", "gallery-3", "Synced emote request between two players, with walk styles and moods", "Built interface — synced emotes"),
    ],
    cardImage: card("fivem-emote-animation-library", "Emote & Animation Library — emote wheel preview"),
    availability: "on-sale",
    curation: 28,
    releasedAt: LAUNCH_DATE,
    updatedAt: LAUNCH_DATE,
    searchTerms: ["emote menu", "animations", "dances", "poses", "walk style", "gestures", "synced emotes", "props"],
  },

  /* ------------------------------------------------------------------ */
  {
    id: "gs-fivem-realtor-system",
    slug: "fivem-realtor-system",
    title: "Realtor System",
    platform: "fivem",
    category: "housing",
    tags: ["Real estate job", "Contracts", "Update plan"],
    frameworks: FRAMEWORKS,
    summary: "A real estate job for FiveM: agencies list properties, book viewings, sign contracts and earn commission, connected to your housing resource.",
    description: [
      "Realtor System turns property in your FiveM city into a job. Estate agents join an agency, take listings from owners and the city, describe and price each property, book viewings, and close sales and lettings with a signed contract, a deposit and optional financing, earning commission on every deal.",
      "It is for servers where housing exists but nobody plays the business around it. Agencies run from a tablet dashboard with a listings pipeline, a viewing calendar and a commission ledger, and every contract is stored with both signatures so disputes can be settled in character. Bridges for common housing resources mean keys and ownership change hands the moment a contract is signed.",
      "New contract types, housing bridges and fixes arrive while you are subscribed. If you cancel, updates stop and the licence to run the system ends with the period you have paid for. Contracts and agency records stay in your database.",
    ],
    whatYouGet: [
      "Agency job with ranks, agents and commission splits",
      "Listings pipeline from new listing to keys handed over",
      "Viewing calendar with map pins and reminders",
      "Sale and letting contracts with signatures and deposits",
      "Optional financing with terms and repayments",
      "Bridges for common housing resources",
      "ESX, QBCore and Qbox support",
    ],
    features: [
      { title: "Property becomes play", body: "Listings, viewings and negotiations give agents real work in the city." },
      { title: "Contracts that stick", body: "Every deal is stored with signatures, terms and payment history." },
      { title: "Keys change hands", body: "Signing a contract updates ownership in your housing resource." },
    ],
    compatibility: [...SCRIPT_COMPAT, "Common housing resources through bridges"],
    requirements: [...SCRIPT_REQUIRES, "A housing resource that manages ownership"],
    license: [...LICENSE_SERVER, "The system is licensed while your subscription is active."],
    installation: [
      "Download Realtor System from your Gaming Library.",
      "Place the resource in your resources directory and run the bundled SQL migration.",
      "Choose your framework and housing bridge in the config, then set agency ranks and commission.",
      "Add the `ensure` line after your housing resource and restart.",
    ],
    pricing: sub(176),
    models: ["update-plan"],
    cadence: ["The full system from your first day", "New contract types and housing bridges as they release", "Framework compatibility updates"],
    afterCancel: [
      "Access and updates continue until the end of the period you paid for.",
      "The licence to run the system ends with the subscription.",
      "Contracts and agency records remain in your database.",
    ],
    eligibleResourceTypes: ["Real estate jobs", "Property contracts", "Financing", "Housing bridges"],
    media: [
      image("fivem-realtor-system", "cover", "Estate agency dashboard with a listings pipeline, today's viewings and commission", "Built interface — agency dashboard"),
      image("fivem-realtor-system", "gallery-2", "Property sale contract on a tablet with terms, deposit and both signatures", "Built interface — sale contract"),
      image("fivem-realtor-system", "gallery-3", "Viewing calendar with a city map, booked viewings and agent assignments", "Built interface — viewing calendar"),
    ],
    cardImage: card("fivem-realtor-system", "Realtor System — agency dashboard preview"),
    availability: "on-sale",
    curation: 29,
    releasedAt: LAUNCH_DATE,
    updatedAt: LAUNCH_DATE,
    searchTerms: ["realtor", "real estate", "estate agent", "property", "mortgage", "rent", "housing job", "contracts"],
  },

  /* ------------------------------------------------------------------ */
  {
    id: "gs-fivem-retail-interiors",
    slug: "fivem-retail-interiors",
    title: "Retail Interiors",
    platform: "fivem",
    category: "mlos-maps",
    tags: ["MLO", "Shops", "Monthly drop"],
    frameworks: ["standalone"],
    summary: "Shop interiors for FiveM — convenience stores, boutiques and service counters — with registers, stock rooms and interaction points marked, and new stores every month.",
    description: [
      "Retail Interiors is a subscription to DistroSource's shop interiors for FiveM. Each store is a complete MLO built for roleplay trade: a shop floor with shelving and fridges, a counter with a register, a stock room behind a staff door and exterior signage, with entity and texture budgets kept low enough for busy streets.",
      "It is for servers whose businesses and robbery scenes all happen in the same few default shops. Every interior ships with its interaction points documented — registers, safes, stock shelves, cameras and doors — along with config snippets for common shop, robbery and business resources, so a new store can be trading on the day it is installed.",
      "New store interiors are released every month and every released interior is available while you are subscribed. If you cancel, updates stop and the licence to use the interiors ends with the period you have paid for.",
    ],
    whatYouGet: [
      "Store interiors with a shop floor, counter, stock room and signage",
      "Registers, safes, cameras and doors marked as interaction points",
      "Config snippets for common shop, robbery and business resources",
      "Occlusion, portals and LODs set up for street performance",
      "A spec sheet per store with entity and texture budgets",
      "New store interiors every month",
    ],
    features: [
      { title: "Ready to trade", body: "Interaction points are marked and documented, not left for you to find." },
      { title: "Light on the street", body: "Entity counts and texture memory are budgeted for busy city blocks." },
      { title: "Beyond the default shops", body: "New stores give businesses and robberies fresh places to happen." },
    ],
    compatibility: ["FiveM, current recommended server artifacts", "Standalone interiors — no framework required", "Config snippets for ESX, QBCore and Qbox shop resources"],
    requirements: ["A FiveM server you own or operate", "Space in your resources folder for streamed interiors"],
    license: [...LICENSE_SERVER, "Interiors are licensed while your subscription is active."],
    installation: [
      "Download the store interiors from your Gaming Library.",
      "Place each interior in your resources directory as its own resource.",
      "Copy the config snippets for your shop and robbery resources.",
      "Add the `ensure` lines to server.cfg and restart.",
    ],
    pricing: sub(156),
    models: ["vault", "monthly-drop"],
    cadence: ["New store interiors every month", "Every released interior while subscribed", "Fixes to existing interiors"],
    afterCancel: AFTER_CANCEL_LICENSED("the interiors"),
    eligibleResourceTypes: ["Convenience stores", "Boutiques and clothing shops", "Service counters", "Shop props and signage"],
    media: [
      image("fivem-retail-interiors", "cover", "Convenience store interior with stocked aisles, a glowing fridge wall and the street outside at dusk", "Rendered preview — convenience store"),
      image("fivem-retail-interiors", "gallery-2", "Checkout counter with the register, lit sign wall and front windows", "Rendered preview — checkout counter"),
      image("fivem-retail-interiors", "gallery-3", "Interior spec sheet with a floor plan, interaction points and performance budget", "Built interface — interior spec sheet"),
    ],
    cardImage: card("fivem-retail-interiors", "Retail Interiors — convenience store preview"),
    availability: "on-sale",
    curation: 30,
    releasedAt: LAUNCH_DATE,
    updatedAt: LAUNCH_DATE,
    searchTerms: ["mlo", "shop", "store", "convenience store", "interior", "robbery", "business", "map"],
  },

  /* ------------------------------------------------------------------ */
  {
    id: "gs-fivem-world-interaction-pack",
    slug: "fivem-world-interaction-pack",
    title: "World Interaction Pack",
    platform: "fivem",
    category: "scripts-systems",
    tags: ["Interactions", "Target", "Update plan"],
    frameworks: FRAMEWORKS,
    summary: "Everyday world interactions for FiveM — sit anywhere, vending machines, ATMs, payphones, bins, carry and knock — through one target system.",
    description: [
      "World Interaction Pack makes the props that fill a FiveM city usable. Players can sit on benches, chairs and sofas, buy from vending machines and food carts, use ATMs and payphones, search bins, knock on doors, carry and drag other players, and ride elevators, all through one target system and one config file.",
      "It is for servers where the world looks rich but does nothing when players reach for it. Interactions are mapped to the game's own props rather than placed by hand, so they work across the whole map from the first restart, and each one can be priced, restricted by job or switched off. It uses the common target resources, so interactions appear in the menu players already know.",
      "New interactions, prop mappings and fixes are released while you are subscribed. If you cancel, updates stop and the licence to run the pack ends with the period you have paid for.",
    ],
    whatYouGet: [
      "Sit, lie and lean on mapped seats, benches and beds",
      "Vending machines, food carts, ATMs and payphones",
      "Bin searching with configurable loot tables",
      "Carry, drag and knock interactions",
      "Elevators with floor menus",
      "One config for prices, jobs and toggles",
      "New interactions while subscribed",
    ],
    features: [
      { title: "Works across the map", body: "Interactions follow the game's props, so no placement work is needed." },
      { title: "One target system", body: "Everything appears in the target menu players already use." },
      { title: "Yours to tune", body: "Price, restrict or switch off each interaction in one file." },
    ],
    compatibility: [...SCRIPT_COMPAT, "ox_target or qb-target"],
    requirements: [...SCRIPT_REQUIRES, "ox_target or qb-target"],
    license: [...LICENSE_SERVER, "The pack is licensed while your subscription is active."],
    installation: [
      "Download the pack from your Gaming Library.",
      "Place the resource in your server's resources directory.",
      "Set your framework, target resource, prices and toggles in the config.",
      "Add the `ensure` line to server.cfg after your target resource, then restart.",
    ],
    pricing: sub(62),
    models: ["vault", "update-plan"],
    cadence: ["Every interaction from your first day", "New interactions and prop mappings as they release", "Framework and target updates"],
    afterCancel: AFTER_CANCEL_LICENSED("the pack"),
    eligibleResourceTypes: ["World interactions", "Seating", "Vending and services", "Player interactions"],
    media: [
      image("fivem-world-interaction-pack", "cover", "Target menu on a street vending machine with buy options, beside a bench players can sit on", "Built interface — target interactions"),
      image("fivem-world-interaction-pack", "gallery-2", "Interaction config with toggles, prices and job restrictions", "Built interface — interaction config"),
      image("fivem-world-interaction-pack", "gallery-3", "Catalogue of interactions grouped by type, with the props each one covers", "Built interface — interaction catalogue"),
    ],
    cardImage: card("fivem-world-interaction-pack", "World Interaction Pack — target interactions preview"),
    availability: "on-sale",
    curation: 31,
    releasedAt: LAUNCH_DATE,
    updatedAt: LAUNCH_DATE,
    searchTerms: ["target", "third eye", "sit", "vending machine", "atm", "payphone", "carry", "interactions"],
  },
]
