import type { GamingProduct } from "@/lib/gaming/catalog/types"
import { AFTER_CANCEL_LICENSED, LAUNCH_DATE, card, image } from "@/lib/gaming/catalog/media"

/** Minecraft subscriptions. */

const LICENSE_NETWORK = [
  "Licensed for one server network you own or operate.",
  "You may edit and configure the files for that network.",
  "Reselling, sharing or re-uploading the files is not permitted.",
]
const JAVA_SERVER = "A Minecraft: Java Edition server you own or operate"

export const MINECRAFT_PRODUCTS: GamingProduct[] = [
  /* ------------------------------------------------------------------ */
  {
    id: "gs-minecraft-prison-network-setup",
    slug: "minecraft-prison-network-setup",
    title: "Prison Network Setup",
    platform: "minecraft",
    category: "server-setups",
    tags: ["Server setup", "Prison", "Monthly update"],
    frameworks: [],
    summary: "A complete prison server — mines, ranks, cells and economy — built, configured and updated every month.",
    description: [
      "Prison Network Setup is a complete Minecraft prison gamemode delivered as a subscription: the builds, plugin configuration and progression design you need to open a prison server. You get the spawn, cell blocks, rank mines and yard, together with configured ranks, prestiges, an economy and resetting mines.",
      "It is for network owners who want a proven gamemode structure without months of balancing. The setup is tuned as a whole — mine resets, sell prices, rank-up costs and enchant costs are designed together and documented, so you can change the pacing knowingly. It runs on Paper, with every required plugin listed in the setup guide.",
      "Each month the setup receives a tested update: a new mine or area, balance changes and plugin-version updates, delivered with a changelog. If you cancel, updates stop and the licence to run the setup ends with the period you have paid for. Your players' data remains yours.",
    ],
    whatYouGet: [
      "Spawn, cell block, yard and rank mine builds",
      "Rank, prestige and rank-up cost configuration",
      "Resetting mines with tuned block mixes",
      "Economy with sell prices, shops and enchant costs designed together",
      "Setup guide with the plugin list and install order",
      "A tested monthly update with a new area and balance changes",
      "Staff and permission groups preconfigured",
    ],
    features: [
      { title: "Balanced as one system", body: "Mines, prices and rank costs are tuned together, and every number is documented." },
      { title: "Built and configured", body: "The builds and the configuration arrive as one working setup." },
      { title: "Keeps moving", body: "A new area and balance pass every month keep the progression fresh." },
    ],
    compatibility: ["Minecraft: Java Edition", "Paper, current release line", "WorldEdit or FastAsyncWorldEdit for builds"],
    requirements: [JAVA_SERVER, "A host with at least 6 GB RAM"],
    license: [...LICENSE_NETWORK, "The setup is licensed while your subscription is active."],
    installation: [
      "Download the setup from your Gaming Library.",
      "Install the plugins listed in the setup guide on a staging server.",
      "Copy the bundled configs and worlds, then follow the checklist.",
      "Test a full rank-up path, then open the server.",
    ],
    pricing: { kind: "subscription", monthly: 144, annual: 1380 },
    models: ["server-owner", "update-plan"],
    cadence: ["The complete setup from your first day", "A new mine or area every month", "Balance and plugin-version updates"],
    afterCancel: [
      "Access and updates continue until the end of the period you paid for.",
      "The licence to run the setup ends with the subscription.",
      "Your players' data remains yours.",
    ],
    eligibleResourceTypes: ["Prison builds and mines", "Rank and prestige configuration", "Economy and shop configuration", "Permission groups"],
    media: [
      image("minecraft-prison-network-setup", "cover", "Prison yard with stone cell blocks, watchtowers and a stepped mine pit", "Rendered preview — prison yard"),
      image("minecraft-prison-network-setup", "gallery-2", "Rank configuration with rank-up costs, mine access and prestige rewards", "Built interface — rank configuration"),
      image("minecraft-prison-network-setup", "gallery-3", "Rank mine seen from the rim, with layered ore bands and a reset sign", "Rendered preview — rank mine"),
    ],
    cardImage: card("minecraft-prison-network-setup", "Prison Network Setup — prison yard preview"),
    availability: "launching",
    curation: 10,
    releasedAt: LAUNCH_DATE,
    updatedAt: LAUNCH_DATE,
    searchTerms: ["prison", "mines", "ranks", "prestige", "server setup", "gamemode", "network"],
  },

  /* ------------------------------------------------------------------ */
  {
    id: "gs-minecraft-minigame-arenas",
    slug: "minecraft-minigame-arenas",
    title: "Minigame Arenas",
    platform: "minecraft",
    category: "minigames",
    tags: ["Minigames", "Arenas", "Monthly drop"],
    frameworks: [],
    summary: "Team arenas, waiting lobbies and minigame configs for Minecraft networks, with new arenas every month.",
    description: [
      "Minigame Arenas is a subscription for Minecraft networks that run competitive modes. It delivers team arenas with island bases, bridges and central objectives, waiting lobbies, and the configuration that turns them into playable games: team spawns, resource generators, shop layouts and map rotation.",
      "It is for networks that need fresh maps to keep a mode alive without pausing development for build work. Arenas are balanced for two, four and eight teams, marked with spawn and generator positions, and tested for sightlines and rush distances before release.",
      "New arenas are released every month and every released arena is available while you are subscribed, along with balance revisions to existing ones. If you cancel, arenas stop updating and the licence to run them ends with the period you have paid for.",
    ],
    whatYouGet: [
      "Team arenas balanced for two, four and eight teams",
      "Waiting lobbies matched to each arena's theme",
      "Marked team spawns, generators and objectives",
      "Shop layouts and map-rotation configuration",
      "Schematics and ready-to-load worlds",
      "New arenas every month",
      "Balance revisions to existing arenas",
    ],
    features: [
      { title: "Tested for fairness", body: "Rush distances and sightlines are checked for every team before release." },
      { title: "Drop-in configs", body: "Spawns, generators and shops are marked and configured, not just built." },
      { title: "A steady rotation", body: "New arenas each month keep a mode's map pool fresh." },
    ],
    compatibility: ["Minecraft: Java Edition", "Paper and Purpur servers", "WorldEdit or FastAsyncWorldEdit", "Common team-minigame plugins"],
    requirements: [JAVA_SERVER, "A team-minigame plugin for your mode"],
    license: [...LICENSE_NETWORK, "Arenas are licensed while your subscription is active."],
    installation: [
      "Download arenas from your Gaming Library.",
      "Load the world or paste the schematic on your game server.",
      "Import the spawn, generator and shop positions into your minigame plugin.",
      "Add the arena to your map rotation.",
    ],
    pricing: { kind: "subscription", monthly: 140, annual: 1340 },
    models: ["vault", "monthly-drop"],
    cadence: ["New arenas released every month", "Every released arena while subscribed", "Balance revisions to existing arenas"],
    afterCancel: AFTER_CANCEL_LICENSED("the arenas"),
    eligibleResourceTypes: ["Team arenas", "Waiting lobbies", "Minigame configuration", "Map rotations"],
    media: [
      image("minecraft-minigame-arenas", "cover", "Team arena with four coloured island bases linked by bridges to a central island", "Rendered preview — team arena"),
      image("minecraft-minigame-arenas", "gallery-2", "Top-down view of the arena showing bases, bridges and the centre objective", "Rendered preview — arena overview"),
      image("minecraft-minigame-arenas", "gallery-3", "Arena setup screen with team spawns, generators and rotation", "Built interface — arena setup"),
    ],
    cardImage: card("minecraft-minigame-arenas", "Minigame Arenas — team arena preview"),
    availability: "launching",
    curation: 14,
    releasedAt: LAUNCH_DATE,
    updatedAt: LAUNCH_DATE,
    searchTerms: ["bedwars", "skywars", "arena", "minigame", "pvp", "teams", "lobby", "maps"],
  },

  /* ------------------------------------------------------------------ */
  {
    id: "gs-minecraft-plugin-suite",
    slug: "minecraft-plugin-suite",
    title: "Plugin Suite",
    platform: "minecraft",
    category: "plugins",
    tags: ["Plugins", "Crates", "Shops"],
    frameworks: [],
    summary: "Crates, shops, custom enchants and GUI menus for Minecraft servers, maintained for new game versions.",
    description: [
      "Plugin Suite is a subscription to DistroSource's Minecraft plugins: crates with animated openings and reward tables, player and server shops, custom enchantments, and a GUI menu builder, all sharing one configuration style and one set of message files.",
      "It is for server owners who want dependable gameplay plugins without juggling a dozen authors' update schedules. Every plugin supports Paper and Purpur, uses YAML configs with a comment on every option, and works with Vault-compatible economies and PlaceholderAPI.",
      "While subscribed you receive new plugins as they release and updates for new Minecraft versions. Each release is tested on a clean Paper server before it reaches your Gaming Library, and every config change is noted in the changelog. If you cancel, updates stop and the licence to run suite plugins ends with the period you have paid for.",
    ],
    whatYouGet: [
      "Crates with animated openings, keys and reward tables",
      "Player shops and staff-curated server shops",
      "Custom enchantments with configurable levels and costs",
      "GUI menu builder for navigation and server selectors",
      "Commented YAML configs and shared message files",
      "Vault economy and PlaceholderAPI support",
      "New plugins and Minecraft version updates while subscribed",
    ],
    features: [
      { title: "One configuration style", body: "Every plugin reads the same way, so staff learn it once." },
      { title: "Menus that look designed", body: "GUIs use consistent layouts, icons and lore formatting." },
      { title: "Kept current", body: "Updates follow new Minecraft versions while you are subscribed." },
    ],
    compatibility: ["Minecraft: Java Edition", "Paper and Purpur", "Vault-compatible economy plugins", "PlaceholderAPI"],
    requirements: [JAVA_SERVER, "A Vault-compatible economy plugin for shops and crates"],
    license: [...LICENSE_NETWORK, "Suite plugins are licensed while your subscription is active."],
    installation: [
      "Download the plugins you want from your Gaming Library.",
      "Place the .jar files in your server's plugins folder.",
      "Restart to generate configs, then edit the commented YAML files.",
      "Reload the plugin or restart to apply changes.",
    ],
    pricing: { kind: "subscription", monthly: 95, annual: 910 },
    models: ["vault", "update-plan"],
    cadence: ["Every suite plugin from your first day", "New plugins as they release", "Updates for new Minecraft versions"],
    afterCancel: AFTER_CANCEL_LICENSED("suite plugins"),
    eligibleResourceTypes: ["Gameplay plugins", "Economy and shop plugins", "Crates and rewards", "GUI menus"],
    media: [
      image("minecraft-plugin-suite", "cover", "Crate opening menu with a reward reel and keys over a Minecraft spawn", "Built interface — crate menu"),
      image("minecraft-plugin-suite", "gallery-2", "Server shop menu with item categories, prices and a balance", "Built interface — server shop"),
      image("minecraft-plugin-suite", "gallery-3", "Commented YAML configuration for a crate's reward table", "Built interface — plugin config"),
    ],
    cardImage: card("minecraft-plugin-suite", "Plugin Suite — crate menu preview"),
    availability: "launching",
    curation: 18,
    releasedAt: LAUNCH_DATE,
    updatedAt: LAUNCH_DATE,
    searchTerms: ["plugin", "plugins", "crates", "shop", "enchants", "gui", "menu", "spigot", "paper"],
  },

  /* ------------------------------------------------------------------ */
  {
    id: "gs-minecraft-skyblock-islands",
    slug: "minecraft-skyblock-islands",
    title: "Skyblock Islands",
    platform: "minecraft",
    category: "worlds-maps",
    tags: ["Skyblock", "Islands", "Pick & keep"],
    frameworks: [],
    summary: "Starter islands and skyblock spawns for Minecraft servers. Claim three builds a month and keep them.",
    description: [
      "Skyblock Islands is a build subscription for skyblock servers. Every month DistroSource releases a set of starter islands and a skyblock spawn, and you claim three builds to keep — schematics ready for your island plugin's schematic folder.",
      "It is for owners who want new players to land somewhere memorable. Islands come in themes — classic, desert, snow, jungle and nether — each with the resources a player needs to start, a chest location and a marked island centre, balanced so no theme starts ahead. Spawns are sized for common island plugins and include warp and NPC positions.",
      "Claimed builds are yours to keep and edit for your server after you cancel, and unused claims do not roll over. While subscribed you can preview every build in the monthly set before you choose.",
    ],
    whatYouGet: [
      "A monthly set of starter islands and a skyblock spawn",
      "Three build claims per month, kept permanently",
      "Themed islands: classic, desert, snow, jungle and nether",
      "Starter resources, chest location and marked island centre",
      "Schematics for your island plugin",
      "Preview worlds for every build",
    ],
    features: [
      { title: "Fair starts", body: "Every theme is balanced to the same starting resources." },
      { title: "Plugin ready", body: "Island centres and chest positions are marked for island plugins." },
      { title: "Yours to keep", body: "Claimed builds stay licensed to you after you cancel." },
    ],
    compatibility: ["Minecraft: Java Edition", "Common skyblock island plugins", "WorldEdit or FastAsyncWorldEdit"],
    requirements: [JAVA_SERVER, "A skyblock island plugin"],
    license: [...LICENSE_NETWORK, "Claimed builds stay licensed to you after you cancel."],
    installation: [
      "Claim builds for the month in your Gaming Library.",
      "Copy island schematics into your island plugin's schematics folder.",
      "Register each island type in the plugin's config.",
      "Paste the spawn with WorldEdit and set the warp at the marked point.",
    ],
    pricing: { kind: "subscription", monthly: 18, annual: 170 },
    models: ["pick-and-keep", "monthly-drop"],
    cadence: ["A new island set every month", "Three claims per billing month", "Unused claims do not roll over"],
    afterCancel: [
      "Builds you claimed stay licensed to you permanently.",
      "No new claims after the paid period ends.",
      "Monthly previews end with the subscription.",
    ],
    eligibleResourceTypes: ["Starter islands", "Skyblock spawns", "Warp and event islands"],
    media: [
      image("minecraft-skyblock-islands", "cover", "Floating starter islands with a tree, chest and dirt underside in the sky", "Rendered preview — starter islands"),
      image("minecraft-skyblock-islands", "gallery-2", "Skyblock spawn island with a portal ring and walkways", "Rendered preview — skyblock spawn"),
      image("minecraft-skyblock-islands", "gallery-3", "Five island themes from the monthly set side by side", "Rendered preview — island themes"),
    ],
    cardImage: card("minecraft-skyblock-islands", "Skyblock Islands — starter island preview"),
    availability: "launching",
    curation: 22,
    releasedAt: LAUNCH_DATE,
    updatedAt: LAUNCH_DATE,
    searchTerms: ["skyblock", "island", "islands", "one block", "schematic", "spawn"],
  },

  /* ------------------------------------------------------------------ */
  {
    id: "gs-minecraft-resource-pack-studio",
    slug: "minecraft-resource-pack-studio",
    title: "Resource Pack Studio",
    platform: "minecraft",
    category: "resource-packs",
    tags: ["Resource pack", "Textures", "GUIs"],
    frameworks: [],
    summary: "Original 16× block textures, GUI skins and custom item models for Minecraft servers, delivered monthly.",
    description: [
      "Resource Pack Studio is a monthly resource-pack subscription for Minecraft servers. Each month adds a themed set of original 16×16 block textures, matching GUI skins for inventories and menus, and custom item models your plugins can assign with custom model data.",
      "It is for servers that want a recognisable look that loads for every player automatically as a server resource pack. Textures are drawn in a consistent, readable pixel style, and every set ships as a pack you can merge into your own, together with source files for edits. Each set is tested on current Java releases and documents its item model IDs.",
      "Sets released while you are subscribed are yours to keep and use on your server after you cancel. Back-catalogue sets are available while your subscription is active.",
    ],
    whatYouGet: [
      "A themed set of original 16×16 block textures every month",
      "Matching GUI skins for inventories, chests and menus",
      "Custom item models with documented model data",
      "A merge-ready server resource pack",
      "Layered source files for your own edits",
      "Sets released while subscribed, kept permanently",
    ],
    features: [
      { title: "One readable style", body: "Every texture follows the same palette and pixel rules." },
      { title: "Made to merge", body: "Packs are structured to combine with your existing server pack." },
      { title: "Keep every set", body: "Monthly sets stay yours after you cancel." },
    ],
    compatibility: ["Minecraft: Java Edition, current releases", "Server resource packs", "Plugins that support custom model data"],
    requirements: [JAVA_SERVER, "A host for the resource pack file"],
    license: [...LICENSE_NETWORK, "Sets released during your paid months stay licensed to you after you cancel."],
    installation: [
      "Download the month's set from your Gaming Library.",
      "Merge it into your server resource pack, or use it as is.",
      "Upload the pack and set `resource-pack` and its hash in server.properties.",
      "Assign custom item models in your plugins using the documented IDs.",
    ],
    pricing: { kind: "subscription", monthly: 38, annual: 360 },
    models: ["monthly-drop", "vault"],
    cadence: ["One themed set every month", "Back catalogue available while subscribed"],
    afterCancel: [
      "Sets released during your paid months stay yours permanently.",
      "Back-catalogue access ends with the subscription.",
      "No new sets after the paid period ends.",
    ],
    eligibleResourceTypes: ["Block textures", "GUI textures", "Item models", "Server resource packs"],
    media: [
      image("minecraft-resource-pack-studio", "cover", "Cottage and garden built with the pack's textured blocks in warm light", "Rendered preview — textured build"),
      image("minecraft-resource-pack-studio", "gallery-2", "Texture sheet of the month's 16×16 block textures at large scale", "Design mockup — texture sheet"),
      image("minecraft-resource-pack-studio", "gallery-3", "Inventory and chest GUI skins from the same set", "Built interface — GUI skins"),
    ],
    cardImage: card("minecraft-resource-pack-studio", "Resource Pack Studio — textured build preview"),
    availability: "launching",
    curation: 24,
    releasedAt: LAUNCH_DATE,
    updatedAt: LAUNCH_DATE,
    searchTerms: ["texture pack", "textures", "resource pack", "custom model data", "gui", "pixel art"],
  },
]
