import {
  Globe,
  Rocket,
  Briefcase,
  Sheet,
  StickyNote,
  Type,
  Palette,
  Shapes,
  Layers,
  Sparkles,
  Share2,
  Megaphone,
  Presentation,
  FileUser,
  GraduationCap,
  Baby,
  Heart,
  NotebookPen,
  Brush,
  Camera,
  Music,
  Box,
  Scissors,
  MonitorSmartphone,
  Code2,
  FileText,
  Users,
  Package,
  type LucideIcon,
} from "lucide-react"

// Explicit slug -> icon mapping for DistroSource's digital-product categories.
export const categoryIconMap: Record<string, LucideIcon> = {
  "website-templates": Globe,
  "business-starter-kits": Rocket,
  "industry-business-packs": Briefcase,
  "spreadsheet-systems": Sheet,
  "notion-productivity": StickyNote,
  "fonts-typography": Type,
  "graphics-illustrations": Palette,
  icons: Shapes,
  mockups: Layers,
  "branding-kits": Sparkles,
  "social-media-packs": Share2,
  "marketing-resources": Megaphone,
  presentations: Presentation,
  "resume-career": FileUser,
  "learning-education": GraduationCap,
  "kids-family": Baby,
  "wedding-events": Heart,
  "personal-planners": NotebookPen,
  "creator-resources": Brush,
  "photography-video": Camera,
  "audio-sound-effects": Music,
  "3d-stl-models": Box,
  "svg-craft-files": Scissors,
  "ui-ux-kits": MonitorSmartphone,
  "developer-products": Code2,
  "business-documents": FileText,
  "freelancer-resources": Users,
  "premium-bundles": Package,
}

export function getCategoryIcon(value: string | null | undefined): LucideIcon {
  if (!value) return Package
  const key = value.toLowerCase()
  return categoryIconMap[key] ?? Package
}
