// Self-contained CRC-32 (no dependency on node:zlib's `crc32`, which only
// exists on Node.js v22.2+ — Vercel's production runtime may be on an older
// LTS version, and calling a missing function there crashes the import
// Server Action with a masked "Server Components render" error).
const CRC_TABLE = (() => {
  const table = new Uint32Array(256)
  for (let n = 0; n < 256; n++) {
    let c = n
    for (let k = 0; k < 8; k++) {
      c = c & 1 ? (0xedb88320 ^ (c >>> 1)) : c >>> 1
    }
    table[n] = c
  }
  return table
})()

function crc32(buf: Buffer): number {
  let crc = 0xffffffff
  for (let i = 0; i < buf.length; i++) {
    crc = CRC_TABLE[(crc ^ buf[i]) & 0xff] ^ (crc >>> 8)
  }
  return (crc ^ 0xffffffff) >>> 0
}

// Builds a minimal, valid, uncompressed (stored) ZIP file containing a single
// README so an imported product always has a real downloadable .zip attached
// and can be published immediately. This lets the full purchase -> entitlement
// -> download flow be tested end-to-end before the real package is uploaded to
// replace it in the admin product editor.
export function createPlaceholderZip(productName: string): Buffer {
  const fileName = "README.txt"
  const content = Buffer.from(
    `${productName}\n\n` +
      `This is a placeholder package created automatically during import.\n` +
      `Replace this file with the real product package in the admin product\n` +
      `editor before announcing this product to customers.\n\n` +
      `Generated by DistroSource admin import tool.\n`,
    "utf-8",
  )

  const now = new Date()
  const dosTime = (now.getHours() << 11) | (now.getMinutes() << 5) | (now.getSeconds() >> 1)
  const dosDate = ((now.getFullYear() - 1980) << 9) | ((now.getMonth() + 1) << 5) | now.getDate()
  const crc = crc32(content)
  const nameBuf = Buffer.from(fileName, "utf-8")

  const localHeader = Buffer.alloc(30)
  localHeader.writeUInt32LE(0x04034b50, 0)
  localHeader.writeUInt16LE(20, 4)
  localHeader.writeUInt16LE(0, 6)
  localHeader.writeUInt16LE(0, 8)
  localHeader.writeUInt16LE(dosTime, 10)
  localHeader.writeUInt16LE(dosDate, 12)
  localHeader.writeUInt32LE(crc, 14)
  localHeader.writeUInt32LE(content.length, 18)
  localHeader.writeUInt32LE(content.length, 22)
  localHeader.writeUInt16LE(nameBuf.length, 26)
  localHeader.writeUInt16LE(0, 28)

  const localEntry = Buffer.concat([localHeader, nameBuf, content])

  const centralHeader = Buffer.alloc(46)
  centralHeader.writeUInt32LE(0x02014b50, 0)
  centralHeader.writeUInt16LE(20, 4)
  centralHeader.writeUInt16LE(20, 6)
  centralHeader.writeUInt16LE(0, 8)
  centralHeader.writeUInt16LE(0, 10)
  centralHeader.writeUInt16LE(dosTime, 12)
  centralHeader.writeUInt16LE(dosDate, 14)
  centralHeader.writeUInt32LE(crc, 16)
  centralHeader.writeUInt32LE(content.length, 20)
  centralHeader.writeUInt32LE(content.length, 24)
  centralHeader.writeUInt16LE(nameBuf.length, 28)
  centralHeader.writeUInt16LE(0, 30)
  centralHeader.writeUInt16LE(0, 32)
  centralHeader.writeUInt16LE(0, 34)
  centralHeader.writeUInt16LE(0, 36)
  centralHeader.writeUInt32LE(0, 38)
  centralHeader.writeUInt32LE(0, 42)

  const centralEntry = Buffer.concat([centralHeader, nameBuf])

  const eocd = Buffer.alloc(22)
  eocd.writeUInt32LE(0x06054b50, 0)
  eocd.writeUInt16LE(0, 4)
  eocd.writeUInt16LE(0, 6)
  eocd.writeUInt16LE(1, 8)
  eocd.writeUInt16LE(1, 10)
  eocd.writeUInt32LE(centralEntry.length, 12)
  eocd.writeUInt32LE(localEntry.length, 16)
  eocd.writeUInt16LE(0, 20)

  return Buffer.concat([localEntry, centralEntry, eocd])
}
