/**
 * Image plans — one ordered gallery per product.
 *
 * Every entry is grounded in the product's own feature list (checked against
 * lib/gaming/products.ts by the orchestrator), so nothing is pictured that
 * the product does not include. The first entry is the cover.
 *
 * Shape:  { key, label, alt, make: () => html }
 */
import { interior, exteriorScene, world } from "./scenes/three.mjs"
import { inventory, anticheatDashboard, anticheatRules, floorplan, textureSheet, beforeAfter, mcInventory, logoSystem, socialBanners, streamOverlay, playerCards } from "./scenes/ui.mjs"
import { vehicleHud, phone, mdt, dispatch, callout, garageApp, businessApp, bankApp, atm, loadingScreen } from "./scenes/ui-fivem.mjs"
import { chestGui, mcOverlay, configEditor, permissionsDashboard, violationsDashboard, audioLibrary } from "./scenes/ui-minecraft.mjs"
import { WORLDS } from "./scenes/worlds.mjs"

/* ------------------------------------------------------------ hospital */

const HOSPITAL_TRIAGE = {
  room: { w: 12, d: 9, h: 3.4, floor: "vinyl", wallColor: "#e9ede8", doors: [{ wall: "n", x: -3.5, w: 2.4, h: 2.4 }, { wall: "n", x: 3.5, w: 2.4, h: 2.4 }], windows: [{ wall: "e", x: -2, w: 2.2 }, { wall: "e", x: 1.5, w: 2.2 }] },
  daylight: { intensity: 1.2, pos: [7, 8, 2] },
  items: [
    { type: "hospitalBed", args: [-4.2, -0.5, 0] }, { type: "ivStand", args: [-3.5, -1.5] }, { type: "curtainRail", args: [-4.2, 1.2, 2.4, 0] },
    { type: "hospitalBed", args: [-1.4, -0.5, 0] }, { type: "ivStand", args: [-0.7, -1.5] }, { type: "curtainRail", args: [-1.4, 1.2, 2.4, 0] },
    { type: "hospitalBed", args: [1.4, -0.5, 0] }, { type: "curtainRail", args: [1.4, 1.2, 2.4, 0] },
    { type: "hospitalBed", args: [4.2, -0.5, 0] }, { type: "ivStand", args: [4.9, -1.5] },
    { type: "counter", args: [0, 3.6, Math.PI, { w: 3.2 }] }, { type: "cabinet", args: [-5.4, 3.2, Math.PI / 2, { w: 1.6 }] }, { type: "cabinet", args: [5.4, 3.2, -Math.PI / 2, { w: 1.6 }] },
    { type: "chair", args: [-0.8, 4.2, Math.PI] },
  ],
}
const HOSPITAL_SURGERY = {
  room: { w: 8, d: 7, h: 3.3, floor: "tile", wallColor: "#dfe7ea", doors: [{ wall: "s", x: 0, w: 1.8, h: 2.3 }], windows: [{ wall: "w", x: 0, w: 2.4, y0: 1.2, y1: 2.0 }] },
  items: [
    { type: "surgeryTable", args: [0, 0, 0] }, { type: "surgeryLight", args: [-0.4, 0.3] },
    { type: "cabinet", args: [-3.5, -1.5, Math.PI / 2, { w: 2.4, h: 0.95, color: 0xdfe4e8 }] }, { type: "cabinet", args: [3.5, 0.5, -Math.PI / 2, { w: 2.4, h: 0.95, color: 0xdfe4e8 }] },
    { type: "ivStand", args: [1.2, -1.2] }, { type: "desk", args: [-2.0, -2.5, 0] }, { type: "shelf", args: [-2.6, 2.9, Math.PI, { w: 1.4, h: 1.9 }] },
  ],
}
const HOSPITAL_WARD = {
  room: { w: 6, d: 16, h: 3.2, floor: "vinyl", wallColor: "#ecebe6", doors: [{ wall: "s", x: 0, w: 1.8, h: 2.3 }, { wall: "w", x: -4, w: 1.2 }, { wall: "w", x: 2, w: 1.2 }, { wall: "e", x: -1, w: 1.2 }, { wall: "e", x: 5, w: 1.2 }] },
  daylight: { intensity: 0.9, pos: [-5, 7, 3] },
  items: [
    { type: "hospitalBed", args: [-2.0, -5.5, 0] }, { type: "hospitalBed", args: [-2.0, -1.5, 0] }, { type: "hospitalBed", args: [-2.0, 2.5, 0] },
    { type: "hospitalBed", args: [2.0, -5.5, 0] }, { type: "hospitalBed", args: [2.0, -1.5, 0] }, { type: "hospitalBed", args: [2.0, 2.5, 0] },
    { type: "ivStand", args: [-1.3, -6.4] }, { type: "ivStand", args: [2.7, -2.4] }, { type: "chair", args: [-1.1, 0.4, Math.PI / 2] }, { type: "chair", args: [1.1, 4.4, -Math.PI / 2] },
    { type: "counter", args: [0, -7.4, 0, { w: 2.4 }] }, { type: "plant", args: [2.6, 6.9] },
  ],
}
const HOSPITAL_PLAN_ROOMS = [
  { x: -8, z: -6, w: 12, d: 9, color: 0xdbe7ee, label: "Triage", doors: [{ x: -3.5, z: -4.5, w: 2.4 }, { x: 3.5, z: -4.5, w: 2.4 }], furniture: [{ x: -4.2, z: -1, w: 0.95, d: 2 }, { x: -1.4, z: -1, w: 0.95, d: 2 }, { x: 1.4, z: -1, w: 0.95, d: 2 }, { x: 4.2, z: -1, w: 0.95, d: 2 }, { x: 0, z: 3.6, w: 3.2, d: 0.7, color: 0x6f7c8a }] },
  { x: 5, z: -6.5, w: 8, d: 7, color: 0xe3ecef, label: "Surgery", doors: [{ x: 0, z: 3.5, w: 1.8 }], furniture: [{ x: 0, z: 0, w: 0.6, d: 2, color: 0x4f5c69 }] },
  { x: 13, z: -6.5, w: 7, d: 7, color: 0xe3ecef, label: "Imaging", doors: [{ x: -3.5, z: 0, w: 1.4 }], furniture: [{ x: 0.5, z: -0.5, w: 2.2, d: 1.6, color: 0x7d8794 }] },
  { x: -12, z: 7, w: 6, d: 16, color: 0xeaeae4, label: "Ward B", doors: [{ x: 0, z: 8, w: 1.8 }], furniture: [{ x: -2, z: -5.5, w: 0.95, d: 2 }, { x: -2, z: -1.5, w: 0.95, d: 2 }, { x: -2, z: 2.5, w: 0.95, d: 2 }, { x: 2, z: -5.5, w: 0.95, d: 2 }, { x: 2, z: -1.5, w: 0.95, d: 2 }, { x: 2, z: 2.5, w: 0.95, d: 2 }] },
  { x: -3, z: 8, w: 10, d: 4, color: 0xf0efe9, label: "Corridor", doors: [{ x: -5, z: 0, w: 1.4 }, { x: 5, z: 0, w: 1.4 }] },
  { x: 6, z: 6, w: 7, d: 8, color: 0xdde3e8, label: "Morgue", doors: [{ x: 0, z: -4, w: 1.4 }], furniture: [{ x: -1.5, z: 0, w: 0.8, d: 2, color: 0x8894a0 }, { x: 1.5, z: 0, w: 0.8, d: 2, color: 0x8894a0 }] },
  { x: 13.5, z: 6, w: 7, d: 8, color: 0xe6e9e2, label: "Pharmacy", doors: [{ x: -3.5, z: 0, w: 1.4 }], furniture: [{ x: 0, z: -2.5, w: 4.5, d: 0.6, color: 0x9aa5b1 }, { x: 0, z: 2, w: 4.5, d: 0.6, color: 0x9aa5b1 }] },
]

/* ------------------------------------------------------ city interiors */

const APARTMENT = {
  room: { w: 9, d: 7, h: 2.8, floor: "wood", wallColor: "#ece6da", ceiling: "#f4f1ea", panels: false, doors: [{ wall: "s", x: -3, w: 1.0 }], windows: [{ wall: "n", x: -1.5, w: 2.6, y0: 0.9, y1: 2.3 }, { wall: "n", x: 2.2, w: 1.6, y0: 0.9, y1: 2.3 }] },
  daylight: { intensity: 2.8, pos: [3, 6, -8], hemi: 0.75 },
  items: [{ type: "sofa", args: [-1.5, 1.2, Math.PI] }, { type: "table", args: [-1.5, -0.4, 0, { w: 1.2, d: 0.6, h: 0.42 }] }, { type: "shelf", args: [3.9, -1.5, -Math.PI / 2, { w: 1.6, h: 1.9 }] }, { type: "plant", args: [-3.9, -2.8] }, { type: "table", args: [2.4, 2.2, 0, { w: 1.4, d: 0.8 }] }, { type: "chair", args: [2.4, 2.9, Math.PI, 0x5a4a3a] }, { type: "chair", args: [2.4, 1.5, 0, 0x5a4a3a] }],
}
const RETAIL = {
  room: { w: 11, d: 8, h: 3.2, floor: "tile", wallColor: "#e8e8e8", doors: [{ wall: "s", x: 0, w: 2.2, h: 2.4 }], windows: [{ wall: "s", x: -3.6, w: 2.6, y0: 0.6, y1: 2.6 }, { wall: "s", x: 3.6, w: 2.6, y0: 0.6, y1: 2.6 }] },
  daylight: { intensity: 1.4, pos: [2, 7, 9] },
  items: [{ type: "counter", args: [3.2, -2.6, 0, { w: 2.8 }] }, { type: "shelf", args: [-4.0, -1.0, Math.PI / 2, { w: 2.6, h: 2.0 }] }, { type: "shelf", args: [-4.0, 2.0, Math.PI / 2, { w: 2.6, h: 2.0 }] }, { type: "shelf", args: [-0.5, -2.8, 0, { w: 2.4, h: 2.0 }] }, { type: "shelf", args: [0.5, 1.0, 0, { w: 2.0, h: 1.6 }] }, { type: "crate", args: [4.4, 2.6, 0.3] }, { type: "crate", args: [4.9, 2.1, 0.8, 0.5] }],
}
const NIGHTCLUB = {
  room: { w: 14, d: 10, h: 4.2, floor: "concrete", wallColor: "#2a2330", ceiling: "#17131c", panels: false, doors: [{ wall: "s", x: -5, w: 1.6, h: 2.4 }] },
  items: [{ type: "bar", args: [4.5, -3.2, 0, { w: 4.2, color: 0x3a2a44 }] }, { type: "sofa", args: [-5.2, 3.0, Math.PI / 2, 0x4a2a5a] }, { type: "sofa", args: [-5.2, -1.0, Math.PI / 2, 0x4a2a5a] }, { type: "table", args: [-4.2, 3.0, 0, { w: 0.7, d: 0.7, h: 0.5, wood: false }] }, { type: "table", args: [-4.2, -1.0, 0, { w: 0.7, d: 0.7, h: 0.5, wood: false }] }, { type: "sofa", args: [5.8, 3.4, -Math.PI / 2, 0x4a2a5a] }],
  club: true,
}

/* ------------------------------------------------------------- plans */

export const PLANS = {
  "hospital-mlo": [
    { key: "cover", label: "Emergency entrance", alt: "Hospital emergency entrance with ambulance bays and canopy", make: () => exteriorScene({ sky: 0xb9d3ea, items: [`buildingBlock(s,0,-14,{w:30,d:14,h:12,rows:3,cols:9,canopy:true});`, `buildingBlock(s,-24,-10,{w:14,d:10,h:7,rows:2,cols:4});`, `helipad(s,0,12.06,-14,3.6);`, `vehicle(s,"van",-5.5,-4.2,0.15,{color:0xf4f4f2,stripe:"#c8202a",type:"ems",unit:"A-12"});`, `vehicle(s,"van",1.5,-4.4,-0.05,{color:0xf4f4f2,stripe:"#c8202a",type:"ems",unit:"A-07"});`, `props.bollard(s,-9,-5);props.bollard(s,-9,-2.6);props.bollard(s,9.5,-5);props.bollard(s,9.5,-2.6);`, `props.tree(s,-15,2,1.2);props.tree(s,16,3,1.1);props.tree(s,22,-2,1.3);`], view: { pos: [18, 6.5, 16], look: [-1, 3.2, -8], fov: 44 } }) },
    { key: "gallery-01", label: "Triage bays", alt: "Triage area with four curtained treatment bays opening from the ambulance doors", make: () => interior({ spec: HOSPITAL_TRIAGE, view: { pos: [-4.6, 1.75, 3.5], look: [1.2, 1.05, -1.8], fov: 56 }, sign: { text: "TRIAGE", at: [0, 2.75, -4.42], opts: { w: 1.6, h: 0.4 } } }) },
    { key: "gallery-02", label: "Surgery", alt: "Operating theatre with surgical table, overhead light and supply cabinets", make: () => interior({ spec: HOSPITAL_SURGERY, view: { pos: [3.4, 1.9, 3.6], look: [-0.3, 1.0, -0.2], fov: 50 } }) },
    { key: "gallery-03", label: "Ward B", alt: "Six-bed ward with a nurse station at the end", make: () => interior({ spec: HOSPITAL_WARD, view: { pos: [0.2, 1.65, 7.4], look: [0, 1.1, -6], fov: 55 }, sign: { text: "WARD B", at: [0, 2.7, -7.92], opts: { w: 1.6, h: 0.4 } } }) },
    { key: "gallery-04", label: "Rooftop helipad", alt: "Rooftop helipad with perimeter lights and plant rooms", make: () => exteriorScene({ sky: 0xa9c8e6, items: [`buildingBlock(s,0,0,{w:30,d:14,h:12,rows:3,cols:9});`, `helipad(s,0,12.06,0,3.8);`, `{const g=new THREE.Group();g.position.set(0,12,0);g.add(box(2.2,1.4,1.6,mat.std(0x9aa3ad),-11,0.7,4));g.add(box(0.9,2.2,0.9,mat.std(0xb8bcc2),11.5,1.1,-4.5));s.add(g);}`, `buildingBlock(s,-40,-30,{w:20,d:16,h:20,rows:5,cols:6});buildingBlock(s,36,-34,{w:24,d:18,h:16,rows:4,cols:7});`], view: { pos: [-9, 15.2, 11], look: [1, 12, -1], fov: 46 }, daylight: { intensity: 2.6, pos: [12, 22, 10], size: 40, hemi: 0.7 } }) },
    { key: "gallery-05", label: "Floor plan", alt: "Ground floor plan showing triage, surgery, imaging, ward, morgue and pharmacy", make: () => floorplan({ title: "Ground floor", rooms: HOSPITAL_PLAN_ROOMS }) },
  ],

  "premium-city-mlo-pack": [
    { key: "cover", label: "Apartment living room", alt: "Furnished apartment living room with daylight from the street windows", make: () => interior({ spec: APARTMENT, view: { pos: [3.4, 1.6, 2.6], look: [-1.2, 1.0, -1.6], fov: 54 } }) },
    { key: "gallery-01", label: "Retail unit", alt: "Retail shop floor with shelving, counter and shopfront glazing", make: () => interior({ spec: RETAIL, view: { pos: [3.8, 1.7, 3.2], look: [-1.5, 1.0, -1.2], fov: 56 } }) },
    { key: "gallery-02", label: "Nightclub", alt: "Nightclub interior with bar, booths and dance floor", make: () => interior({ spec: NIGHTCLUB, view: { pos: [-5.5, 1.8, 4.2], look: [2.5, 1.2, -2.0], fov: 60 } }) },
    { key: "gallery-03", label: "Apartment detail", alt: "Apartment dining corner with table, chairs and shelving", make: () => interior({ spec: APARTMENT, view: { pos: [-2.6, 1.5, 3.0], look: [2.6, 1.0, 1.4], fov: 50 } }) },
    { key: "gallery-04", label: "Retail stockroom side", alt: "Retail unit viewed from the counter toward the stock shelving", make: () => interior({ spec: RETAIL, view: { pos: [3.0, 1.6, -2.0], look: [-3.5, 1.0, 1.5], fov: 58 } }) },
  ],

  "premium-inventory-interface": [
    { key: "cover", label: "Player inventory", alt: "Player inventory grid with weight bar, hotbar and item details", make: () => inventory() },
    { key: "gallery-01", label: "Vehicle trunk", alt: "Player inventory beside a vehicle trunk container", make: () => inventory({ view: "trunk" }) },
    { key: "gallery-02", label: "config.lua", alt: "Slots, weight, hotbar keybinds and the framework bridge, all in one config", make: () => configEditor({"filename":"config.lua","title":"Premium Inventory Interface","activeLine":5,"tree":[["resources",0,false,true],["ds_inventory",1,false,true],["fxmanifest.lua",2,false],["config.lua",2,true],["bridge",2,false,true],["esx.lua",3,false],["qb.lua",3,false],["html",2,false,true],["images",3,false,true]],"lines":[[["Config = {}","val"]],[["Config.Framework = ","key"],["'auto'","str"],["      -- 'esx' | 'qb' | 'auto' (see bridge/)","cmt"]],[["Config.Slots = ","key"],["30","num"]],[["Config.MaxWeight = ","key"],["40.0","num"],["         -- kg; the bar turns red above this","cmt"]],[["Config.Hotbar = { slots = ","key"],["5","num"],[", keys = ","key"],["{ '1', '2', '3', '4', '5' }","str"],[" }","val"]],[["Config.SplitKey = ","key"],["'LSHIFT'","str"],["   -- shift-drag splits a stack","cmt"]],[["Config.Views = {","sec"]],[["  trunk     = { slots = ","key"],["40","num"],[", maxWeight = ","key"],["120.0","num"],[" },","val"]],[["  container = { slots = ","key"],["20","num"],[", maxWeight = ","key"],["60.0","num"],[" },","val"]],[["  shop      = { slots = ","key"],["30","num"],[", buyKey = ","key"],["'E'","str"],[" },","val"]],[["}","sec"]],[["Config.Metadata = { durability = ","key"],["true","bool"],[", quality = ","key"],["true","bool"],[" }","val"]],[["Config.Images = ","key"],["'html/images/'","str"],["   -- starter set included; add your own by item name","cmt"]]]}) },
    { key: "gallery-03", label: "Shop view", alt: "Player inventory beside a shop stock view", make: () => inventory({ view: "shop" }) },
  ],

  "emergency-vehicle-pack": [
    { key: "cover", label: "Fleet lineup", alt: "Police sedan, police SUV, ambulance and fire engine lined up outside a station", make: () => exteriorScene({ sky: 0xc4d8ea, items: [`vehicle(s,"sedan",-9,0,0,{color:0x1a1c1f,stripe:"#e8e8e8",unit:"104",type:"police"});`, `vehicle(s,"suv",-3,0,0,{color:0xf2f2f0,stripe:"#1f4e79",unit:"215",type:"police"});`, `vehicle(s,"van",3.4,0,0,{color:0xf4f4f2,stripe:"#c8202a",unit:"A-12",type:"ems"});`, `vehicle(s,"truck",11,0,0,{color:0xc8202a,stripe:"#f2d55c",unit:"E-3",type:"fire"});`, `buildingBlock(s,0,-22,{w:60,d:14,h:8,rows:2,cols:14});props.tree(s,-26,-10,1.3);props.tree(s,28,-9,1.2);`], view: { pos: [1, 3.4, 24.5], look: [1, 1.2, 0], fov: 44 } }) },
    { key: "gallery-01", label: "Police sedan", alt: "Marked police sedan with light bar and unit number 104", make: () => exteriorScene({ sky: 0xbfd3e6, items: [`vehicle(s,"sedan",0,0,0.55,{color:0x1a1c1f,stripe:"#e8e8e8",unit:"104",type:"police"});`, `buildingBlock(s,-6,-18,{w:40,d:14,h:9,rows:2,cols:10});props.tree(s,14,-8,1.2);props.bollard(s,6,4);`], view: { pos: [5.4, 1.6, 5.2], look: [0, 0.9, 0], fov: 40 } }) },
    { key: "gallery-02", label: "Fire engine", alt: "Fire engine with equipment body and warning lights", make: () => exteriorScene({ sky: 0xc1d5e8, items: [`vehicle(s,"truck",0,0,0.5,{color:0xc8202a,stripe:"#f2d55c",unit:"E-3",type:"fire"});`, `buildingBlock(s,-4,-20,{w:44,d:14,h:9,rows:2,cols:11});props.tree(s,-18,-6,1.3);`], view: { pos: [9, 2.6, 8.5], look: [0, 1.4, 0], fov: 42 } }) },
    { key: "gallery-03", label: "Ambulance", alt: "Ambulance with patient box body and red livery", make: () => exteriorScene({ sky: 0xc1d5e8, items: [`vehicle(s,"van",0,0,-0.6,{color:0xf4f4f2,stripe:"#c8202a",unit:"A-12",type:"ems"});`, `buildingBlock(s,4,-19,{w:40,d:14,h:10,rows:2,cols:10,canopy:true});props.bollard(s,-6,4);props.bollard(s,-6,1.5);`], view: { pos: [-7, 2.2, 7], look: [0, 1.2, 0], fov: 42 } }) },
    { key: "gallery-04", label: "Night lighting", alt: "Two police units at night with light bars active under street lighting", make: () => exteriorScene({ sky: 0x0b1220, daylight: { intensity: 0.35, color: 0x9fb4d8, pos: [-6, 12, 8], size: 24, hemi: 0.18 }, items: [`vehicle(s,"sedan",-2.5,0,0.35,{color:0x1a1c1f,stripe:"#e8e8e8",unit:"104",type:"police"});vehicle(s,"suv",3.5,-2,0.2,{color:0xf2f2f0,stripe:"#1f4e79",unit:"215",type:"police"});`, `{for(const [x,z,c] of [[-2.7,0.9,0xff2a1f],[-1.9,0.9,0x2a6dff],[3.3,-1.1,0xff2a1f],[4.1,-1.1,0x2a6dff]]){const l=new THREE.PointLight(c,14,8,1.4);l.position.set(x,1.9,z);s.add(l);}}`, `{for(const x of [-14,-4,6,16]){s.add(cyl(0.08,0.1,7,mat.std(0x3a3d42),x,3.5,-9,8));const l=new THREE.PointLight(0xffd9a0,34,22,1.6);l.position.set(x,6.6,-9);s.add(l);s.add(box(0.5,0.16,0.5,mat.emissive(0xffd9a0,3),x,6.9,-9,false));}}`, `buildingBlock(s,0,-20,{w:44,d:14,h:10,rows:2,cols:12});`], view: { pos: [6, 2.2, 9], look: [0, 1.0, -1], fov: 44 } }) },
    { key: "gallery-05", label: "Livery detail", alt: "Close view of the police SUV livery stripe and unit number", make: () => exteriorScene({ sky: 0xc4d8ea, items: [`vehicle(s,"suv",0,0,1.1,{color:0xf2f2f0,stripe:"#1f4e79",unit:"215",type:"police"});`, `buildingBlock(s,-8,-16,{w:36,d:12,h:8,rows:2,cols:9});`], view: { pos: [2.6, 1.3, 4.6], look: [0.4, 0.9, 0.4], fov: 36 } }) },
  ],

  "fivem-anticheat-suite": [
    { key: "cover", label: "Live events", alt: "Anticheat admin dashboard showing live detection events with scores and actions", make: () => anticheatDashboard() },
    { key: "gallery-01", label: "Rules", alt: "Rule configuration with per-check sensitivity, scores and staff bypass", make: () => anticheatRules() },
    { key: "gallery-02", label: "Tuning config", alt: "The default rule set with scores and the auto-action threshold, tuned before enforcing", make: () => configEditor({"filename":"config.lua","title":"FiveM Anticheat Suite","activeLine":3,"tree":[["resources",0,false,true],["ds_anticheat",1,false,true],["fxmanifest.lua",2,false],["config.lua",2,true],["rules",2,false,true],["default.lua",3,false],["sql",2,false,true],["schema.sql",3,false],["TUNING.md",2,false]],"lines":[[["-- Run in 'notify' for a week and read the log before switching to 'enforce'.","cmt"]],[["Config = {}","val"]],[["Config.Mode = ","key"],["'notify'","str"],["             -- 'notify' | 'enforce'","cmt"]],[["Config.StaffBypassAce = ","key"],["'ds.staff'","str"]],[["Config.AutoAction = { threshold = ","key"],["90","num"],[", action = ","key"],["'kick'","str"],[", cooldown = ","key"],["300","num"],[" }","val"]],[["Config.Checks = {","sec"]],[["  eventValidation = { score = ","key"],["70","num"],[", enabled = ","key"],["true","bool"],[" },","val"]],[["  teleportDelta   = { score = ","key"],["85","num"],[", maxMetres = ","key"],["120","num"],[", window = ","key"],["1.0","num"],[" },","val"]],[["  resourceHash    = { score = ","key"],["90","num"],[", enabled = ","key"],["true","bool"],[" },","val"]],[["  injection       = { score = ","key"],["95","num"],[", enabled = ","key"],["true","bool"],[" },","val"]],[["  eventRate       = { score = ","key"],["40","num"],[", perSecond = ","key"],["25","num"],[" },","val"],["   -- inventory:move spam","cmt"]],[["}","sec"]],[["Config.Log = { retainDays = ","key"],["30","num"],[", webhook = ","key"],["''","str"],[" }","val"]]]}) },
  ],

  "medieval-spawn-map": [
    { key: "cover", label: "Town overview", alt: "Aerial view of the walled medieval spawn town with towers and market square", make: () => world({ preset: "medievalTown", sky: "day", view: { pos: [46, 34, 52], look: [0, 8, 0], fov: 55 } }) },
    { key: "gallery-01", label: "Market square", alt: "Market square with four covered stalls at ground level", make: () => world({ preset: "medievalTown", sky: "day", view: { pos: [21, 10.5, 1.5], look: [0, 8.5, -1], fov: 62 } }) },
    { key: "gallery-02", label: "South gate", alt: "Approach to the south gate along the cobblestone road", make: () => world({ preset: "medievalTown", sky: "day", view: { pos: [3, 10, 40], look: [0, 9, 10], fov: 62 } }) },
    { key: "gallery-03", label: "Portal hall", alt: "Portal hall on the north side with six labelled destinations", make: () => world({ preset: "medievalTown", sky: "day", view: { pos: [-4, 10.5, -10], look: [0, 10, -20], fov: 64 } }) },
    { key: "gallery-04", label: "Night", alt: "The spawn town at night lit by torches", make: () => world({ preset: "medievalTown", sky: "night", night: true, exposure: 1.7, view: { pos: [40, 26, 44], look: [0, 8, 0], fov: 56 } }) },
  ],

  "premium-resource-pack": [
    { key: "cover", label: "Texture sheet", alt: "Sheet of 32x block textures drawn to a single palette", make: () => textureSheet({ size: 32, title: "32× texture set" }) },
    { key: "gallery-01", label: "Before and after", alt: "Side-by-side comparison of default 16x textures and the pack's 32x textures", make: () => beforeAfter({ size: 32 }) },
    { key: "gallery-02", label: "Inventory skin", alt: "Survival inventory GUI using the pack's matching UI skin", make: () => mcInventory() },
    { key: "gallery-03", label: "In the world", alt: "Blocks from the pack in a built world at ground level", make: () => world({ preset: "medievalTown", sky: "day", view: { pos: [-21, 10.5, -1.5], look: [0, 8.5, 1], fov: 62 } }) },
  ],

  "esports-team-brand-kit": [
    { key: "cover", label: "Logo system", alt: "Logo system with primary lockup, compact mark, icon sizes and palette", make: () => logoSystem() },
    { key: "gallery-01", label: "Social layouts", alt: "Social media banners at current platform sizes", make: () => socialBanners() },
    { key: "gallery-02", label: "Stream overlay", alt: "Broadcast overlay with team scoreboard, camera frame and sponsor slots over gameplay", make: () => streamOverlay() },
    { key: "gallery-03", label: "Player cards", alt: "Player card and roster templates", make: () => playerCards() },
  ],

  /* ------------------------------------------- batch 2: FiveM UI + systems */

  "advanced-vehicle-hud": [
    { key: "cover", label: "In vehicle", alt: "Vehicle HUD cluster with speed, gear, fuel, engine and body condition while driving", make: () => vehicleHud({ view: "driving" }) },
    { key: "gallery-01", label: "Night driving", alt: "The HUD cluster at night", make: () => vehicleHud({ view: "night" }) },
    { key: "gallery-02", label: "HUD settings", alt: "In-game settings for cluster scale, position, opacity, units and element visibility", make: () => vehicleHud({ view: "config" }) },
    { key: "gallery-03", label: "On foot", alt: "Vehicle cluster hidden automatically on foot, leaving only status and money", make: () => vehicleHud({ view: "onfoot" }) },
    { key: "gallery-04", label: "config.lua", alt: "The documented config with per-element position, scale, visibility and units", make: () => configEditor({"filename":"config.lua","title":"Advanced Vehicle HUD","activeLine":4,"tree":[["resources",0,false,true],["ds_hud",1,false,true],["fxmanifest.lua",2,false],["config.lua",2,true],["themes",2,false,true],["default.json",3,false],["slate.json",3,false],["html",2,false,true]],"lines":[[["-- Every element can be moved, scaled or hidden here. Nothing needs a rebuild.","cmt"]],[["Config = {}","val"]],[["Config.Units = ","key"],["'mph'","str"],["            -- 'mph' | 'kmh'","cmt"]],[["Config.Theme = ","key"],["'default'","str"],["        -- themes/*.json","cmt"]],[["Config.HideOnFoot = ","key"],["true","bool"]],[["Config.HideInCutscene = ","key"],["true","bool"]],[["Config.Elements = {","sec"]],[["  speed    = { x = ","key"],["0.86","num"],[", y = ","key"],["0.88","num"],[", scale = ","key"],["1.0","num"],[", show = ","key"],["true","bool"],[" },","val"]],[["  fuel     = { x = ","key"],["0.93","num"],[", y = ","key"],["0.88","num"],[", scale = ","key"],["1.0","num"],[", show = ","key"],["true","bool"],[" },","val"]],[["  gear     = { x = ","key"],["0.90","num"],[", y = ","key"],["0.93","num"],[", scale = ","key"],["0.9","num"],[", show = ","key"],["true","bool"],[" },","val"]],[["  seatbelt = { x = ","key"],["0.86","num"],[", y = ","key"],["0.78","num"],[", scale = ","key"],["1.0","num"],[", show = ","key"],["true","bool"],[" },","val"]],[["  status   = { x = ","key"],["0.03","num"],[", y = ","key"],["0.92","num"],[", scale = ","key"],["1.0","num"],[", show = ","key"],["true","bool"],[" },","val"]],[["  money    = { x = ","key"],["0.93","num"],[", y = ","key"],["0.05","num"],[", scale = ","key"],["1.0","num"],[", show = ","key"],["true","bool"],[" },","val"]],[["}","sec"]],[["Config.Seatbelt = { warnAbove = ","key"],["30","num"],[", ejectAbove = ","key"],["120","num"],[" }","val"],["   -- in Config.Units","cmt"]]]}) },
  ],

  "modern-phone-interface": [
    { key: "cover", label: "Home screen", alt: "Phone home screen with app grid, notification and dock", make: () => phone({ app: "home" }) },
    { key: "gallery-01", label: "Messages", alt: "Messages app with conversation list", make: () => phone({ app: "messages" }) },
    { key: "gallery-02", label: "Bank app", alt: "Bank app with balance, actions and recent transactions", make: () => phone({ app: "bank" }) },
    { key: "gallery-03", label: "App SDK example", alt: "The worked example: a third-party app registers with the phone without editing the core", make: () => configEditor({"filename":"example_app.lua","title":"Modern Phone Interface","activeLine":3,"tree":[["resources",0,false,true],["ds_phone",1,false,true],["fxmanifest.lua",2,false],["config.lua",2,false],["themes",2,false,true],["dark.css",3,false],["light.css",3,false],["sdk",2,false,true],["README.md",3,false],["example_app.lua",3,true],["example_app.html",3,false]],"lines":[[["-- A third-party app: registers itself, keeps its own state, gets a tray icon.","cmt"]],[["-- Nothing in ds_phone changes.","cmt"]],[["exports.ds_phone:registerApp({","val"]],[["  id      = ","key"],["'garage'","str"],[",","val"]],[["  name    = ","key"],["'Garage'","str"],[",","val"]],[["  icon    = ","key"],["'nui://ds_garage/html/icon.svg'","str"],[",","val"]],[["  page    = ","key"],["'nui://ds_garage/html/app.html'","str"],[",","val"]],[["  keepState = ","key"],["true","bool"],[",         -- survives switching apps","cmt"]],[["  notify  = function(count)","val"]],[["    return count > ","val"],["0","num"],[" and (count .. ","val"],["' vehicle(s) ready'","str"],[") or nil","val"]],[["  end,","val"]],[["})","val"]],[["","val"]],[["RegisterNetEvent(","val"],["'garage:ready'","str"],[", function(plate)","val"]],[["  exports.ds_phone:notify(","val"],["'garage'","str"],[", ","val"],["'Vehicle ready: '","str"],[" .. plate)","val"]],[["end)","val"]]]}) },
    { key: "gallery-04", label: "Light theme", alt: "Home screen in the light theme", make: () => phone({ app: "home", theme: "light" }) },
  ],

  "emergency-services-ui-pack": [
    { key: "cover", label: "MDT · person records", alt: "Mobile data terminal with searchable person records and a selected record", make: () => mdt({ tab: "persons" }) },
    { key: "gallery-01", label: "Dispatch board", alt: "Dispatch board with unit status and active callouts", make: () => dispatch() },
    { key: "gallery-02", label: "Callout panel", alt: "In-game callout panel with priority, location and responding units", make: () => callout() },
    { key: "gallery-03", label: "MDT · vehicle records", alt: "Vehicle records with plate, owner, insurance and flags", make: () => mdt({ tab: "vehicles" }) },
  ],

  "advanced-garage-system": [
    { key: "cover", label: "Stored vehicles", alt: "Garage menu listing stored vehicles with condition, fuel and status", make: () => garageApp({ tab: "vehicles" }) },
    { key: "gallery-01", label: "Impound", alt: "Impound lot with retrieval fee and vehicle state", make: () => garageApp({ tab: "impound" }) },
    { key: "gallery-02", label: "Admin recovery", alt: "Admin tool for recovering vehicles stranded outside any garage", make: () => garageApp({ tab: "admin" }) },
    { key: "gallery-03", label: "Garage entrance", alt: "Vehicles parked at a garage entrance", make: () => exteriorScene({ sky: 0xc1d5e8, items: [`buildingBlock(s,0,-12,{w:26,d:12,h:6,rows:1,cols:6});`, `vehicle(s,"sedan",-6,-2,0.1,{color:0x3d5a80,lightbar:false});vehicle(s,"suv",0.5,-2.4,-0.05,{color:0x8a8f96,lightbar:false});vehicle(s,"sedan",7,-2,0.15,{color:0xc44536,lightbar:false});`, `props.bollard(s,-11,2);props.bollard(s,11,2);props.tree(s,-16,-4,1.2);props.tree(s,17,-3,1.1);`], view: { pos: [10, 3.2, 12], look: [0, 1.2, -3], fov: 44 } }) },
  ],

  "business-management-system": [
    { key: "cover", label: "Staff", alt: "Business staff list with roles, wages and duty status", make: () => businessApp({ tab: "staff" }) },
    { key: "gallery-01", label: "Stock", alt: "Stock levels with reorder thresholds and low-stock alerts", make: () => businessApp({ tab: "stock" }) },
    { key: "gallery-02", label: "Books", alt: "Owner books showing revenue, wages, stock costs and payroll interval", make: () => businessApp({ tab: "books" }) },
  ],

  "banking-system": [
    { key: "cover", label: "Accounts", alt: "Bank accounts overview with personal and business balances and transaction history", make: () => bankApp({ tab: "accounts" }) },
    { key: "gallery-01", label: "Transfer", alt: "Transfer form with searchable history", make: () => bankApp({ tab: "transfer" }) },
    { key: "gallery-02", label: "Cards", alt: "Debit and business cards with freeze and lost-or-stolen actions", make: () => bankApp({ tab: "cards" }) },
    { key: "gallery-03", label: "Loans", alt: "Loans with interest, repayment schedule and progress", make: () => bankApp({ tab: "loans" }) },
    { key: "gallery-04", label: "ATM", alt: "In-game ATM screen with withdrawal limit", make: () => atm() },
  ],

  "loading-screen-pack": [
    { key: "cover", label: "Screen 1", alt: "Loading screen with rotating tip, music player and connection progress", make: () => loadingScreen({ variant: 1 }) },
    { key: "gallery-01", label: "Screen 2 · rules", alt: "Loading screen variant showing server rules", make: () => loadingScreen({ variant: 2 }) },
    { key: "gallery-02", label: "Screen 3", alt: "Loading screen variant with a different colour treatment", make: () => loadingScreen({ variant: 3 }) },
  ],

  /* ---------------------------------------- batch 3: Minecraft + audio */

  "premium-survival-spawn": [
    { key: "cover", label: "Hub overview", alt: "Aerial view of the compact survival hub with shop row, warp board and the exit path", make: () => world({ build: WORLDS.survivalHub, sky: "day", view: { pos: [34, 26, 38], look: [0, 7, 0], fov: 56 } }) },
    { key: "gallery-01", label: "Spawn platform", alt: "The spawn platform, oriented toward the exit path", make: () => world({ build: WORLDS.survivalHub, sky: "day", view: { pos: [-10, 11, 12], look: [6, 8, -2], fov: 64 } }) },
    { key: "gallery-02", label: "Shop row", alt: "The shop row of four units along the west side", make: () => world({ build: WORLDS.survivalHub, sky: "day", view: { pos: [-2, 10.5, 4], look: [-13, 9, -2], fov: 62 } }) },
    { key: "gallery-03", label: "Warp board", alt: "The warp board on the north side of the hub", make: () => world({ build: WORLDS.survivalHub, sky: "day", view: { pos: [2, 10.5, -4], look: [0, 9.5, -13], fov: 60 } }) },
    { key: "gallery-04", label: "Night", alt: "The hub at night, fully lit", make: () => world({ build: WORLDS.survivalHub, sky: "night", exposure: 1.7, view: { pos: [30, 22, 34], look: [0, 7, 0], fov: 56 } }) },
  ],

  "modern-lobby-map": [
    { key: "cover", label: "Lobby overview", alt: "Aerial view of the lobby: central hub, circular walkway with eight portal pads, leaderboard walls and the cosmetics area", make: () => world({ build: WORLDS.lobby, sky: "night", exposure: 1.6, view: { pos: [30, 26, 34], look: [0, 6, 0], fov: 56 } }) },
    { key: "gallery-01", label: "Portal walkway", alt: "Ground view along the walkway past two portal pads", make: () => world({ build: WORLDS.lobby, sky: "night", exposure: 1.6, view: { pos: [2, 9.5, 6], look: [12, 8, -6], fov: 62 } }) },
    { key: "gallery-02", label: "Leaderboard walls", alt: "The leaderboard walls on the south edge", make: () => world({ build: WORLDS.lobby, sky: "night", exposure: 1.6, view: { pos: [0, 9, 8], look: [0, 8.5, 18], fov: 62 } }) },
    { key: "gallery-03", label: "Cosmetics area", alt: "The glass-walled cosmetics area in the north-east corner", make: () => world({ build: WORLDS.lobby, sky: "night", exposure: 1.6, view: { pos: [24, 12, 0], look: [15, 6, -16], fov: 56 } }) },
  ],

  "adventure-map-collection": [
    { key: "cover", label: "Map 01 · Highlands", alt: "Aerial view of the highlands map with the objective path climbing to the boss arena", make: () => world({ build: WORLDS.adventureHighlands, sky: "dusk", view: { pos: [-20, 40, 60], look: [0, 8, -6], fov: 56 } }) },
    { key: "gallery-01", label: "Checkpoint", alt: "A checkpoint pillar on the objective path", make: () => world({ build: WORLDS.adventureHighlands, sky: "dusk", view: { pos: [-30, 14, 24], look: [-20, 11, 12], fov: 64 } }) },
    { key: "gallery-02", label: "Boss arena", alt: "The boss arena ring on the far hill with its lava core", make: () => world({ build: WORLDS.adventureHighlands, sky: "dusk", view: { pos: [8, 22, -8], look: [22, 12, -22], fov: 60 } }) },
    { key: "gallery-03", label: "Map 03 · Cavern", alt: "Inside the cavern map: pillars, lava pools and the descent ramp", make: () => world({ build: WORLDS.adventureCavern, sky: "cave", exposure: 1.8, view: { pos: [-26, 9, 14], look: [4, 4, -4], fov: 66 } }) },
    { key: "gallery-04", label: "Cavern vault", alt: "The obsidian vault at the end of the cavern", make: () => world({ build: WORLDS.adventureCavern, sky: "cave", exposure: 1.8, view: { pos: [0, 7, 4], look: [12, 4, -8], fov: 64 } }) },
  ],

  "skyblock-island-pack": [
    { key: "cover", label: "Starter island", alt: "A starter island floating in the sky with a tree, sand spit and stone outcrop", make: () => world({ build: WORLDS.skyblockStarter, sky: "day", view: { pos: [16, 16, 20], look: [0, 6, 0], fov: 54 } }) },
    { key: "gallery-01", label: "Advanced island", alt: "A grown island with a house, farm plots and a bridge to a second island", make: () => world({ build: WORLDS.skyblockAdvanced, sky: "day", view: { pos: [26, 20, 30], look: [6, 7, 0], fov: 56 } }) },
    { key: "gallery-02", label: "Nether companion", alt: "The nether companion island beside the starter island", make: () => world({ build: WORLDS.skyblockStarter, sky: "day", view: { pos: [30, 14, -6], look: [8, 5, -8], fov: 52 } }) },
    { key: "gallery-03", label: "Island at night", alt: "The advanced island at night with torches", make: () => world({ build: WORLDS.skyblockAdvanced, sky: "night", exposure: 1.7, view: { pos: [-20, 16, 22], look: [0, 8, 0], fov: 58 } }) },
  ],

  "prison-server-map": [
    { key: "cover", label: "Compound overview", alt: "Aerial view of the walled prison: cell blocks, yard, shop and PvP areas, guard tower and mine tiers", make: () => world({ build: WORLDS.prison, sky: "day", view: { pos: [50, 44, 60], look: [0, 6, 4], fov: 54 } }) },
    { key: "gallery-01", label: "Cell block", alt: "A numbered cell block with barred fronts", make: () => world({ build: WORLDS.prison, sky: "day", view: { pos: [-10, 12, -36], look: [-14, 8, -18], fov: 60 } }) },
    { key: "gallery-02", label: "Mine tiers", alt: "The mine tiers, each larger and deeper than the last", make: () => world({ build: WORLDS.prison, sky: "day", view: { pos: [-44, 22, 22], look: [-16, 4, 32], fov: 56 } }) },
    { key: "gallery-03", label: "Yard and PvP area", alt: "The yard with the separated shop and PvP areas", make: () => world({ build: WORLDS.prison, sky: "day", view: { pos: [-20, 20, 34], look: [20, 7, 12], fov: 58 } }) },
  ],

  "rpg-interface-pack": [
    { key: "cover", label: "Quest log", alt: "Quest log GUI with chapter, objectives, rewards and progress on hover", make: () => chestGui({ title: "Quest Log", rows: 3, tooltip: 1, items: [{ name: "The Harbour Contract", c1: "#c9a35a", c2: "#8a6a3a", lore: ["§Chapter 1", "Deliver 12 crates to the docks", "Reward: 120 XP · 30 coins", "Complete"] }, { name: "The Lost Caravan", c1: "#5fa8d3", c2: "#2f6a8f", lore: ["§Chapter 2", "Find the missing supplies", "Reward: 250 XP · 40 coins", "Progress: 2 / 3"], glow: true }, { name: "Wolves at the Gate", c1: "#8b8b8b", c2: "#5a5a5a", lore: ["§Chapter 2", "Clear the northern road", "Reward: 300 XP", "Progress: 0 / 8"] }, null, null, null, null, null, null, { name: "Daily · Fishing", c1: "#3ec66d", c2: "#2a8a4a", lore: ["§Daily", "Catch 10 fish", "Reward: 50 XP", "Progress: 4 / 10"] }] }) },
    { key: "gallery-01", label: "Stats and skills", alt: "Stats and skills GUI with level, XP and skill entries", make: () => chestGui({ title: "Stats & Skills", rows: 3, tooltip: 4, items: [{ name: "Combat", c1: "#c8202a", c2: "#7a1018", lore: ["Level 14", "XP 2,340 / 3,000"] }, { name: "Mining", c1: "#8b8b8b", c2: "#5a5a5a", lore: ["Level 22", "XP 8,100 / 9,500"] }, { name: "Farming", c1: "#3ec66d", c2: "#2a8a4a", lore: ["Level 9", "XP 610 / 1,200"] }, { name: "Fishing", c1: "#5fa8d3", c2: "#2f6a8f", lore: ["Level 11", "XP 1,020 / 1,800"] }, { name: "Character", c1: "#e8b84a", c2: "#a87a2a", lore: ["§Level 18", "Health 24 · Armour 12", "Strength 7 · Agility 5", "Skill points: 2"], glow: true }, { name: "Crafting", c1: "#a8743f", c2: "#6b4a2f", lore: ["Level 6", "XP 210 / 800"] }] }) },
    { key: "gallery-02", label: "Quest tracker in game", alt: "In-game view with the quest tracker in the sidebar", make: () => mcOverlay({ tone: "day", scoreboard: { title: "Quest Tracker", rows: [["The Lost Caravan", ""], ["  Supplies found", "2/3"], ["  Return to camp", ""], ["", ""], ["Daily · Fishing", "4/10"], ["", ""], ["Level 18", "2,340 XP"]] }, chat: [`<span style="color:#55ff55">[Quest]</span> Supplies found (2/3)`, `<span style="color:#ffaa00">+40 XP</span> Combat`], hotbarSel: 2 }) },
    { key: "gallery-03", label: "Shop layout", alt: "Shop GUI with priced items", make: () => chestGui({ title: "General Store", rows: 3, tooltip: 3, items: [{ name: "Bread", c1: "#c9a35a", c2: "#8a6a3a", count: 16, lore: ["Buy: 4 coins", "Sell: 1 coin"] }, { name: "Iron Ingot", c1: "#d8d8d8", c2: "#a0a0a0", count: 8, lore: ["Buy: 22 coins", "Sell: 9 coins"] }, { name: "Torch", c1: "#e8b84a", c2: "#6b4a2f", count: 32, lore: ["Buy: 1 coin", "Sell: —"] }, { name: "Iron Pickaxe", c1: "#d8d8d8", c2: "#6b4a2f", lore: ["§Buy: 120 coins", "Sell: 40 coins", "Durability: 250 / 250", "Click to buy"], glow: true }, { name: "Oak Planks", c1: "#a8743f", c2: "#8a6a3a", count: 64, lore: ["Buy: 44 coins", "Sell: 12 coins"] }, { name: "Arrow", c1: "#b9bec6", c2: "#6b4a2f", count: 32, lore: ["Buy: 12 coins", "Sell: 3 coins"] }] }) },
  ],

  "economy-server-configuration": [
    { key: "cover", label: "Economy config", alt: "The economy configuration file open in an editor, with every value commented", make: () => configEditor({ filename: "economy.yml", title: "Economy Server Configuration", activeLine: 6, tree: [["plugins", 0, false, true], ["Economy", 1, false, true], ["economy.yml", 2, true], ["shops.yml", 2, false], ["jobs.yml", 2, false], ["sinks.yml", 2, false], ["Shop", 1, false, true], ["Jobs", 1, false, true], ["server.properties", 0, false]], lines: [[["# Tuned so currency does not inflate away in the first month.", "cmt"]], [["currency:", "sec"]], [["  symbol: ", "key"], ["'$'", "str"]], [["  starting-balance: ", "key"], ["250", "num"], ["   # low on purpose: the first job pays within 10 minutes", "cmt"]], [["", "val"]], [["shops:", "sec"]], [["  buy-margin: ", "key"], ["0.18", "num"], ["   # +18% over base; closes the raw-ore arbitrage loop", "cmt"]], [["  sell-margin: ", "key"], ["-0.12", "num"], ["  # sells 12% under base, never above buy", "cmt"]], [["  base-prices:", "key"]], [["    raw_ore: ", "key"], ["12", "num"]], [["    refined_goods: ", "key"], ["44", "num"]], [["    farm_produce: ", "key"], ["6", "num"]], [["    rare_drops: ", "key"], ["310", "num"]], [["", "val"]], [["jobs:", "sec"]], [["  payout-per-hour: ", "key"], ["420", "num"], ["   # measured against average session length", "cmt"]], [["  cap-per-day: ", "key"], ["3200", "num"]], [["", "val"]], [["sinks:", "sec"]], [["  tax-rate: ", "key"], ["0.06", "num"]], [["  land-claim-cost: ", "key"], ["1800", "num"], ["   # the top-end sink", "cmt"]], [["  repair-cost-multiplier: ", "key"], ["1.4", "num"]]] }) },
    { key: "gallery-01", label: "Shop price table", alt: "The shop price table configuration with buy and sell prices set against each other", make: () => configEditor({ filename: "shops.yml", title: "Economy Server Configuration", activeLine: 4, tree: [["plugins", 0, false, true], ["Economy", 1, false, true], ["economy.yml", 2, false], ["shops.yml", 2, true], ["jobs.yml", 2, false], ["sinks.yml", 2, false]], lines: [[["# Buy and sell prices are derived from base * margin; edit base only.", "cmt"]], [["categories:", "sec"]], [["  ores:", "key"]], [["    coal:     ", "key"], ["{ base: ", "val"], ["12", "num"], [",  buy: ", "val"], ["14", "num"], [", sell: ", "val"], ["10", "num"], [" }", "val"]], [["    iron:     ", "key"], ["{ base: ", "val"], ["28", "num"], [",  buy: ", "val"], ["33", "num"], [", sell: ", "val"], ["24", "num"], [" }", "val"]], [["    gold:     ", "key"], ["{ base: ", "val"], ["60", "num"], [",  buy: ", "val"], ["71", "num"], [", sell: ", "val"], ["52", "num"], [" }", "val"]], [["    diamond:  ", "key"], ["{ base: ", "val"], ["310", "num"], [", buy: ", "val"], ["366", "num"], [", sell: ", "val"], ["272", "num"], [" }", "val"]], [["  produce:", "key"]], [["    wheat:    ", "key"], ["{ base: ", "val"], ["6", "num"], [",   buy: ", "val"], ["7", "num"], [",  sell: ", "val"], ["5", "num"], [" }", "val"]], [["    carrot:   ", "key"], ["{ base: ", "val"], ["5", "num"], [",   buy: ", "val"], ["6", "num"], [",  sell: ", "val"], ["4", "num"], [" }", "val"]], [["  blocks:", "key"]], [["    stone:    ", "key"], ["{ base: ", "val"], ["3", "num"], [",   buy: ", "val"], ["4", "num"], [",  sell: ", "val"], ["2", "num"], [" }", "val"]], [["    oak_log:  ", "key"], ["{ base: ", "val"], ["8", "num"], [",   buy: ", "val"], ["9", "num"], [",  sell: ", "val"], ["7", "num"], [" }", "val"]]] }) },
    { key: "gallery-02", label: "Shop in game", alt: "The server shop GUI showing the configured prices", make: () => chestGui({ title: "Server Shop · Ores", rows: 2, tooltip: 3, items: [{ name: "Coal", c1: "#2a2a2a", c2: "#8b8b8b", count: 16, lore: ["Buy: $14", "Sell: $10"] }, { name: "Iron Ingot", c1: "#d8d8d8", c2: "#a0a0a0", lore: ["Buy: $33", "Sell: $24"] }, { name: "Gold Ingot", c1: "#e8b84a", c2: "#a87a2a", lore: ["Buy: $71", "Sell: $52"] }, { name: "Diamond", c1: "#7fd6e8", c2: "#3fa8c4", lore: ["§Buy: $366", "Sell: $272", "Left-click: buy 1", "Shift-click: buy 16"], glow: true }] }) },
  ],

  "minecraft-server-essentials-pack": [
    { key: "cover", label: "Ranks and permissions", alt: "Rank ladder with inheritance, permission nodes, home and warp limits", make: () => permissionsDashboard() },
    { key: "gallery-01", label: "Permissions config", alt: "The permissions configuration file, every value commented", make: () => configEditor({ filename: "permissions.yml", title: "Server Essentials Pack", activeLine: 9, tree: [["plugins", 0, false, true], ["Essentials", 1, false, true], ["permissions.yml", 2, true], ["ranks.yml", 2, false], ["moderation.yml", 2, false], ["warps.yml", 2, false]], lines: [[["# Each rank inherits the one below it. Insert a rank here; nothing else changes.", "cmt"]], [["groups:", "sec"]], [["  default:", "key"]], [["    permissions:", "key"]], [["      - ", "val"], ["essentials.home", "str"]], [["      - ", "val"], ["essentials.warp", "str"]], [["      - ", "val"], ["chat.color", "str"]], [["  member:", "key"]], [["    inherits: ", "key"], ["default", "str"]], [["    permissions:", "key"]], [["      - ", "val"], ["essentials.sethome.2", "str"], ["   # two homes; raise per rank, not globally", "cmt"]], [["      - ", "val"], ["essentials.kit.member", "str"]], [["  trusted:", "key"]], [["    inherits: ", "key"], ["member", "str"]], [["    permissions:", "key"]], [["      - ", "val"], ["essentials.sethome.4", "str"]], [["      - ", "val"], ["essentials.fly", "str"], ["   # earned, not default", "cmt"]], [["  staff:", "key"]], [["    inherits: ", "key"], ["trusted", "str"]], [["    permissions:", "key"]], [["      - ", "val"], ["essentials.kick", "str"]], [["      - ", "val"], ["essentials.mute", "str"]], [["      - ", "val"], ["essentials.vanish", "str"]]] }) },
    { key: "gallery-02", label: "Moderation config", alt: "Moderation defaults for chat cooldown, AFK and claim limits", make: () => configEditor({ filename: "moderation.yml", title: "Server Essentials Pack", activeLine: 3, tree: [["plugins", 0, false, true], ["Essentials", 1, false, true], ["permissions.yml", 2, false], ["ranks.yml", 2, false], ["moderation.yml", 2, true], ["warps.yml", 2, false]], lines: [[["# Defaults that catch the common problems on a public server.", "cmt"]], [["chat:", "sec"]], [["  cooldown-seconds: ", "key"], ["2", "num"], ["     # stops paste-spam without hurting conversation", "cmt"]], [["  caps-limit: ", "key"], ["0.6", "num"], ["         # fraction of a message allowed in caps", "cmt"]], [["  link-filter: ", "key"], ["true", "bool"]], [["afk:", "sec"]], [["  timeout-minutes: ", "key"], ["10", "num"]], [["  kick-when-full: ", "key"], ["true", "bool"]], [["claims:", "sec"]], [["  starting-blocks: ", "key"], ["8000", "num"]], [["  blocks-per-hour: ", "key"], ["200", "num"]], [["homes:", "sec"]], [["  cooldown-seconds: ", "key"], ["5", "num"]], [["  warmup-seconds: ", "key"], ["3", "num"], ["      # cancels on damage", "cmt"]], [["warps:", "sec"]], [["  public: ", "key"], ["[spawn, shop, mine, arena]", "str"]], [["  ranked: ", "key"], ["[nether, end]", "str"], ["   # trusted and above", "cmt"]]] }) },
    { key: "gallery-03", label: "In game", alt: "Rank prefixes in chat and the server sidebar", make: () => mcOverlay({ tone: "day", scoreboard: { title: "Harbour SMP", rows: [["Rank", "Trusted"], ["Balance", "$4,250"], ["Claim blocks", "8,200"], ["Homes", "3 / 4"], ["", ""], ["/warp · /home", ""]] }, chat: [`<span style="color:#e8b84a">[Staff]</span> Dana: welcome to the server!`, `<span style="color:#4a9be8">[Trusted]</span> Marcus: thanks, heading to /warp mine`, `<span style="color:#8b93a1">[Member]</span> Priya: anyone selling iron?`], actionbar: "Home set: base · 3 of 4 homes used", hotbarSel: 1 }) },
  ],

  "minecraft-anticheat-configuration": [
    { key: "cover", label: "Survival profile", alt: "Anticheat tuning for the survival profile with per-check sensitivity and notes", make: () => violationsDashboard({ profile: "survival" }) },
    { key: "gallery-01", label: "Staff notify in game", alt: "Notify-only mode: flags reach staff in chat with the check, score and violation level", make: () => mcOverlay({ tone: "day", scoreboard: { title: "Anticheat", rows: [["Mode", "notify"], ["Checks", "12"], ["Flags · 1 h", "7"], ["", ""], ["Profile", "survival"]] }, chat: [`<span style="color:#ff5555">[AC]</span> Marcus B. flagged <span style="color:#ffaa00">combat-reach</span> (3.4 blocks) VL 22`, `<span style="color:#ff5555">[AC]</span> Tom F. flagged <span style="color:#ffaa00">movement</span> on ice VL 4 · below notify threshold`, `<span style="color:#55ff55">[AC]</span> Elena B. cleared · elytra excluded`], actionbar: "Notify-only · no actions taken", hotbarSel: 0 }) },
    { key: "gallery-02", label: "Minigame profile", alt: "The minigame profile with lenient movement checks", make: () => violationsDashboard({ profile: "minigame" }) },
    { key: "gallery-03", label: "Config file", alt: "The anticheat configuration with every check documented", make: () => configEditor({ filename: "checks.yml", title: "Minecraft Anticheat Configuration", activeLine: 5, tree: [["plugins", 0, false, true], ["Anticheat", 1, false, true], ["checks.yml", 2, true], ["profiles", 2, false, true], ["survival.yml", 3, false], ["pvp.yml", 3, false], ["minigame.yml", 3, false]], lines: [[["# Run notify-only for a week before enabling actions.", "cmt"]], [["mode: ", "key"], ["notify", "str"], ["   # notify | enforce", "cmt"]], [["staff-bypass: ", "key"], ["true", "bool"]], [["checks:", "sec"]], [["  movement:", "key"]], [["    sensitivity: ", "key"], ["medium", "str"], ["   # trips on ice and boats when strict", "cmt"]], [["    vl-decay-seconds: ", "key"], ["120", "num"]], [["  combat-reach:", "key"]], [["    sensitivity: ", "key"], ["strict", "str"]], [["    ping-compensation-ms: ", "key"], ["150", "num"]], [["  autoclicker:", "key"]], [["    max-cps: ", "key"], ["16", "num"], ["   # legit players peak around 14", "cmt"]], [["  flight:", "key"]], [["    sensitivity: ", "key"], ["strict", "str"]], [["    exclude: ", "key"], ["[elytra, creative, spectator]", "str"]], [["  packet-rate:", "key"]], [["    sensitivity: ", "key"], ["lenient", "str"], ["   # high-latency regions flag falsely otherwise", "cmt"]], [["actions:", "sec"]], [["  notify-at: ", "key"], ["20", "num"]], [["  kick-at: ", "key"], ["40", "num"]], [["  tempban-at: ", "key"], ["80", "num"]]] }) },
  ],

  "ambient-music-pack": [
    { key: "cover", label: "Track library", alt: "The ambient music library with categories, track list and a waveform player", make: () => audioLibrary({ title: "Ambient Music Pack", categories: [["Exploration", 12], ["Settlement", 8], ["Tension", 6], ["Night", 4]], selected: 0, accent: "#6fb3a0", tracks: [["Ridge Line", "4:12", "Exploration"], ["Fog Over the Basin", "3:48", "Exploration"], ["Long Road East", "5:02", "Exploration"], ["Hearth", "3:20", "Settlement"], ["Market Morning", "2:58", "Settlement"], ["Something in the Dark", "3:36", "Tension"], ["Held Breath", "2:44", "Tension"], ["Lantern", "4:30", "Night"]] }) },
    { key: "gallery-01", label: "Tension tracks", alt: "The tension category selected in the library", make: () => audioLibrary({ title: "Ambient Music Pack", categories: [["Tension", 6], ["Exploration", 12], ["Settlement", 8], ["Night", 4]], selected: 5, accent: "#c46a6a", tracks: [["Ridge Line", "4:12", "Exploration"], ["Fog Over the Basin", "3:48", "Exploration"], ["Long Road East", "5:02", "Exploration"], ["Hearth", "3:20", "Settlement"], ["Market Morning", "2:58", "Settlement"], ["Something in the Dark", "3:36", "Tension"], ["Held Breath", "2:44", "Tension"], ["Lantern", "4:30", "Night"]] }) },
    { key: "gallery-02", label: "Trigger config", alt: "Biome and region trigger configuration with crossfade and minimum gap", make: () => configEditor({ filename: "triggers.yml", title: "Ambient Music Pack", activeLine: 2, tree: [["resourcepacks", 0, false, true], ["ambient-music", 1, false, true], ["pack.mcmeta", 2, false], ["assets", 2, false, true], ["plugins", 0, false, true], ["triggers.yml", 1, true]], lines: [[["playback:", "sec"]], [["  crossfade-seconds: ", "key"], ["4", "num"]], [["  minimum-gap-seconds: ", "key"], ["90", "num"], ["   # music should not run constantly", "cmt"]], [["  volume: ", "key"], ["0.7", "num"]], [["biomes:", "sec"]], [["  forest: ", "key"], ["exploration", "str"]], [["  plains: ", "key"], ["exploration", "str"]], [["  mountains: ", "key"], ["exploration", "str"]], [["  village: ", "key"], ["settlement", "str"]], [["  dark_forest: ", "key"], ["tension", "str"]], [["  deep_dark: ", "key"], ["tension", "str"]], [["time:", "sec"]], [["  night: ", "key"], ["night", "str"], ["   # overrides biome after dusk", "cmt"]], [["regions:", "sec"]], [["  spawn: ", "key"], ["settlement", "str"]], [["  arena: ", "key"], ["tension", "str"]]] }) },
  ],

  "custom-enchantments-plugin": [
    { key: "cover", label: "Enchanter GUI", alt: "The enchanter GUI with tiered enchantments and a hover tooltip showing chance, items and conflicts", make: () => chestGui({ title: "Enchanter · Epic", rows: 3, tooltip: 1, items: [{ name: "Life Steal II", c1: "#c8202a", c2: "#7a1018", lore: ["§Epic · 11%", "Heals 6% of damage dealt", "Applies to: swords, axes", "Conflicts: Vampire", "Cost: 34 levels"] }, { name: "Tempest III", c1: "#5fa8d3", c2: "#2f6a8f", lore: ["§Epic · 11%", "Lightning on critical hits", "Applies to: swords, bows", "Conflicts: none", "Cost: 34 levels"], glow: true }, { name: "Excavator II", c1: "#8b8b8b", c2: "#5a5a5a", lore: ["§Epic · 11%", "Mines a 3×3 area", "Applies to: pickaxes", "Conflicts: Tunnel", "Cost: 34 levels"] }, { name: "Harvest I", c1: "#3ec66d", c2: "#2a8a4a", lore: ["§Epic · 11%", "Replants crops on harvest", "Applies to: hoes", "Cost: 34 levels"] }, { name: "Featherfoot", c1: "#e8e8e8", c2: "#a0a0a0", lore: ["§Epic · 11%", "No fall damage", "Applies to: boots", "Cost: 34 levels"] }, null, null, null, null, { name: "Common", c1: "#8b8b8b", c2: "#5a5a5a", lore: ["62% chance", "Click to switch tier"] }, { name: "Rare", c1: "#5fa8d3", c2: "#2f6a8f", lore: ["24% chance", "Click to switch tier"] }, { name: "Epic", c1: "#a05bd6", c2: "#6a2fa0", lore: ["11% chance", "Current tier"], glow: true }, { name: "Legendary", c1: "#e8b84a", c2: "#a87a2a", lore: ["3% chance", "Click to switch tier"] }], sidebar: { title: "Enchanter", rows: [["Level", "42"], ["Books", "3"], ["Tier", "Epic"]] } }) },
    { key: "gallery-01", label: "Enchantment book", alt: "An enchantment book item with its tooltip, tradeable through shops", make: () => chestGui({ title: "Enchantment Books", rows: 2, tooltip: 2, items: [{ name: "Book · Life Steal II", c1: "#c9a35a", c2: "#c8202a", lore: ["§Epic", "Apply to: swords, axes", "Tradeable"] }, { name: "Book · Excavator II", c1: "#c9a35a", c2: "#8b8b8b", lore: ["§Epic", "Apply to: pickaxes", "Tradeable"] }, { name: "Book · Tempest III", c1: "#c9a35a", c2: "#5fa8d3", lore: ["§Epic", "Lightning on critical hits", "Apply to: swords, bows", "Conflicts: none", "Drag onto an item to apply"], glow: true }, { name: "Book · Harvest I", c1: "#c9a35a", c2: "#3ec66d", lore: ["§Epic", "Apply to: hoes", "Tradeable"] }] }) },
    { key: "gallery-02", label: "Config", alt: "Per-enchantment configuration: chance, tier, applicable items, conflicts and cost", make: () => configEditor({ filename: "enchantments.yml", title: "Custom Enchantments Plugin", activeLine: 3, tree: [["plugins", 0, false, true], ["CustomEnchants", 1, false, true], ["enchantments.yml", 2, true], ["tiers.yml", 2, false], ["messages.yml", 2, false]], lines: [[["# Every enchantment has its own block; disable any with enabled: false.", "cmt"]], [["enchantments:", "sec"]], [["  life_steal:", "key"]], [["    enabled: ", "key"], ["true", "bool"]], [["    tier: ", "key"], ["epic", "str"]], [["    max-level: ", "key"], ["3", "num"]], [["    applies-to: ", "key"], ["[sword, axe]", "str"]], [["    conflicts: ", "key"], ["[vampire]", "str"], ["   # cannot stack with", "cmt"]], [["    heal-percent-per-level: ", "key"], ["3", "num"]], [["    cost-levels: ", "key"], ["34", "num"]], [["  tempest:", "key"]], [["    enabled: ", "key"], ["true", "bool"]], [["    tier: ", "key"], ["epic", "str"]], [["    max-level: ", "key"], ["3", "num"]], [["    applies-to: ", "key"], ["[sword, bow]", "str"]], [["    trigger: ", "key"], ["critical_hit", "str"]], [["tiers:", "sec"]], [["  common:    ", "key"], ["{ chance: ", "val"], ["0.62", "num"], [" }", "val"]], [["  rare:      ", "key"], ["{ chance: ", "val"], ["0.24", "num"], [" }", "val"]], [["  epic:      ", "key"], ["{ chance: ", "val"], ["0.11", "num"], [" }", "val"]], [["  legendary: ", "key"], ["{ chance: ", "val"], ["0.03", "num"], [" }", "val"]]] }) },
  ],

  "crates-rewards-plugin": [
    { key: "cover", label: "Crate preview", alt: "Crate preview GUI showing the loot pool with real weight-derived chances", make: () => chestGui({ title: "Rare Crate · Preview", rows: 3, tooltip: 3, items: [{ name: "Iron Ingot", c1: "#d8d8d8", c2: "#a0a0a0", count: 16, lore: ["Common · 60%"] }, { name: "Gold Ingot", c1: "#e8b84a", c2: "#a87a2a", count: 8, lore: ["Uncommon · 25%"] }, { name: "Diamond", c1: "#7fd6e8", c2: "#3fa8c4", count: 3, lore: ["Rare · 11%"] }, { name: "Diamond Sword", c1: "#7fd6e8", c2: "#6b4a2f", lore: ["§Rare · 11%", "Sharpness III", "Unbreaking II", "1 of 3 rare items"], glow: true }, { name: "Enchanted Book", c1: "#c9a35a", c2: "#a05bd6", lore: ["Epic · 3.5%"] }, { name: "Netherite Ingot", c1: "#4a4048", c2: "#2a2428", lore: ["Mythic · 0.5%"], glow: true }, null, null, null, null, null, null, null, null, null, null, null, null, { name: "Rare Key", c1: "#e8b84a", c2: "#8a6a3a", count: 2, lore: ["You have 2 keys", "Right-click the crate to open"] }], sidebar: { title: "Crates", rows: [["Rare keys", "2"], ["Vote keys", "5"], ["Opened", "14"], ["Next milestone", "6 opens"]] } }) },
    { key: "gallery-01", label: "Opening", alt: "A crate opening in game with the reward reveal", make: () => mcOverlay({ tone: "dusk", title: "Rare Crate", subtitle: "Diamond Sword · Sharpness III", bossbar: { label: "Opening…", fill: 78 }, chat: [`<span style="color:#ffaa00">[Crates]</span> You won <span style="color:#55ffff">Diamond Sword</span> from a Rare Crate`], actionbar: "Milestone: 15 of 20 opens", hotbarSel: 0 }) },
    { key: "gallery-02", label: "Loot table config", alt: "A crate configuration with weighted loot entries", make: () => configEditor({ filename: "rare.yml", title: "Crates & Rewards Plugin", activeLine: 6, tree: [["plugins", 0, false, true], ["Crates", 1, false, true], ["crates", 2, false, true], ["vote.yml", 3, false], ["common.yml", 3, false], ["rare.yml", 3, true], ["seasonal.yml", 3, false], ["milestones.yml", 2, false]], lines: [[["# Weights are plain numbers and need not sum to anything.", "cmt"]], [["name: ", "key"], ["'Rare Crate'", "str"]], [["animation: ", "key"], ["roulette", "str"], ["   # roulette | cascade | flash", "cmt"]], [["key-item: ", "key"], ["TRIPWIRE_HOOK", "str"]], [["preview: ", "key"], ["true", "bool"]], [["loot:", "sec"]], [["  - ", "val"], ["{ item: IRON_INGOT, amount: 16, weight: ", "val"], ["600", "num"], [" }", "val"]], [["  - ", "val"], ["{ item: GOLD_INGOT, amount: 8,  weight: ", "val"], ["250", "num"], [" }", "val"]], [["  - ", "val"], ["{ item: DIAMOND, amount: 3,     weight: ", "val"], ["110", "num"], [" }", "val"]], [["  - ", "val"], ["{ item: DIAMOND_SWORD, weight: ", "val"], ["110", "num"], [", enchants: [sharpness:3, unbreaking:2] }", "val"]], [["  - ", "val"], ["{ item: ENCHANTED_BOOK, weight: ", "val"], ["35", "num"], [" }", "val"]], [["  - ", "val"], ["{ item: NETHERITE_INGOT, weight: ", "val"], ["5", "num"], [" }", "val"]], [["milestones:", "sec"]], [["  20: ", "key"], ["{ item: RARE_KEY, amount: 1 }", "val"]], [["  50: ", "key"], ["{ item: EPIC_KEY, amount: 1 }", "val"]]] }) },
  ],

  "player-shops-plugin": [
    { key: "cover", label: "Market search", alt: "The market GUI indexing every player shop, with price history on hover", make: () => chestGui({ title: "Market · Search: iron", rows: 3, tooltip: 1, items: [{ name: "Iron Ingot ×64", c1: "#d8d8d8", c2: "#a0a0a0", count: 64, lore: ["$22 each", "Shop: Dana W.", "Stock: 192"] }, { name: "Iron Ingot ×64", c1: "#d8d8d8", c2: "#a0a0a0", count: 64, lore: ["§$20 each", "Shop: Marcus B.", "Stock: 64", "7-day average: $23", "Lowest listed: $20", "Click to teleport"], glow: true }, { name: "Iron Block ×16", c1: "#d8d8d8", c2: "#c0c0c0", count: 16, lore: ["$190 each", "Shop: Priya R.", "Stock: 48"] }, { name: "Iron Pickaxe", c1: "#d8d8d8", c2: "#6b4a2f", lore: ["$140", "Shop: Tom F.", "Stock: 3"] }, { name: "Iron Ore ×32", c1: "#8b8b8b", c2: "#d8a57a", count: 32, lore: ["$15 each", "Shop: Elena B.", "Stock: 96"] }], sidebar: { title: "Market", rows: [["Listings", "1,284"], ["Your shops", "2 / 5"], ["Balance", "$4,250"]] } }) },
    { key: "gallery-01", label: "My shops", alt: "The player's own shops with stock and takings", make: () => chestGui({ title: "My Shops", rows: 2, tooltip: 0, items: [{ name: "Shop · Spawn Market", c1: "#a8743f", c2: "#3ec66d", lore: ["§12 listings", "Stock: 1,240 items", "Takings today: $410", "Click to manage"], glow: true }, { name: "Shop · Mine Entrance", c1: "#a8743f", c2: "#8b8b8b", lore: ["4 listings", "Stock: 96 items", "Takings today: $62"] }, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { name: "New shop", c1: "#3ec66d", c2: "#2a8a4a", lore: ["3 of 5 slots free", "Place a chest and type /shop create"] }] }) },
    { key: "gallery-02", label: "Shop in world", alt: "Buying from a chest shop in the world, with the transaction in chat", make: () => mcOverlay({ tone: "day", chat: [`<span style="color:#55ff55">[Shop]</span> Bought 16× Iron Ingot from Marcus B. for $320`, `<span style="color:#55ff55">[Shop]</span> Balance: $3,930`], actionbar: "Marcus B.'s shop · Iron Ingot · $20 each · Left-click to buy", scoreboard: { title: "Market", rows: [["Balance", "$3,930"], ["Listings", "1,284"], ["Your shops", "2 / 5"]] }, hotbarSel: 3 }) },
    { key: "gallery-03", label: "Config", alt: "Shop limits per rank and database settings", make: () => configEditor({ filename: "config.yml", title: "Player Shops Plugin", activeLine: 6, tree: [["plugins", 0, false, true], ["PlayerShops", 1, false, true], ["config.yml", 2, true], ["messages.yml", 2, false], ["shops.db", 2, false]], lines: [[["database:", "sec"]], [["  type: ", "key"], ["mysql", "str"], ["   # sqlite is fine for small servers", "cmt"]], [["  host: ", "key"], ["localhost", "str"]], [["  name: ", "key"], ["playershops", "str"]], [["limits:", "sec"]], [["  shops-per-rank:", "key"]], [["    default: ", "key"], ["1", "num"]], [["    member: ", "key"], ["3", "num"]], [["    trusted: ", "key"], ["5", "num"]], [["    staff: ", "key"], ["10", "num"]], [["market:", "sec"]], [["  index-interval-seconds: ", "key"], ["30", "num"]], [["  price-history-days: ", "key"], ["7", "num"]], [["  teleport-to-shop: ", "key"], ["true", "bool"]], [["  tax-percent: ", "key"], ["2", "num"], ["   # goes to the economy sink", "cmt"]]] }) },
  ],

  "minigame-framework": [
    { key: "cover", label: "Game lobby", alt: "The game lobby with queue status in the sidebar", make: () => mcOverlay({ tone: "day", scoreboard: { title: "Lobby", rows: [["Queue", "Capture"], ["Players", "14 / 24"], ["Starting in", "0:42"], ["", ""], ["Map", "Riverside"], ["Team", "Blue"]] }, chat: [`<span style="color:#55ff55">[Game]</span> Queue for Capture: 14 / 24`, `<span style="color:#ffaa00">[Game]</span> Starting in 45 seconds`], actionbar: "Right-click the compass to change game", hotbarSel: 0 }) },
    { key: "gallery-01", label: "Match", alt: "In a match with the boss bar timer and team scores in the sidebar", make: () => mcOverlay({ tone: "night", bossbar: { label: "Capture · 6:12 remaining", fill: 62 }, scoreboard: { title: "Capture", rows: [["Blue", "3"], ["Red", "2"], ["", ""], ["Your kills", "4"], ["Captures", "1"], ["", ""], ["Map", "Riverside"]] }, chat: [`<span style="color:#5555ff">[Blue]</span> Dana captured point B`, `<span style="color:#ff5555">[Red]</span> Marcus was eliminated`], actionbar: "Point C is being captured", hotbarSel: 0 }) },
    { key: "gallery-02", label: "Results", alt: "End-of-round results with the winning team", make: () => mcOverlay({ tone: "dusk", title: "VICTORY", subtitle: "Blue team · 5 – 3", scoreboard: { title: "Results", rows: [["Winner", "Blue"], ["", ""], ["Your kills", "6"], ["Captures", "2"], ["Reward", "+120"], ["", ""], ["Next round", "0:20"]] }, chat: [`<span style="color:#ffaa00">[Game]</span> Arena resetting from schematic…`], hotbarSel: 0 }) },
    { key: "gallery-03", label: "Lobby build", alt: "The game lobby build with queue portals", make: () => world({ build: WORLDS.lobby, sky: "day", view: { pos: [28, 22, 30], look: [0, 6, 0], fov: 58 } }) },
    { key: "gallery-04", label: "Arena config", alt: "Arena registration with queue sizes and reset schematic", make: () => configEditor({ filename: "arenas.yml", title: "Minigame Framework", activeLine: 2, tree: [["plugins", 0, false, true], ["Minigames", 1, false, true], ["arenas.yml", 2, true], ["games", 2, false, true], ["capture.yml", 3, false], ["deathmatch.yml", 3, false], ["schematics", 2, false, true], ["riverside.schem", 3, false]], lines: [[["arenas:", "sec"]], [["  riverside:", "key"]], [["    game: ", "key"], ["capture", "str"]], [["    min-players: ", "key"], ["8", "num"]], [["    max-players: ", "key"], ["24", "num"]], [["    countdown-seconds: ", "key"], ["45", "num"]], [["    round-minutes: ", "key"], ["10", "num"]], [["    reset: ", "key"], ["schematic", "str"], ["   # restores riverside.schem after every round", "cmt"]], [["    schematic: ", "key"], ["riverside", "str"]], [["    teams: ", "key"], ["[blue, red]", "str"]], [["    spawns:", "key"]], [["      blue: ", "key"], ["[-40, 65, 12]", "str"]], [["      red:  ", "key"], ["[38, 65, -10]", "str"]], [["    rewards:", "key"]], [["      win: ", "key"], ["120", "num"]], [["      lose: ", "key"], ["40", "num"]]] }) },
  ],

  "emergency-siren-pack": [
    { key: "cover", label: "Siren library", alt: "The siren library with 24 tones by category and a waveform player", make: () => audioLibrary({ title: "Emergency Siren Pack", categories: [["Wail", 6], ["Yelp", 6], ["Phaser", 4], ["Hi-Lo", 4], ["Air horn", 4]], selected: 0, accent: "#e8554a", tracks: [["Wail · Standard", "0:08", "Wail", "3"], ["Wail · Long", "0:12", "Wail", "2"], ["Yelp · Fast", "0:06", "Yelp", "3"], ["Yelp · Slow", "0:08", "Yelp", "2"], ["Phaser", "0:06", "Phaser", "2"], ["Hi-Lo · European", "0:08", "Hi-Lo", "2"], ["Air horn · Short", "0:03", "Air horn", "2"], ["Air horn · Long", "0:05", "Air horn", "2"]] }) },
    { key: "gallery-01", label: "Vehicle mapping", alt: "Per-vehicle siren mapping so fire, police and EMS differ", make: () => configEditor({ filename: "config.lua", title: "Emergency Siren Pack", activeLine: 4, tree: [["resources", 0, false, true], ["ds_sirens", 1, false, true], ["fxmanifest.lua", 2, false], ["config.lua", 2, true], ["audio", 2, false, true], ["data", 2, false, true]], lines: [[["-- Map tones to vehicle models. Anything unmapped falls back to Default.", "cmt"]], [["Config = {}", "val"]], [["Config.Falloff = { maxDistance = ", "key"], ["180.0", "num"], [", rolloff = ", "key"], ["'linear'", "str"], [", occlusion = ", "key"], ["true", "bool"], [" }", "val"]], [["Config.Vehicles = {", "sec"]], [["  ['police']    = { primary = ", "key"], ["'wail_standard'", "str"], [", secondary = ", "key"], ["'yelp_fast'", "str"], [", horn = ", "key"], ["'airhorn_short'", "str"], [" },", "val"]], [["  ['police2']   = { primary = ", "key"], ["'wail_long'", "str"], [", secondary = ", "key"], ["'phaser'", "str"], [", horn = ", "key"], ["'airhorn_short'", "str"], [" },", "val"]], [["  ['ambulance'] = { primary = ", "key"], ["'hilo_european'", "str"], [", secondary = ", "key"], ["'yelp_slow'", "str"], [", horn = ", "key"], ["'airhorn_long'", "str"], [" },", "val"]], [["  ['firetruk']  = { primary = ", "key"], ["'wail_long'", "str"], [", secondary = ", "key"], ["'hilo_european'", "str"], [", horn = ", "key"], ["'airhorn_long'", "str"], [" },", "val"]], [["  ['default']   = { primary = ", "key"], ["'wail_standard'", "str"], [", secondary = ", "key"], ["'yelp_fast'", "str"], [", horn = ", "key"], ["'airhorn_short'", "str"], [" },", "val"]], [["}", "sec"]], [["Config.Keys = { toggle = ", "key"], ["'Q'", "str"], [", cycle = ", "key"], ["'R'", "str"], [", horn = ", "key"], ["'E'", "str"], [" }", "val"]]] }) },
    { key: "gallery-02", label: "In context", alt: "Emergency units with light bars active, the vehicles the siren tones are mapped to", make: () => exteriorScene({ sky: 0xbfd3e6, items: [`vehicle(s,"sedan",-4,0,0.3,{color:0x1a1c1f,stripe:"#e8e8e8",unit:"104",type:"police"});vehicle(s,"van",4,-1,-0.2,{color:0xf4f4f2,stripe:"#c8202a",unit:"A-12",type:"ems"});`, `buildingBlock(s,0,-18,{w:40,d:14,h:9,rows:2,cols:10});props.tree(s,-16,-6,1.2);`], view: { pos: [7, 2.4, 10], look: [0, 1.1, -1], fov: 44 } }) },
  ],

  "vehicle-engine-sound-pack": [
    { key: "cover", label: "Engine profiles", alt: "The engine audio library with 40 profiles by engine class", make: () => audioLibrary({ title: "Vehicle Engine Sound Pack", categories: [["Four-cylinder", 10], ["Turbo four", 6], ["V6", 8], ["V8", 9], ["V12", 3], ["Electric", 4]], selected: 3, accent: "#e8b84a", tracks: [["I4 · 1.6 NA", "0:14", "Four-cylinder", "idle · mid · redline"], ["I4 · 2.0 Turbo", "0:14", "Turbo four", "idle · mid · redline · spool"], ["V6 · 3.5", "0:14", "V6", "idle · mid · redline"], ["V8 · 5.0 Muscle", "0:16", "V8", "idle · mid · redline · pops"], ["V8 · 6.2 Supercharged", "0:16", "V8", "idle · mid · redline · whine"], ["V12 · 6.5", "0:16", "V12", "idle · mid · redline"], ["Electric · Performance", "0:12", "Electric", "idle · mid · whine"], ["Diesel · 3.0 Truck", "0:14", "Four-cylinder", "idle · mid · redline"]] }) },
    { key: "gallery-01", label: "Profile mapping", alt: "Mapping engine profiles to vehicles with optional turbo and exhaust layers", make: () => configEditor({ filename: "config.lua", title: "Vehicle Engine Sound Pack", activeLine: 5, tree: [["resources", 0, false, true], ["ds_engine_audio", 1, false, true], ["fxmanifest.lua", 2, false], ["config.lua", 2, true], ["audio", 2, false, true]], lines: [[["-- Layers default to off: a turbo layer is wrong on a naturally aspirated car.", "cmt"]], [["Config = {}", "val"]], [["Config.Volume = ", "key"], ["0.8", "num"]], [["Config.Vehicles = {", "sec"]], [["  ['sultan']   = { profile = ", "key"], ["'i4_20_turbo'", "str"], [", turbo = ", "key"], ["true", "bool"], [", blowoff = ", "key"], ["true", "bool"], [" },", "val"]], [["  ['dominator'] = { profile = ", "key"], ["'v8_50_muscle'", "str"], [", pops = ", "key"], ["true", "bool"], [" },", "val"]], [["  ['comet']    = { profile = ", "key"], ["'v6_35'", "str"], [" },", "val"]], [["  ['zentorno'] = { profile = ", "key"], ["'v12_65'", "str"], [" },", "val"]], [["  ['raiden']   = { profile = ", "key"], ["'electric_performance'", "str"], [" },", "val"]], [["  ['default']  = { profile = ", "key"], ["'i4_16_na'", "str"], [" },", "val"]], [["}", "sec"]], [["Config.Layers = { load = ", "key"], ["true", "bool"], [", rpm = ", "key"], ["true", "bool"], [" }", "val"]]] }) },
    { key: "gallery-02", label: "Mapped vehicles", alt: "Hatchback, coupe, sedan and SUV — the vehicle classes the profiles cover", make: () => exteriorScene({ sky: 0xc4d8ea, items: [`vehicle(s,"hatch",-9,0,0,{color:0x3d5a80,lightbar:false,livery:false});vehicle(s,"coupe",-3,0,0,{color:0xc44536,lightbar:false,livery:false,gloss:0.2});vehicle(s,"sedan",3.5,0,0,{color:0x8a8f96,lightbar:false,livery:false});vehicle(s,"suv",10.5,0,0,{color:0x2b2f36,lightbar:false,livery:false});`, `buildingBlock(s,0,-20,{w:56,d:14,h:8,rows:2,cols:13});props.tree(s,-24,-8,1.3);`], view: { pos: [2, 3.4, 24.5], look: [2, 1.2, 0], fov: 44 } }) },
  ],
}

export const BENCHMARK = Object.keys(PLANS)

/* Batch 4 lives in its own file; merged here so run.mjs sees one plan set. */
import { PLANS4 } from "./plan4.mjs"
Object.assign(PLANS, PLANS4)
