// In-template copy written in the voice of the sample business, plus the
// store-listing pitch that describes the template itself. Keeping the two
// apart means a buyer never has to strip "this template…" sentences out of
// their own homepage. Keyed by brand; merged over catalog.mjs entries.

export const COPY = {
  /* ---------------------------------------------------------------- */
  /* Websites                                                          */
  /* ---------------------------------------------------------------- */
  Marisol: {
    pitch: ["Marisol is a multi-page website template for a dental clinic. It leads with the three things nervous patients want answered — can I get in soon, what will it cost, will it hurt — and puts online booking one tap away on every page.", "Five pages ship ready to edit: home, about, services, pricing with three care plans, and contact. The mint-and-charcoal palette and rounded components feel clinical without feeling cold."],
    site: { lede: "Same-week appointments, transparent pricing and a team that explains every step before it happens. Modern dentistry for families who would rather not think about the dentist.", about: { paragraphs: ["We opened Marisol because too many people put off care after one bad experience. So we built a practice around the nervous patient: longer first appointments, written plans you take home, and prices you can see before you sit down.", "Four dentists, two hygienists and a front desk that answers the phone. Weekend hours, finance on every treatment, and a kids' corner that makes the second visit easier than the first."] } },
  },
  Halden: {
    pitch: ["Halden is an image-led website template for an architecture, interiors or landscape studio. A dark, editorial layout gives project photography room to breathe, with a project index, case-study pages and a journal.", "Five pages: home, about, services, gallery and contact. The typographic system is a serif display over a humanist sans, tuned for long captions and short manifestos."],
    site: { lede: "We design houses, civic buildings and neighbourhoods that belong to their place — low in energy, generous in light, built to be adapted for a century.", about: { paragraphs: ["Halden is a studio of fourteen architects and designers working from a converted foundry. Since 2009 we have completed one hundred and forty projects, from a single-room extension to a town library, with the same attention at every scale.", "We are Passivhaus-certified designers, RIBA chartered, and unusually fond of the planning process. Most of our work comes from people who have lived in or visited a building we made."] } },
  },
  Corvina: {
    pitch: ["Corvina is a restaurant website template with the menu, hours and a reservation button exactly where hungry people look for them. Warm editorial styling, an accessible HTML menu, and a private-dining page with its own enquiry form.", "Five pages: home, about, menus, gallery and contact. The serif display and sand palette suit bistros, wine bars and neighbourhood restaurants."],
    site: { lede: "A forty-eight-seat neighbourhood bistro with a short menu that changes every few weeks, a wine list built around small producers, and a kitchen you can see from every table.", about: { paragraphs: ["Corvina opened in 2015 on the corner of Market Lane with two cooks, one oven and a menu written that morning. The oven is bigger now; the habit of writing the menu daily has not changed.", "Vegetables come from two farms within an hour's drive and are named on the menu. The room seats forty-eight, the private dining room seats twelve, and the bar keeps a stool for people eating alone."] } },
  },
  Ferrow: {
    pitch: ["Ferrow is a plain-English website template for a law firm or legal consultancy. Practice areas are written in the client's language, fees are published where they can be, and every page ends with a way to start a fixed-fee consultation.", "Five pages: home, about, services, pricing with fixed-fee packages, and contact with a matter-type selector. The slate palette and serif headings read as established without feeling stuffy."],
    site: { lede: "Employment, property and commercial law for people and small businesses — explained in plain English, priced up front, and handled by a lawyer who answers the phone.", about: { paragraphs: ["Ferrow was founded by three solicitors who had spent twenty-five years between them at larger firms and wanted to practise law the way clients actually experience it: one lawyer, one clear plan, one predictable bill.", "We publish fixed fees for the matters most people need — a first consultation, a will, a business starter package — and quote everything else in writing before any work starts. We are regulated, insured and happy to say so."] } },
  },
  Ostberg: {
    pitch: ["Ostberg is a website template for an accounting or bookkeeping firm that sells a monthly service rather than a list of tasks. Packages are shown as prices, the team is visible, and a client-login slot sits in the header.", "Five pages: home, about, services, pricing with three monthly packages, and contact. The ocean palette and monospaced accents suit firms that want to look precise and modern."],
    site: { lede: "Monthly bookkeeping, tax done early and a dedicated accountant who explains your numbers in plain language. Fixed monthly fees, cloud software, no year-end surprises.", about: { paragraphs: ["Ostberg is a nine-person accountancy practice for sole traders, small companies and growing teams. We close the books by the tenth of every month and send a one-page summary that tells you what to do next.", "Every client has a named accountant, a quarterly planning call and a published fee. We work in the cloud, migrate you from wherever you are, and answer email within a working day."] } },
  },
  Lindqvist: {
    pitch: ["Lindqvist is a portfolio-first website template for an interior design studio. One unhurried statement, one image, and project pages that combine photography with short process notes so prospective clients understand how the studio works.", "Five pages: home, about, services, gallery and contact with a budget-range field. Warm clay and stone tones flatter interior photography of any style."],
    site: { lede: "Residential and hospitality interiors with a point of view — layouts that make homes feel generous, restaurants that work on a Friday night, and furniture chosen for the way you actually live.", about: { paragraphs: ["Lindqvist is a four-person interior design studio founded in 2012. We have completed more than ninety projects across twelve countries, from a one-room studio flat to a forty-room hotel.", "Every project starts with a conversation in the space. We present concepts in person, manage contractors and site visits, and finish with a styling day that puts the last cushion where it belongs."] } },
  },
  Tamsin: {
    pitch: ["Tamsin is a website template for a yoga, pilates or wellness studio, written for the person who has never been. Soft colours, generous spacing, a schedule that reads on a phone in a car park, and pricing with an intro offer.", "Five pages: home, about, classes, pricing with three memberships, and contact. The sage palette and rounded components feel calm without tipping into cliché."],
    site: { lede: "Thirty-eight classes a week across two studios, from slow restorative sessions to small-group reformer pilates. Beginners welcome, first class free, book from your phone.", about: { paragraphs: ["Tamsin opened in an old chapel in 2017 with one room and a rented set of mats. Today there are two studios, nine teachers and a beginners course that has introduced more than a thousand people to a practice they thought was not for them.", "We keep classes small, cue for real bodies rather than photographs, and never make anyone feel they should already know what a downward dog is. Tea is free and the props are always out."] } },
  },
  Brightwater: {
    pitch: ["Brightwater is a phone-first website template for a plumbing, heating or home-services company. A sticky call button on mobile, price-from tables, certifications up front and a service-area page: everything a customer checks before they ring.", "Five pages: home, about, services, pricing with a care plan, and contact. The cobalt palette and condensed sans read as dependable and fast."],
    site: { lede: "Emergency plumbing and heating, twenty-four hours a day, with fixed prices quoted before work starts and engineers who tidy up after themselves.", about: { paragraphs: ["Brightwater started with one van in 2011. There are twelve now, all tracked, all stocked, all driven by certified engineers who have been with us for an average of six years.", "We quote before we start, we charge what we quoted, and we guarantee every boiler we install for five years. If we can't fix it on the first visit, we tell you why and what it will cost."] } },
  },
  Kestwood: {
    pitch: ["Kestwood is a website template for a veterinary practice, designed from the point of view of the anxious owner at 2am. Emergency details are pinned to the header, prices are plain, and the health-plan page turns an annual bill into a small monthly one.", "Five pages: home, about, services, pricing with three health plans, and contact with a register-a-pet form. The lime palette and rounded type feel friendly and competent."],
    site: { lede: "Six vets, in-house diagnostics and a twenty-four-hour emergency line. Same-day appointments, health plans from twelve dollars a month, and a team that treats your pet like their own.", about: { paragraphs: ["Kestwood has looked after the animals of this town since 1998. Three thousand two hundred pets are registered with us, from hamsters to Great Danes, and a vet is on call every single night.", "We invested in an in-house lab, x-ray and ultrasound so most questions are answered in one visit. Our health plans spread the cost of prevention, and our reminders mean you never miss a booster."] } },
  },
  Alderyn: {
    pitch: ["Alderyn is an image-first website template for a wedding or portrait photographer. Quiet rose and paper tones, editorial serif headings and galleries that let the images carry the emotion. Pricing is three clear packages, not 'enquire'.", "Five pages: home, about, gallery, pricing and contact with date and venue fields. Suits documentary photographers, filmmakers and small studios."],
    site: { lede: "Documentary wedding photography for couples who want the day as it actually felt — unposed, unhurried and, when you look back in thirty years, still true.", about: { paragraphs: ["Alderyn is two photographers who have covered two hundred and ten weddings across fourteen countries. We work quietly, in the background, and we never ask you to look at the camera.", "Every couple gets an engagement session first, so the camera feels familiar by the day itself. Galleries arrive within eight weeks, sneak peeks within days, and albums are designed together afterwards."] } },
  },
  Solvay: {
    pitch: ["Solvay is a membership-driven website template for a coworking space or flexible office. Tour booking sits above the fold, memberships are easy to compare, and meeting rooms and events have their own pages.", "Five pages: home, about, spaces, pricing with three memberships, and contact with a tour-booking form. The dark ink palette signals a space for serious work."],
    site: { lede: "Hot desks, dedicated desks and private offices for people who take work seriously — with meeting rooms included, twenty-four-hour access and a community that shows up for Friday breakfast.", about: { paragraphs: ["Solvay Works occupies three floors of a former print works on Union Street. Two hundred and eighteen members work here today: freelancers, remote teams and startups that have grown from two desks to twelve.", "Memberships are month to month, meeting rooms come with credits rather than fees, and the events calendar is run by members, not by us. Tours run every weekday; the coffee is on us."] } },
  },
  Moravia: {
    pitch: ["Moravia is a booking-focused website template for a boutique hotel, inn or guesthouse. The booking bar sits on every page, rooms are described honestly, and the local-area content guests search for before booking is part of the template.", "Five pages: home, about, rooms, gallery and contact. Warm sand tones and a printed-feeling serif make photography look like a magazine spread."],
    site: { lede: "A twelve-room house by the water, one minute from the harbour, with a restaurant worth staying in for and nothing you have to do. Book direct for the best rate and free cancellation to forty-eight hours.", about: { paragraphs: ["Moravia was a harbourmaster's house before it was a hotel. We kept the staircase, the walled garden and the view, and added twelve rooms that are all different because the house is.", "Breakfast is included and made from what the boats and the farms bring in. Dinner is a short seasonal menu served to guests and locals alike. Dogs are welcome; so are children; so is doing nothing at all."] } },
  },
  "Pelican Bay": {
    pitch: ["Pelican Bay is a bookings-first website template for a surf school, water-sports centre or outdoor activity business. Big type, ocean tones and buttons you can hit with a wet thumb; sessions show level, duration and price up top.", "Five pages: home, about, sessions, pricing with a season pass, and contact for group and school bookings. A conditions block on the homepage is ready for a live surf-report embed."],
    site: { lede: "Surf lessons, paddleboard tours and coasteering from the hut on the beach. Groups of six, all kit included, ages eight and up, April to October.", about: { paragraphs: ["Pelican Bay has been teaching people to stand up on a wave since 2008. Eight instructors, all lifeguard-qualified, all still stoked, all of whom learned on this same beach.", "We keep groups to six so everyone gets coached, check the tide so you don't have to, and include wetsuits, boards and photos in every session. The kids' club runs all summer; the season pass runs all season."] } },
  },
  Redfern: {
    pitch: ["Redfern is a website template for a craft brewery, distillery or taproom with the swagger of a good label: condensed type, a dark palette and a beer list that doubles as a taproom board. Tours, events and a shop layout are included.", "Five pages: home, about, taproom, gallery and contact. The charcoal-and-amber palette suits breweries, distilleries, roasteries and bars."],
    site: { lede: "Fourteen beers on tap, a kitchen residency that changes monthly, brewery tours every Saturday and a taproom that welcomes dogs, children and people who don't like beer yet.", about: { paragraphs: ["Redfern Brewing Co. started in a garage in 2016 with a fifty-litre kit and an unreasonable pale ale. The brewhouse is thirty times bigger now and the pale ale is still on tap one.", "We brew fourteen beers, can most of them, ship them within forty-eight hours, and open the taproom Thursday to Sunday. Tours end at the bar, which is the only sensible place for a tour to end."] } },
  },
  Whitlow: {
    pitch: ["Whitlow is a website template for a physiotherapy, chiropractic or sports-injury clinic that turns a symptom search into an appointment. Condition pages explain the first visit, therapists show real credentials, and booking is on every page.", "Five pages: home, about, treatments, pricing with a rehab block, and contact. The mint-and-charcoal palette and large type suit a patient reading on a phone in pain."],
    site: { lede: "Physiotherapy for sports injuries, back and neck pain, post-surgery rehab and women's health. No referral needed, evening appointments, and a plan on day one.", about: { paragraphs: ["Whitlow Clinic is seven physiotherapists, a rehab gym and a front desk that books you in the same week. We treat runners, desk workers, new parents and people six weeks out from a knee replacement, often on the same morning.", "Every first appointment lasts forty-five minutes and ends with a written plan and a home programme. Follow-ups are as many as you need and no more; strength sessions in the gym keep the problem from coming back."] } },
  },
  Casterly: {
    pitch: ["Casterly is a listings-ready website template for a real estate agency or property consultancy. A listings grid, a free-valuation funnel and area guides — the three pages that generate almost every enquiry an agency receives.", "Five pages: home, about, services, gallery as a listings layout, and contact with a valuation form. The slate palette and rounded sans feel polished and local."],
    site: { lede: "Sales, lettings and valuations across the city since 2004. Professional photography and floor plans on every listing, no sale no fee, and a free valuation within twenty-four hours.", about: { paragraphs: ["Casterly & Co. has sold homes on these streets for twenty years. We know which side of the park sells faster, which schools move prices and which vendors will take a sensible offer in November.", "Every listing gets professional photography, a floor plan and a launch on every portal on day one. We chase the chain, we keep you informed, and we publish our fees so there is nothing to negotiate later."] } },
  },

  /* ---------------------------------------------------------------- */
  /* Landing pages                                                     */
  /* ---------------------------------------------------------------- */
  Loopwise: {
    pitch: ["Loopwise is a landing page template for a habit, routine or wellbeing app: an app-window hero, benefits told as outcomes, a three-tier pricing table and a FAQ that handles objections before support does.", "Two pages ship: the landing page with anchor navigation and a contact page. The plum palette and rounded geometry suit consumer apps."],
    site: { lede: "Loopwise turns the habits you keep meaning to start into routines you actually keep — with one-tap check-ins, streaks that forgive a rest day, and reminders that learn when you really do things." },
  },
  Signalbay: {
    pitch: ["Signalbay is a B2B SaaS landing page template for an email marketing or newsletter tool: dashboard preview, a benefits grid written for marketers, pricing by contact count and a FAQ tuned for procurement questions.", "Two pages: landing and contact. The dark ink palette and geometric grotesk read as a serious product for serious teams."],
    site: { lede: "Signalbay is email marketing for teams who ship: a drag-and-drop editor, deliverability built in, segments that update themselves, and reports that tell you what to send next." },
  },
  Draftly: {
    pitch: ["Draftly is a landing page template for a document, proposal or e-signature tool aimed at freelancers and agencies: a document-style preview, benefits framed around winning clients and simple per-seat pricing.", "Two pages: landing and contact. Paper tones and a serif display give it the feel of a well-set proposal."],
    site: { lede: "Draftly writes, sends and signs the proposal so you can get on with the work: templates for forty industries, legally binding e-signatures and a deposit collected the moment a client says yes." },
  },
  Tidewatch: {
    pitch: ["Tidewatch is a developer-facing landing page template for a monitoring, status-page or observability product: a live-looking dashboard preview, benefits that speak to on-call engineers, and pricing per monitor.", "Two pages: landing and contact. The midnight palette and monospaced accents look at home next to a terminal."],
    site: { lede: "Tidewatch checks your endpoints every thirty seconds from twelve regions, wakes the right person when something breaks, and gives your customers a status page they can subscribe to." },
  },
  Cartogram: {
    pitch: ["Cartogram is a landing page template for field-service, dispatch or scheduling software: it shows the schedule board, sells time saved per dispatcher, and prices per technician with a demo-led enterprise tier.", "Two pages: landing and contact. The cobalt palette and condensed sans suit operations software."],
    site: { lede: "Cartogram puts every job, every van and every technician on one screen: drag-and-drop dispatch, live tracking, offline job sheets and invoices sent before the van leaves the driveway." },
  },
  Pocketledger: {
    pitch: ["Pocketledger is a consumer-fintech landing page template for an expense, receipts or budgeting app: warm, trustworthy, phone-first, with benefits about time saved and money found, and transparent pricing.", "Two pages: landing and contact. The sage palette and friendly rounded type avoid the coldness of most finance products."],
    site: { lede: "Pocketledger sorts your expenses while you get on with your life: snap a receipt and it's captured, connect a bank and it's matched, and at tax time export a report your accountant will thank you for." },
  },
  Lumenary: {
    pitch: ["Lumenary is a product landing page template for consumer hardware or a smart-home device: big, dark and cinematic, with benefits told through moments of the day, a specifications section and a pre-order pricing block.", "Two pages: landing and contact. The charcoal-and-amber palette makes product renders glow."],
    site: { lede: "Lumenary is a smart bulb that follows the day: cool and bright in the morning, warm and low at night, instant to respond, and at home with every assistant you already use." },
  },
  Sproutly: {
    pitch: ["Sproutly is a lifestyle app landing page template with soft greens, a phone preview, benefits with personality and a simple free-versus-plus pricing choice. Built for plant-care, gardening and hobby apps.", "Two pages: landing and contact. The lime palette and rounded shapes feel friendly on a phone."],
    site: { lede: "Sproutly identifies your plants from a photo, tells you when to water and when not to, measures the light in your flat, and diagnoses the yellow leaf before it becomes a problem." },
  },
  Quietdesk: {
    pitch: ["Quietdesk is a deliberately minimal landing page template for a focus, productivity or writing tool: generous white space, a serif voice and a product story told in a few honest sentences. Ideal for indie tools with a strong point of view.", "Two pages: landing and contact. Paper tones and a one-time-purchase pricing block suit independent software."],
    site: { lede: "Quietdesk gives you ninety minutes of nothing else: distractions blocked on every device, a soundscape that actually loops, and one line at the end that says what got done." },
  },
  Fleetline: {
    pitch: ["Fleetline is an enterprise-leaning landing page template for logistics, routing or fleet software: a route-planning preview, ROI-driven benefits and pricing that leads to a demo rather than a checkout.", "Two pages: landing and contact. The slate palette and grotesk type read as capable and calm."],
    site: { lede: "Fleetline plans thousands of stops in seconds, gives drivers a day that makes sense, and gives customers an arrival window they can trust — more stops per route, fewer miles, fewer calls." },
  },

  /* ---------------------------------------------------------------- */
  /* Storefronts                                                       */
  /* ---------------------------------------------------------------- */
  "Vellum & Vine": {
    pitch: ["Vellum & Vine is a storefront template for stationery, paper goods and gift brands: a warm paper palette, product cards that show texture, and a product page with variants, swatches and honest details.", "Six pages: home, shop, product, cart, about and contact. Every page a shop needs before the checkout hand-off, ready to connect to your commerce platform."],
    site: { lede: "Notebooks, planners and pens made slowly in small batches — paper that takes fountain-pen ink, bindings that lie flat, and gift sets wrapped by hand.", about: ["Vellum & Vine began at a kitchen table with a sewing frame and a ream of paper that was better than anything we could buy. We still bind the notebooks ourselves, in batches of two hundred.", "Everything we sell we use: the planner is the one on our desk, the ink is the one in our pens. If a product doesn't survive a year of daily use, it doesn't go in the shop."] },
  },
  Northstitch: {
    pitch: ["Northstitch is a high-contrast apparel storefront template for streetwear, merch and drop-driven brands: oversized type, a drop-style hero, a product grid with size and colour variants and a cart that feels fast.", "Six pages: home, shop, product, cart, about and contact. The charcoal palette makes product photography pop."],
    site: { lede: "Heavyweight basics and limited drops, built for daily wear: 320gsm tees, brushed fleece, canvas jackets and the occasional restock.", about: ["Northstitch makes clothes for people who wear the same three things every week and want them to last. We release small drops, restock the essentials, and never put anything on sale that we wouldn't wear ourselves.", "Everything is unisex, sized XS to XXL, and cut boxy on purpose. Exchanges are free because sizing is personal."] },
  },
  Terrafirma: {
    pitch: ["Terrafirma is a gallery-like storefront template for ceramics, homeware and handmade goods: clay tones, generous whitespace and product pages that explain how each piece is made and cared for. A seconds category sells imperfect stock honestly.", "Six pages: home, shop, product, cart, about and contact. Suits ceramics, glass, textiles and small-batch homeware."],
    site: { lede: "Hand-thrown stoneware for every day: mugs, plates, bowls and lamps made in our studio, glazed in small batches and fired twice.", about: ["Terrafirma is two potters, one kiln and a shop at the front of the studio. We throw everything on the wheel, so every piece is slightly different, and we sell the ones with glaze marks as seconds rather than throwing them away.", "Our glazes are food-safe, our clay is stoneware, and everything survives the dishwasher. If a piece arrives broken, we replace it; that is the whole returns policy."] },
  },
  Bloomhaus: {
    pitch: ["Bloomhaus is a delivery-focused storefront template for a florist or plant shop: occasion categories, same-day messaging above the fold, and a product page built for gifting with a message field and delivery-date picker.", "Six pages: home, shop, product, cart, about and contact. The rose palette and rounded shapes feel fresh and generous."],
    site: { lede: "Seasonal bouquets, houseplants and everlasting stems, hand-tied in the shop and delivered the same day when you order before one.", about: ["Bloomhaus is a florist on the corner of Mill Street with a delivery van and a soft spot for whatever is best at the market that morning. We buy from local growers first and never from a catalogue.", "Every bouquet is hand-tied, delivered in water, and guaranteed fresh for a week. Subscriptions bring flowers weekly or monthly; gift boxes come with a handwritten card."] },
  },
  Ridgepack: {
    pitch: ["Ridgepack is a spec-driven storefront template for outdoor, cycling or adventure gear: weight, capacity and materials on the product card, and a product page that leads with a comparison-friendly spec section and a 'tested on' note.", "Six pages: home, shop, product, cart, about and contact. The dark forest palette keeps product photography vivid."],
    site: { lede: "Packs, shelter, layers and footwear tested on real trails — every product weighed, every seam guaranteed for life, every return free for sixty days.", about: ["Ridgepack was started by two guides who were tired of gear that failed on the third day. We design in a small workshop, test on the ridges outside the door, and only sell what comes back intact.", "Weights on our site are measured, not quoted. Repairs are free for life. Sixty days on the trail is enough time to decide, so that is our returns window."] },
  },
  "Cocoa & Co": {
    pitch: ["Cocoa & Co is a food storefront template with warm tones and generous product imagery: origin details on each bar, gift bundles, and subscription boxes as first-class products. Suits chocolate, coffee, tea and artisan food brands.", "Six pages: home, shop, product, cart, about and contact. The clay palette and serif display feel indulgent without shouting."],
    site: { lede: "Bean-to-bar chocolate from single estates, roasted and tempered in our workshop in forty-kilo batches — bars, tasting flights, drinking chocolate and a monthly box.", about: ["Cocoa & Co makes chocolate from two ingredients and one origin at a time. We buy beans directly from farms we have visited, roast them ourselves, and put the estate on the front of the wrapper.", "Everything ships in insulated packaging with a handwritten note if it's a gift. If a bar arrives bloomed or broken, we replace it and we'd like to know."] },
  },
  "Kindred Kids": {
    pitch: ["Kindred Kids is a family storefront template for toys, children's clothing or gifts: age-based categories, safety details on every product page, and a cheerful palette that stays readable for tired parents.", "Six pages: home, shop, product, cart, about and contact. Rounded shapes and a bright-but-calm palette keep it playful without becoming loud."],
    site: { lede: "Toys that grow with them: wooden, well-made and safety-tested, sorted by age so you find the right thing in a minute — gift wrapping included.", about: ["Kindred Kids was started by two parents who were tired of toys that broke by Tuesday. Everything we sell is tested to toy-safety standards, chosen for how long it stays interesting, and sorted by the age it actually suits.", "Gift wrapping is included on every order because most of our orders are gifts. Free shipping starts at forty dollars; returns are simple because children are unpredictable."] },
  },
  Auralite: {
    pitch: ["Auralite is a sleek electronics storefront template for audio gear, headphones and accessories: feature callouts on the product page, a comparison-ready spec list and trust signals for higher-ticket purchases.", "Six pages: home, shop, product, cart, about and contact. The dark ink palette and restrained accent suit premium electronics."],
    site: { lede: "Studio headphones, wireless earbuds, desktop speakers and the cables that connect them — tuned flat, built to be repaired, and yours to try at home for forty-five days.", about: ["Auralite designs audio gear for people who listen for a living and people who just listen a lot. Our headphones are tuned flat, our pads and cables are replaceable, and our repair desk fixes things other brands would replace.", "Every product ships free in two days, comes with a two-year warranty and can go back within forty-five days if it isn't right. We'd rather you tried it in your room than in a shop."] },
  },
}
